/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HomeUI.DataModelAccessoryControlViewController : _TtGC6HomeUI36HomeUIAccessoryControlViewControllerC13HomeDataModel9DataModel_ <HUPresentationDelegateHost> {
    void item;
    void presentationDelegate;
}

@property (nonatomic, readonly) NSString *description;
@property (nonatomic) <HUPresentationDelegate> *presentationDelegate;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (id)presentationDelegate;
- (void)setPresentationDelegate:(id)arg1;

@end
