/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUTipsManager : NSObject

+ (id)sharedManager;

- (void)donateAppLaunchEvent;
- (void)warmUp;

@end
