/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CDMFoundation.framework/CDMFoundation
 */

@interface _TtC13CDMFoundationP33_833AF4D03D8E219706164CB26EE43F4313DateAttribute : _TtC13CDMFoundationP33_833AF4D03D8E219706164CB26EE43F4322CompositeAttributeBase

@end
