/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CDMFoundation.framework/CDMFoundation
 */

@interface CDMAssetsDelegateHandler : NSObject {
    long long  _assetAvailabilityType;
    NSArray * _assetSetNames;
    NSMutableDictionary * _assetsAvailabilities;
    <CDMTrialAssetsDelegate> * _delegate;
}

- (void).cxx_destruct;
- (bool)assetsAvailableForAssetSet:(id)arg1 forLocale:(id)arg2;
- (bool)assetsUnavailableForAssetSet:(id)arg1;
- (id)initWithAssetsDelegate:(id)arg1 forAssetSets:(id)arg2 withAssetAvailabilityType:(long long)arg3;
- (void)notifyDelegate;

@end
