/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CDMFoundation.framework/CDMFoundation
 */

@interface CDMFoundation.SiriReferenceResolutionProxy : _TtCs12_SwiftObject {
    void latestEntityCollection;
    void queue;
    void referenceResolutionClient;
}

@end
