/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriMailInternal.framework/SiriMailInternal
 */

@interface SiriMailInternal.PrivacyDisclosureManager : _TtCs12_SwiftObject {
    void preflightManager;
}

@end
