/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PassKitCore.ProvisioningContext : _TtCs12_SwiftObject {
    void analyticsSession;
    void destinationDevice;
    void flowType;
    void groupsController;
    void hostApplicationBundleIdentifier;
    void managingDevice;
    void provisioningController;
    void referralSource;
    void sceneIdentifier;
    void teamIdentifier;
}

@end
