/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKAddHomeKeyPassConfiguration : PKAddSecureElementPassConfiguration {
    NSArray * _appletTypes;
}

@property (nonatomic, readonly) NSArray *appletTypes;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithPaymentMethodTypes:(id)arg1;
- (id)appletTypes;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithPaymentMethodTypes:(id)arg1;

@end
