/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DiskImages2.framework/DiskImages2
 */

@interface DICommonAttach : NSObject

+ (bool)DI1_attachWithDictionary:(id)arg1 BSDName:(id*)arg2 error:(id*)arg3;
+ (bool)DI2_attachWithParams:(id)arg1 BSDName:(id*)arg2 error:(id*)arg3;
+ (bool)defaultDiskImageAttach:(id)arg1 BSDName:(id*)arg2 error:(id*)arg3;
+ (bool)diskImageAttach:(id)arg1 BSDName:(id*)arg2 error:(id*)arg3;
+ (bool)diskImageAttach:(id)arg1 readOnly:(bool)arg2 autoMount:(bool)arg3 BSDName:(id*)arg4 error:(id*)arg5;

@end
