/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFFeatureAvailability : WBSFeatureAvailability

+ (bool)_isEligibleForDomain:(unsigned long long)arg1;
+ (bool)_shouldShowChineseFeatures;
+ (bool)_shouldShowRussianFeatures;
+ (bool)isBrowserSelectionSheetEligible;
+ (bool)isHSWADisabled;
+ (bool)isTabBarAvailableForScreenSize:(struct CGSize { double x1; double x2; })arg1;
+ (bool)isYttriumEligible;
+ (bool)supportsCVV;

@end
