/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatform.framework/IntelligencePlatform
 */

@interface _TtCC20IntelligencePlatform37EntityResolutionCAEventLoggerProvider11GuardedData : _TtCs12_SwiftObject {
    void eventLoggers;
}

@end
