/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriEntityMatcher.framework/SiriEntityMatcher
 */

@interface SEMCascadeFieldTypeFilter : NSObject <SEMEntityFilter> {
    unsigned short  _fieldType;
}

@property (nonatomic, readonly) unsigned short fieldType;

+ (id)filterFromKVFieldTypeNumber:(id)arg1;

- (id)description;
- (unsigned char)entityType;
- (unsigned short)fieldType;
- (unsigned long long)hash;
- (id)initWithFieldType:(unsigned short)arg1 error:(id*)arg2;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToCascadeFieldTypeFilter:(id)arg1;

@end
