/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriEntityMatcher.framework/SiriEntityMatcher
 */

@interface SEMFTSMatcher : NSObject {
    NSObject<SEMFTSAccessProvider> * _ftsAccessProvider;
}

- (void).cxx_destruct;
- (id)_allFTSRecordsWithExternalIds:(id)arg1 database:(id)arg2 error:(id*)arg3;
- (id)_matchFTSRecordsWithSearchCriteria:(id)arg1 database:(id)arg2 error:(id*)arg3;
- (id)initWithFTSAccessProvider:(id)arg1;
- (id)searchFTSWithCriteria:(id)arg1 error:(id*)arg2;

@end
