/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriEntityMatcher.framework/SiriEntityMatcher
 */

@interface SEMTrialUtilities : NSObject

+ (bool)getBoolTrialValueForTrialCli:(id)arg1 withFactor:(id)arg2 andNamespaceName:(id)arg3;
+ (long long)getLongTrialValueForTrialCli:(id)arg1 withFactor:(id)arg2 andNamespaceName:(id)arg3;
+ (void)refreshTrialFactors;

@end
