/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMContinuityCaptureCore.framework/CMContinuityCaptureCore
 */

@interface CMContinuityCaptureTransportDeviceNWStream : NSObject <ContinuityCaptureTransportDeviceStream> {
    long long  _entity;
    NSString * _identifier;
    NSUUID * _nwClientID;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) long long entity;
@property (readonly) unsigned long long hash;
@property (readonly, retain) NSString *streamIdentifier;
@property (readonly, retain) NSUUID *streamUUID;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)cipherKeyforSessionID:(id)arg1;
- (id)description;
- (void)enqueueResponse:(id)arg1 identifier:(id)arg2;
- (long long)entity;
- (id)initForIdentifier:(id)arg1 nwClientID:(id)arg2;
- (void)sendMessage:(id)arg1 message:(id)arg2 completion:(id /* block */)arg3;
- (id)streamIdentifier;
- (id)streamUUID;

@end
