/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MicroLocationUtilities.framework/MicroLocationUtilities
 */

@interface ULDarwinNotificationRecord : NSObject {
    id /* block */  _handler;
    NSString * _notificationName;
    NSNumber * _registrationToken;
}

@property (nonatomic, copy) id /* block */ handler;
@property (nonatomic, retain) NSString *notificationName;
@property (nonatomic, retain) NSNumber *registrationToken;

- (void).cxx_destruct;
- (id /* block */)handler;
- (id)initWithNotificationName:(id)arg1 registrationToken:(id)arg2 handler:(id /* block */)arg3;
- (id)notificationName;
- (id)registrationToken;
- (void)setHandler:(id /* block */)arg1;
- (void)setNotificationName:(id)arg1;
- (void)setRegistrationToken:(id)arg1;

@end
