/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClarityFoundation.framework/ClarityFoundation
 */

@interface CLFMusicSettings_GeneratedCode : CLFBaseSettings

@property (nonatomic, retain) NSArray *selectedPlaylists;

+ (id)allPreferenceSelectorsAsStrings;
+ (id)domainName;
+ (id)sharedInstance;

- (id)init;
- (id)selectedPlaylists;
- (void)setSelectedPlaylists:(id)arg1;

@end
