/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/InstallProgress.framework/InstallProgress
 */

@interface IPGlobalInstallableStateSourceDefaultBehavior : IPGlobalInstallableStateSourceXPCBehavior

+ (id)sharedInstance;

@end
