/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreviewsFoundationOS.framework/PreviewsFoundationOS
 */

@interface PreviewsFoundationOS.AgentSymbolTableManager : _TtCs12_SwiftObject {
    void invalidatedLinkerTimeout;
    void state;
}

@end
