/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FSKit.framework/FSKit
 */

@interface FSItemSetAttributesRequest : FSItemAttributes {
    long long  _consumedAttributes;
    unsigned long long  attrsConsumed;
}

@property (nonatomic) long long consumedAttributes;

+ (bool)supportsSecureCoding;

- (Class)classForCoder;
- (long long)consumedAttributes;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)setConsumedAttributes:(long long)arg1;
- (bool)wasAttributeConsumed:(long long)arg1;

@end
