/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MedicalIDUI.framework/MedicalIDUI
 */

@interface _TtC11MedicalIDUIP33_D4BBDB7E727832FA87D2B563116D5DE45Model : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _$observationRegistrar;
    void _defaultText;
    void _fieldFocused;
    void _text;
}

@end
