/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MedicalIDUI.framework/MedicalIDUI
 */

@interface MIUIMedicalIDNavigationBarView : UIView {
    void containerView;
    void dateUpdatedLabel;
    void imageView;
    void showDateUpdated;
    void textLabel;
    void titleFont;
    void viewModel;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithHealthStore:(id)arg1 medicalIDData:(id)arg2 showDateUpdated:(bool)arg3 locale:(id)arg4;

@end
