/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaControls.framework/MediaControls
 */

@interface MediaControls.MediaModulePresenter : _TtCs12_SwiftObject {
    void controller;
    void presentable;
}

@end
