/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.Daemon : _TtCs12_SwiftObject {
    void activityReplicationService;
    void activityService;
    void appAuthorizationMonitor;
    void clientScreenshotManager;
    void controlCenterServer;
    void controlHostService;
    void controlsCacheKeyProvider;
    void controlsPowerlogUpdateService;
    void controlsServer;
    void dataProtectionMonitor;
    void descriptorService;
    void deviceService;
    void discoveryService;
    void duetWidgetConfigurationManager;
    void environmentProvidingFactory;
    void extensionManager;
    void finishLaunchingToken;
    void focusConfigurationMonitor;
    void iconStore;
    void interactionService;
    void keybagStateProvider;
    void layerSnapshotter;
    void liveControlsService;
    void localeChangeCoordinator;
    void locationService;
    void placeholderService;
    void powerlogControlsViewService;
    void powerlogSuggestionService;
    void preferences;
    void previewControlsService;
    void pushService;
    void reaperService;
    void remoteWidgetExtensionService;
    void remoteWidgetRapportNotifier;
    void rendererServer;
    void replicationService;
    void replicator;
    void replicatorMigrationService;
    void servicesBootstrapExtension;
    void servicesServer;
    void sigtermSource;
    void snapshotService;
    void stateCaptureService;
    void storefrontChangeCoordinator;
    void subscriptions;
    void taskService;
    void timelineService;
    void toolServicesServer;
    void userManager;
    void wakeManager;
    void widgetCacheKeyProvider;
    void widgetCenterServer;
    void widgetHostService;
    void widgetRelevanceService;
    void widgetsPowerlogUpdateService;
}

@end
