/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.WakingWorkScheduler : _TtCs12_SwiftObject {
    void _lock_backgroundWakeTask;
    void didFire;
    void invalidationQueue;
    void lock;
}

@end
