/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitRuntime.framework/SiriKitRuntime
 */

@interface SiriKitRuntime.AnnounceContext : _TtCs12_SwiftObject {
    void activeTasks;
    void executedTasks;
}

@end
