/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitRuntime.framework/SiriKitRuntime
 */

@interface SKRConversationFlexibleExecutionSupport : NSObject <NSSecureCoding> {
    void rawValue;
}

+ (void)setSupportsSecureCoding:(bool)arg1;
+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end
