/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
 */

@interface AVMetricHLSMediaSegmentRequestEvent : AVMetricEvent {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _byteRange;
    NSURL * _indexFileURL;
    bool  _isMapSegment;
    AVMetricMediaResourceRequestEvent * _mediaResourceRequestEvent;
    NSString * _mediaType;
    NSURL * _url;
}

@property (readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } byteRange;
@property (readonly) NSURL *indexFileURL;
@property (readonly) bool isMapSegment;
@property (readonly) AVMetricMediaResourceRequestEvent *mediaResourceRequestEvent;
@property (readonly) NSString *mediaType;
@property (readonly) NSURL *url;

+ (bool)supportsSecureCoding;

- (struct _NSRange { unsigned long long x1; unsigned long long x2; })byteRange;
- (void)dealloc;
- (id)debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)indexFileURL;
- (id)initWithCoder:(id)arg1;
- (id)initWithDate:(id)arg1 mediaTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 sessionID:(id)arg3 indexFileURL:(id)arg4 byteRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg5 isMapSegment:(bool)arg6 mediaType:(id)arg7 mediaResourceRequestEvent:(id)arg8;
- (bool)isMapSegment;
- (id)mediaResourceRequestEvent;
- (id)mediaType;
- (id)url;

@end
