/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFLinkSafariFindReadingListItemsAction : WFLinkContentItemFilterAction

- (id)localizedCategoryWithContext:(id)arg1;
- (id)localizedNameWithContext:(id)arg1;

@end
