/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFRegexFieldParameter : WFTextInputParameter

@property (nonatomic, readonly) NSString *localizedIncompleteHintString;

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

- (id)hintForState:(id)arg1;
- (id)initWithDefinition:(id)arg1;
- (id)localizedIncompleteHintString;
- (Class)singleStateClass;

// Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor

+ (Class)moduleSummaryEditorClass;

@end
