/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIFoundation.framework/PhotosUIFoundation
 */

@interface PhotosUIFoundation.PhotosScreenEdgeDismissalSlideTransition : NSObject <UIViewControllerAnimatedTransitioning> {
    void foregroundViewLateralInset;
}

- (void)animateTransition:(id)arg1;
- (id)init;
- (double)transitionDuration:(id)arg1;

@end
