/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iCloudSettings.framework/iCloudSettings
 */

@interface iCloudSettings.ManageStorageThermometerSection : NSObject {
    void bundleId;
    void displayLabel;
    void storagePercentage;
}

@property (nonatomic, readonly) NSString *bundleId;
@property (nonatomic, readonly) NSString *displayLabel;
@property (nonatomic, readonly) double storagePercentage;

- (void).cxx_destruct;
- (id)bundleId;
- (id)displayLabel;
- (id)init;
- (id)init:(id)arg1;
- (double)storagePercentage;

@end
