/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iCloudSettings.framework/iCloudSettings
 */

@interface ICSHMEPresenter : NSObject <AAUIGrandSlamRemoteUIPresenterDelegate, AIDAAccountManagerDelegate> {
    AIDAAccountManager * _accountManager;
    <ICSCloudHomeViewDelegate> * _delegate;
    AAUIGrandSlamRemoteUIPresenter * _privateEmailPresenter;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (nonatomic) <ICSCloudHomeViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)delegate;
- (id)initWithAccountManager:(id)arg1;
- (void)remoteUIRequestComplete:(id)arg1 error:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)showHMEWithPresenter:(id)arg1;

@end
