/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iCloudSettings.framework/iCloudSettings
 */

@interface ICSHomeDataModel : NSObject {
    void _rawJsonObject;
    void backupViewInfo;
    void headerCard;
    void icloudAppsCard;
    void icloudPlusCard;
    void manageStorageViewInfo;
    void manageSubscriptionsAction;
    void preLaunchAction;
    void settingsFooter;
    void upsellCard;
}

@property (nonatomic, readonly) _TtC14iCloudSettings14BackupViewInfo *backupViewInfo;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) _TtC14iCloudSettings10HeaderCard *headerCard;
@property (nonatomic, readonly) _TtC14iCloudSettings14iCloudAppsCard *icloudAppsCard;
@property (nonatomic, readonly) _TtC14iCloudSettings14iCloudPlusCard *icloudPlusCard;
@property (nonatomic, readonly) _TtC14iCloudSettings21ManageStorageViewInfo *manageStorageViewInfo;
@property (nonatomic, readonly) _TtC14iCloudSettings6Action *manageSubscriptionsAction;
@property (nonatomic, readonly) _TtC14iCloudSettings6Action *preLaunchAction;
@property (nonatomic, readonly) _TtC14iCloudSettings14SettingsFooter *settingsFooter;
@property (nonatomic, readonly) _TtC14iCloudSettings10UpsellCard *upsellCard;

- (void).cxx_destruct;
- (id)backupViewInfo;
- (id)description;
- (id)headerCard;
- (id)icloudAppsCard;
- (id)icloudPlusCard;
- (id)init;
- (id)init:(id)arg1;
- (id)manageStorageViewInfo;
- (id)manageSubscriptionsAction;
- (id)preLaunchAction;
- (id)settingsFooter;
- (id)upsellCard;

@end
