/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafariUI.framework/MobileSafariUI
 */

@interface SafariClearBrowsingDataController : NSObject <SFClearHistoryViewControllerDelegate> {
    NSArray * _availableIntervals;
    <TabGroupProvider> * _tabGroupProvider;
}

@property (readonly) NSArray *availableIntervals;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic) <TabGroupProvider> *tabGroupProvider;

- (void).cxx_destruct;
- (long long)_analyticsClearBrowsingIntervalForDate:(id)arg1;
- (void)_clearAllScribbleEdits;
- (void)_clearBrowsingDataAddedAfterDate:(id)arg1 profileIdentifiers:(id)arg2 closeAllTabs:(bool)arg3;
- (id)availableIntervals;
- (void)clearDataAddedAfterDate:(id)arg1 beforeDate:(id)arg2 profileIdentifier:(id)arg3 clearAllProfiles:(bool)arg4 closeTabs:(bool)arg5;
- (void)clearHistoryViewController:(id)arg1 clearHistoryVisitsAddedAfterDate:(id)arg2 beforeDate:(id)arg3 profileIdentifier:(id)arg4 clearAllProfiles:(bool)arg5 closeAllTabs:(bool)arg6;
- (unsigned long long)clearHistoryViewController:(id)arg1 numberOfTabsToBeClosedForProfilesWithIdentifiers:(id)arg2;
- (id)init;
- (void)setTabGroupProvider:(id)arg1;
- (void)showClearHistoryMenuFromViewController:(id)arg1;
- (void)showClearHistoryMenuFromViewController:(id)arg1 profileIdentifier:(id)arg2;
- (id)tabGroupProvider;

@end
