/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CorePrescriptionLite.framework/CorePrescriptionLite
 */

@interface CRXFCalibrationData : NSObject {
    NSData * _accPayload;
    NSString * _leftCalibrationData;
    NSString * _rightCalibrationData;
}

@property (nonatomic, readonly) NSData *accPayload;
@property (nonatomic, readonly) NSString *leftCalibrationData;
@property (nonatomic, readonly) NSString *rightCalibrationData;

- (void).cxx_destruct;
- (id)accPayload;
- (id)initWithACCPayload:(id)arg1 leftCalibrationData:(id)arg2 rightCalibrationData:(id)arg3;
- (id)leftCalibrationData;
- (id)rightCalibrationData;

@end
