/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligentTrackingCore.framework/IntelligentTrackingCore
 */

@interface IntelligentTrackingCore.DKRepeatingTimer : NSObject {
    void date;
    void state;
    void stateLock;
    void timer;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end
