/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface ChatKit.SendMenuOrderManager : _TtCs12_SwiftObject {
    void persistenceManager;
}

@end
