/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FPFS.framework/FPFS
 */

@interface libfssync.FPShouldPauseResult : NSObject {
    void semaphore;
    void shouldPause;
}

@property (nonatomic, readonly) OS_dispatch_semaphore *semaphore;
@property (nonatomic, readonly) bool shouldPause;

- (void).cxx_destruct;
- (id)init;
- (id)initWithShouldPause:(bool)arg1 semaphore:(id)arg2;
- (id)semaphore;
- (bool)shouldPause;

@end
