/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FPFS.framework/FPFS
 */

@interface libfssync.FPFSGlobalProgress : _TtCs12_SwiftObject {
    void _pendingBackgroundDownloadsCounter;
    void activeChildProgress;
    void activeCounters;
    void complementaryProgress;
    void complementaryProgressSubscriber;
    void dispatchQueue;
    void dispatchTimer;
    void doneCounters;
    void downloadSchedulerRunning;
    void fileSizeCache;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  fileURL;
    void jobsProvider;
    void kind;
    void log;
    void needsNotifyGlobalProgress;
    void partialUnitCount;
    void pausableJobsCounter;
    void proxies;
    void publishedProgress;
    void useComplementaryProgress;
}

@end
