/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPCoreAnalyticsManager : NSObject

+ (id)aggdLogIdentifierFromItem:(id)arg1 type:(int)arg2 baseType:(id*)arg3;
+ (void)computeEngagementMatrixForEngagedItem:(id)arg1 topAnalyticsItemsPerSection:(id)arg2;
+ (void)logEngagementWithBundleIdentifier:(id)arg1 forEvent:(unsigned long long)arg2;
+ (void)logEngagementWithItem:(id)arg1 atPosition:(unsigned long long)arg2 forEvent:(unsigned long long)arg3;

@end
