/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Search.framework/Search
 */

@interface SPFeedbackListenerWrapper : NSObject {
    <SFFeedbackListener> * _feedbackListener;
    unsigned long long  _supportedTypes;
}

@property (nonatomic, retain) <SFFeedbackListener> *feedbackListener;
@property (nonatomic) unsigned long long supportedTypes;

+ (void)initialize;
+ (id)wrapperWithFeedbackListener:(id)arg1;

- (void).cxx_destruct;
- (id)feedbackListener;
- (id)initWithFeedbackListener:(id)arg1;
- (void)setFeedbackListener:(id)arg1;
- (void)setSupportedTypes:(unsigned long long)arg1;
- (unsigned long long)supportedTypes;
- (bool)supportsFeedbackType:(long long)arg1;

@end
