/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@interface _TtCO7Sharing20SFAirDropInvocations21FetchEndpointMetadata : SFXPCInvocation

+ (bool)supportsSecureCoding;

- (id)init;
- (id)initWithCoder:(id)arg1;

@end
