/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
 */

@interface SFAirDropUserDefaults_objc : NSObject

+ (bool)askToAirdropEnabled;
+ (bool)cellularUsageEnabled;
+ (bool)moveToAppEnabled;
+ (bool)nearFieldSharingEnabled;
+ (bool)privateContactDiscoveryEnabled;
+ (void)setCellularUsageEnabled:(bool)arg1;
+ (void)setNearFieldSharingEnabled:(bool)arg1;
+ (bool)systemLevelProgressEnabled;

@end
