/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CameraEditKit.framework/CameraEditKit
 */

@interface CEKC2GroupCompletion : NSObject

+ (void)perform:(id /* block */)arg1 finalCompletion:(id /* block */)arg2;
+ (void)perform:(id /* block */)arg1 finalCompletion:(id /* block */)arg2 options:(unsigned long long)arg3 delegate:(id)arg4;

@end
