/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface SWTransparencySFAnalytics : SFAnalytics

+ (id)databasePath;
+ (id)logger;

@end
