/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TodayFeedMastheadModelProvider : _TtCs12_SwiftObject {
    void bundleSubscriptionManager;
    void configurationManager;
    void featureAvailability;
    void mastheadPaywallConfigurationProvider;
    void mastheadWelcomeMessageProvider;
    void offerManager;
    void offlineManager;
}

@end
