/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AutoFillUI.framework/AutoFillUI
 */

@interface AFCreditCard : NSObject {
    NSString * _expiration;
    NSString * _name;
    NSString * _nickname;
    NSString * _number;
    NSString * _securityCode;
    NSString * _suffix;
    NSString * _type;
}

@property (nonatomic, copy) NSString *expiration;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *nickname;
@property (nonatomic, copy) NSString *number;
@property (nonatomic, copy) NSString *securityCode;
@property (nonatomic, copy) NSString *suffix;
@property (nonatomic, copy) NSString *type;

- (void).cxx_destruct;
- (id)description;
- (id)expiration;
- (id)initWithName:(id)arg1 number:(id)arg2 expiration:(id)arg3 securityCode:(id)arg4 type:(id)arg5 nickname:(id)arg6 suffix:(id)arg7;
- (id)name;
- (id)nickname;
- (id)number;
- (id)securityCode;
- (void)setExpiration:(id)arg1;
- (void)setName:(id)arg1;
- (void)setNickname:(id)arg1;
- (void)setNumber:(id)arg1;
- (void)setSecurityCode:(id)arg1;
- (void)setSuffix:(id)arg1;
- (void)setType:(id)arg1;
- (id)suffix;
- (id)type;

@end
