/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CarPlayUIServices.framework/CarPlayUIServices
 */

@interface CRSUIClusterThemeLayoutPreview : NSObject <BSXPCSecureCoding> {
    CRSUIClusterThemeCAPackageAsset * _asset;
    NSDictionary * _darkModeStateForPaletteID;
    NSDictionary * _lightModeStateForPaletteID;
    bool  _supportsDynamicAppearance;
}

@property (nonatomic, readonly) CRSUIClusterThemeCAPackageAsset *asset;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool supportsDynamicAppearance;

+ (bool)supportsBSXPCSecureCoding;

- (void).cxx_destruct;
- (id)asset;
- (void)encodeWithBSXPCCoder:(id)arg1;
- (id)initWithAsset:(id)arg1 lightModeStateForPaletteID:(id)arg2 darkModeStateForPaletteID:(id)arg3;
- (id)initWithAsset:(id)arg1 lightModeStateForPaletteID:(id)arg2 darkModeStateForPaletteID:(id)arg3 supportsDynamicAppearance:(bool)arg4;
- (id)initWithAsset:(id)arg1 stateForPaletteID:(id)arg2;
- (id)initWithBSXPCCoder:(id)arg1;
- (id)stateForPaletteIDWithInterfaceStyle:(long long)arg1;
- (bool)supportsDynamicAppearance;

@end
