/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MediaPlaybackCore.PlayerController : _TtCs12_SwiftObject <MFPlayerConfigurable, MFResettable, MFStateDumpable> {
    void applicationMusicPlayerTransitionOptions;
    void audioSessionController;
    void behavior;
    void coordinatedPlaybackSuspension;
    void currentItemTransition;
    void delegate;
    void didBecomeActiveSubscription;
    void fsm;
    void leaseController;
    void mode;
    void nextItemTracksChangeSubscription;
    void playbackCoordinatorObservation;
    void playbackStartSubscription;
    void player;
    void playerID;
    void playerObserver;
    void playerSubscription;
    void previousItemID;
    void queue;
    void reporter;
    void systemObserver;
    void systemSubscription;
    void userActionTimeout;
    void userEventsMonitor;
    void videoPlayerBehavior;
    void videoPlayerViewController;
    void willResignActiveSubscription;
}

@property (nonatomic) float relativeVolume;
@property (nonatomic, readonly) NSDictionary *stateDictionary;

- (float)relativeVolume;
- (void)resetWithReason:(id)arg1;
- (void)setApplicationMusicPlayerTransitionType:(long long)arg1 duration:(double)arg2;
- (void)setRelativeVolume:(float)arg1;
- (void)setSpatializationFormat:(long long)arg1;
- (id)stateDictionary;

@end
