/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@interface NFReaderSessionPollConfig : NSObject {
    NSData * _ecp;
    bool  _fieldDetect;
    bool  _lpcd;
    unsigned int  _pollDuration;
    bool  _skipMifareClassify;
    unsigned int  _technology;
}

@property (nonatomic, retain) NSData *ecp;
@property (nonatomic) bool fieldDetect;
@property (nonatomic) bool lpcd;
@property (nonatomic) unsigned int pollDuration;
@property (nonatomic) bool skipMifareClassify;
@property (nonatomic) unsigned int technology;

+ (id)pollConfigWithTechnology:(unsigned int)arg1;

- (void).cxx_destruct;
- (id)asDictionary;
- (id)ecp;
- (bool)fieldDetect;
- (id)init;
- (bool)lpcd;
- (unsigned int)pollDuration;
- (void)setEcp:(id)arg1;
- (void)setFieldDetect:(bool)arg1;
- (void)setLpcd:(bool)arg1;
- (void)setPollDuration:(unsigned int)arg1;
- (void)setSkipMifareClassify:(bool)arg1;
- (void)setTechnology:(unsigned int)arg1;
- (bool)skipMifareClassify;
- (unsigned int)technology;

@end
