/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GenerativeFunctionsInstrumentation.framework/GenerativeFunctionsInstrumentation
 */

@interface GenerativeFunctionsInstrumentation.PrewarmEventProcessor : _TtCs12_SwiftObject {
    void coreAnalyticsReporter;
    void eventLogger;
    void maxEventBuffereSize;
    void prewarmEventIdentifiers;
    void prewarmEvents;
}

@end
