/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GenerativeFunctionsInstrumentation.framework/GenerativeFunctionsInstrumentation
 */

@interface GenerativeFunctionsInstrumentation.InferencePerformanceProcessor : _TtCs12_SwiftObject {
    void buffer;
    void coreAnalyticsReporter;
    void eventLogger;
    void stringCompressor;
}

@end
