/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CipherML.framework/CipherML
 */

@interface _TtCC8CipherML11ConfigCache12StoredConfig : _TtCs12_SwiftObject {
    void _$backingData;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _$observationRegistrar;
    void _serializedConfig;
    void _usecase;
}

@end
