/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BridgePreferences.framework/BridgePreferences
 */

@interface BPSLazyLoadingIconProperties : NSObject {
    NSString * _bundlePath;
    bool  _flipsForRTL;
    NSString * _identifier;
    NSString * _lazyIconID;
    NSString * _squareIconName;
}

@property (nonatomic, retain) NSString *bundlePath;
@property (nonatomic) bool flipsForRTL;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSString *lazyIconID;
@property (nonatomic, retain) NSString *squareIconName;

- (void).cxx_destruct;
- (id)bundlePath;
- (bool)flipsForRTL;
- (id)identifier;
- (id)lazyIconID;
- (void)setBundlePath:(id)arg1;
- (void)setFlipsForRTL:(bool)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLazyIconID:(id)arg1;
- (void)setSquareIconName:(id)arg1;
- (id)squareIconName;

@end
