/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthAppHealthDaemon.framework/HealthAppHealthDaemon
 */

@interface HealthAppHealthDaemon.PinnedContentDaemonStore : _TtCs12_SwiftObject {
    void domain;
    void kvd;
    void notificationPoster;
    void profile;
}

@end
