/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSystemCommandsIntents.framework/SiriSystemCommandsIntents
 */

@interface SiriSystemCommandsIntents.SCSystemCommandsYesNoStrategy : _TtCs12_SwiftObject {
    void deviceState;
    void provider;
    void responseType;
}

@end
