/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIMaintenancePersistedTask : TRIPBMessage

@property (nonatomic) bool hasRetryCount;
@property (nonatomic) int retryCount;

+ (id)descriptor;

@end
