/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SetupAssistantUI.framework/SetupAssistantUI
 */

@interface BFFViewControllerSpinnerManager : NSObject

+ (void)configureWithNavigationController:(id)arg1;
+ (void)startAnimatingSpinnerFor:(id)arg1 identifier:(id)arg2;
+ (void)stopAnimatingSpinnerFor:(id)arg1;

@end
