/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NeutrinoCore.framework/NeutrinoCore
 */

@interface _NUFlexRangeChannelProperties : NSObject <NUFlexRangeChannelProperties> {
    float  _alternateOffset;
    float  _baseOffset;
    float  _gamma;
    float  _max;
    float  _min;
}

@property (nonatomic) float alternateOffset;
@property (nonatomic) float baseOffset;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic) float gamma;
@property (readonly) unsigned long long hash;
@property (nonatomic) float max;
@property (nonatomic) float min;
@property (readonly) Class superclass;

- (float)alternateOffset;
- (float)baseOffset;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (float)gamma;
- (float)max;
- (float)min;
- (void)setAlternateOffset:(float)arg1;
- (void)setBaseOffset:(float)arg1;
- (void)setGamma:(float)arg1;
- (void)setMax:(float)arg1;
- (void)setMin:(float)arg1;

@end
