/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AeroML.framework/AeroML
 */

@interface AMLFeaturesDecoder : NSObject

+ (id)dataMetricsForFeatureProvider:(id)arg1;
+ (id)dictionariesFromBatchProvider:(id)arg1;
+ (id)logger;
+ (id)modelArrayForArrayProvider:(id)arg1;
+ (id)modelContentForBatchProvider:(id)arg1;
+ (id)modelDataFrom:(id)arg1;

@end
