/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AeroML.framework/AeroML
 */

@interface AMLSpotlightStorage : NSObject

+ (id)clientDonationForPhotoId:(id)arg1 aroundTime:(double)arg2;
+ (id)clientDonationsForSession:(id)arg1;
+ (id)featuresConfigurationForConfigurationId:(id)arg1;
+ (id)featuresForSpotlightId:(id)arg1;
+ (id)metadataForPhotoId:(id)arg1 aroundTime:(double)arg2;
+ (id)metadataForSession:(id)arg1;

- (void).cxx_destruct;
- (id)init;

@end
