/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NeuralNetworks.framework/NeuralNetworks
 */

@interface NeuralNetworks.SliceOperation : NeuralNetworks.BaseSliceOperation {
    void backward;
}

@end
