/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPIndeterminateProgressSpinnerStyle : NSObject {
    UIColor * _indicatorColor;
    LPTextViewStyle * _label;
    LPPadding * _padding;
    LPPointUnit * _spacing;
    bool  _useLargeIndicatorStyle;
    LPPointUnit * _verticalOffset;
}

@property (nonatomic, retain) UIColor *indicatorColor;
@property (nonatomic, retain) LPTextViewStyle *label;
@property (nonatomic, retain) LPPadding *padding;
@property (nonatomic, retain) LPPointUnit *spacing;
@property (nonatomic) bool useLargeIndicatorStyle;
@property (nonatomic, retain) LPPointUnit *verticalOffset;

- (void).cxx_destruct;
- (id)indicatorColor;
- (id)initWithPlatform:(long long)arg1 sizeClass:(unsigned long long)arg2 fontScalingFactor:(double)arg3;
- (id)label;
- (id)padding;
- (void)setIndicatorColor:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setPadding:(id)arg1;
- (void)setSpacing:(id)arg1;
- (void)setUseLargeIndicatorStyle:(bool)arg1;
- (void)setVerticalOffset:(id)arg1;
- (id)spacing;
- (bool)useLargeIndicatorStyle;
- (id)verticalOffset;

@end
