/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PosterUIFoundation.framework/PosterUIFoundation
 */

@interface _PUIStyleTwoToneCoordinatorImpl : PUIStyleUICoordinatorImpl {
    UIView * _color1View;
    UIView * _color2View;
    UIView * _itemView;
}

- (void).cxx_destruct;
- (id)effectiveColor1;
- (id)effectiveColor2;
- (id)itemView;
- (double)itemViewLuminance;

@end
