/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LocalAuthenticationCore.framework/LocalAuthenticationCore
 */

@interface LACExtractablePasswordPersistenceOptions : NSObject {
    <LACContextProviding> * _contextProvider;
}

@property (nonatomic, readonly) <LACContextProviding> *contextProvider;

- (void).cxx_destruct;
- (id)contextProvider;
- (id)initWithContextProvider:(id)arg1;

@end
