/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Visage.framework/Visage
 */

@interface VGHRTFEarCaptureProcessedData : NSObject {
    VGHRTFEarCaptureDetectionData * _detectionData;
    unsigned long long  _error;
    IOSurface * _rectifiedColorBuffer;
}

@property (nonatomic, retain) VGHRTFEarCaptureDetectionData *detectionData;
@property (nonatomic) unsigned long long error;
@property (nonatomic, retain) IOSurface *rectifiedColorBuffer;

- (void).cxx_destruct;
- (id)detectionData;
- (unsigned long long)error;
- (id)initEmpty;
- (id)rectifiedColorBuffer;
- (void)setDetectionData:(id)arg1;
- (void)setError:(unsigned long long)arg1;
- (void)setRectifiedColorBuffer:(id)arg1;

@end
