/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NearFieldPrivateServices.framework/NearFieldPrivateServices
 */

@interface NFStorageService : NFPrivateService

- (bool)canRun;
- (void)deleteAllAppletEntities;
- (void)deleteAllESEExpressEntities;
- (id)fetchAppletEntitiesWithError:(id*)arg1;
- (id)fetchESEExpressEntitiesWithError:(id*)arg1;
- (id)serviceName;
- (id)updateAppletEntitiesWithConfig:(id)arg1;
- (void)updateESEExpressEntitiesWithConfig:(id)arg1;

@end
