/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFScheduleUtilities : NSObject

+ (id)localizedDetailedStringForRule:(id)arg1;
+ (id)localizedMainStringForRule:(id)arg1;
+ (id)localizedStringForRule:(id)arg1;
+ (id)localizedStringForSchedule:(id)arg1;
+ (id)localizedStringFromScheduleType:(unsigned long long)arg1;
+ (id /* block */)sortComparatorForScheduleRules;
+ (id)sortedScheduleRules:(id)arg1;

@end
