/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherCore.framework/WeatherCore
 */

@interface WeatherCore.LocationsOfInterestDataSource : _TtCs12_SwiftObject {
    void coreRoutineDataManager;
    void geocodeManager;
    void locationMatchHelper;
}

@end
