/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMAccessoryInfoProtoWifiNetworkInfoEvent : PBCodable <NSCopying> {
    struct { 
        unsigned int networkRSSI : 1; 
        unsigned int requiresPassword : 1; 
    }  _has;
    NSString * _macAddress;
    NSString * _networkBSSID;
    NSString * _networkGatewayIPAddress;
    NSString * _networkGatewayMacAddress;
    int  _networkRSSI;
    NSString * _networkSSID;
    bool  _requiresPassword;
}

@property (nonatomic, readonly) bool hasMacAddress;
@property (nonatomic, readonly) bool hasNetworkBSSID;
@property (nonatomic, readonly) bool hasNetworkGatewayIPAddress;
@property (nonatomic, readonly) bool hasNetworkGatewayMacAddress;
@property (nonatomic) bool hasNetworkRSSI;
@property (nonatomic, readonly) bool hasNetworkSSID;
@property (nonatomic) bool hasRequiresPassword;
@property (nonatomic, retain) NSString *macAddress;
@property (nonatomic, retain) NSString *networkBSSID;
@property (nonatomic, retain) NSString *networkGatewayIPAddress;
@property (nonatomic, retain) NSString *networkGatewayMacAddress;
@property (nonatomic) int networkRSSI;
@property (nonatomic, retain) NSString *networkSSID;
@property (nonatomic) bool requiresPassword;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasMacAddress;
- (bool)hasNetworkBSSID;
- (bool)hasNetworkGatewayIPAddress;
- (bool)hasNetworkGatewayMacAddress;
- (bool)hasNetworkRSSI;
- (bool)hasNetworkSSID;
- (bool)hasRequiresPassword;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)macAddress;
- (void)mergeFrom:(id)arg1;
- (id)networkBSSID;
- (id)networkGatewayIPAddress;
- (id)networkGatewayMacAddress;
- (int)networkRSSI;
- (id)networkSSID;
- (bool)readFrom:(id)arg1;
- (bool)requiresPassword;
- (void)setHasNetworkRSSI:(bool)arg1;
- (void)setHasRequiresPassword:(bool)arg1;
- (void)setMacAddress:(id)arg1;
- (void)setNetworkBSSID:(id)arg1;
- (void)setNetworkGatewayIPAddress:(id)arg1;
- (void)setNetworkGatewayMacAddress:(id)arg1;
- (void)setNetworkRSSI:(int)arg1;
- (void)setNetworkSSID:(id)arg1;
- (void)setRequiresPassword:(bool)arg1;
- (void)writeTo:(id)arg1;

@end
