/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMMatterAttributeEvent : HMEvent <NSCopying, NSMutableCopying, NSSecureCoding> {
    HMAccessory * _accessory;
    NSNumber * _attributeID;
    NSNumber * _clusterID;
    NSNumber * _endpointID;
    <NSCopying> * _triggerValue;
}

@property (nonatomic, readonly) HMAccessory *accessory;
@property (nonatomic, readonly) NSNumber *attributeID;
@property (nonatomic, readonly) NSNumber *clusterID;
@property (nonatomic, readonly) NSNumber *endpointID;
@property (nonatomic, readonly, copy) <NSCopying> *triggerValue;

+ (id)createWithDictionary:(id)arg1 home:(id)arg2;
+ (id)new;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_serializeForAdd;
- (void)_updateFromDictionary:(id)arg1;
- (id)accessory;
- (id)attributeID;
- (id)clusterID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)endpointID;
- (id)initWithAttributeID:(id)arg1 clusterID:(id)arg2 endpointID:(id)arg3 accessory:(id)arg4 triggerValue:(id)arg5;
- (id)initWithCoder:(id)arg1;
- (id)initWithDict:(id)arg1 attributeID:(id)arg2 clusterID:(id)arg3 endpointID:(id)arg4 accessory:(id)arg5 triggerValue:(id)arg6;
- (bool)mergeFromNewObject:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (void)setTriggerValue:(id)arg1;
- (id)triggerValue;

@end
