/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SoundAnalysis.framework/SoundAnalysis
 */

@interface SoundAnalysis.SessionActivation : _TtCs12_SwiftObject {
    void session;
}

@end
