/* Generated by RuntimeBrowser.
 */

@protocol _SFPBWatchListButtonItem <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setToggleButtonConfiguration:(_SFPBToggleButtonConfiguration *)arg1;
- (void)setUniqueId:(unsigned long long)arg1;
- (void)setWatchListItem:(_SFPBWatchListItem *)arg1;
- (_SFPBToggleButtonConfiguration *)toggleButtonConfiguration;
- (unsigned long long)uniqueId;
- (_SFPBWatchListItem *)watchListItem;

@end
