/* Generated by RuntimeBrowser.
 */

@protocol AppleCV3DSchemaSubmapCreatedEvent <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (AppleCommonSchemaMetadata *)metadata;
- (AppleCV3DSchemaSubmapCreated *)payload;
- (void)setMetadata:(AppleCommonSchemaMetadata *)arg1;
- (void)setPayload:(AppleCV3DSchemaSubmapCreated *)arg1;

@end
