/* Generated by RuntimeBrowser.
 */

@protocol ASDTIOServiceManagerDelegate <NSObject>

@required

- (void)ioServiceAvailable:(ASDTIOService *)arg1 withManager:(ASDTIOServiceManager *)arg2;

@optional

- (void)ioServiceWillTerminate:(ASDTIOService *)arg1 withManager:(ASDTIOServiceManager *)arg2;

@end
