/* Generated by RuntimeBrowser.
 */

@protocol AVMediaSelectionMenuDelegate <NSObject>

@required

- (void)mediaSelectionMenuController:(AVMediaSelectionMenuController *)arg1 didSelectOption:(AVMediaSelectionOption *)arg2;

@optional

- (void)mediaSelectionMenuController:(AVMediaSelectionMenuController *)arg1 didSelectEnhanceDialogueOption:(long long)arg2;
- (NSString *)mediaSelectionMenuController:(AVMediaSelectionMenuController *)arg1 displayNameForMediaSelectionOption:(AVMediaSelectionOption *)arg2;
- (bool)shouldApplyLegibleMediaSelectionCriteriaAutomaticallyForMediaSelectionMenuController:(AVMediaSelectionMenuController *)arg1;

@end
