/* Generated by RuntimeBrowser.
 */

@protocol AVMobileChromelessDisplayModeControlsViewDelegate <NSObject>

@optional

- (void)displayModeControlsView:(AVMobileChromelessDisplayModeControlsView *)arg1 layoutWithHiddenIdentifiers:(NSArray *)arg2;
- (void)displayModeControlsViewDidDismissContextMenu:(AVMobileChromelessDisplayModeControlsView *)arg1;
- (void)displayModeControlsViewFullscreenButtonWasPressed:(AVMobileChromelessDisplayModeControlsView *)arg1;
- (void)displayModeControlsViewPictureInPictureButtonWasPressed:(AVMobileChromelessDisplayModeControlsView *)arg1;
- (void)displayModeControlsViewWillPresentContextMenu:(AVMobileChromelessDisplayModeControlsView *)arg1;

@end
