/* Generated by RuntimeBrowser.
 */

@protocol BCSFilterShardItemProtocol <BCSShardItemProtocol>

@required

- (<BCSFilterShardMatchResult> *)containsItemMatching:(id <BCSItemIdentifying>)arg1;

@end
