/* Generated by RuntimeBrowser.
 */

@protocol CollectionViewTabIndexProviding <NSObject>

@required

- (long long)collectionViewIndexOfTab:(id <CollectionViewTab>)arg1;
- (<CollectionViewTab> *)tabAtCollectionViewIndex:(long long)arg1;

@end
