/* Generated by RuntimeBrowser.
 */

@protocol DKUserAlertResponder <NSObject>

@optional

- (void)displayAlertWithHeader:(void *)arg1 message:(void *)arg2 buttonStrings:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 10: NSString *, NSString *, NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSNumber *, NSError *, void*
- (void)displayInstructions:(void *)arg1 style:(void *)arg2 imageLocators:(void *)arg3 title:(void *)arg4 subtitle:(void *)arg5 iconLocator:(void *)arg6 options:(void *)arg7 completion:(void *)arg8; // needs 8 arg types, found 14: NSArray *, int, NSArray *, NSString *, NSString *, NSString *, NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, NSError *, void*

@end
