/* Generated by RuntimeBrowser.
 */

@protocol DOCUIPTraitEnvironment

@required

- (bool)enclosedInUIPDocumentLanding;
- (long long)enclosingDocumentLandingMode;
- (long long)enclosingTabSwitcherStyle;
- (double)enclosingUIPHorizontalInset;

@end
