/* Generated by RuntimeBrowser.
 */

@protocol FedStatsCategoricalTypeFilteringProtocol <NSObject>

@required

+ (id)instanceWithParameters:(NSDictionary *)arg1 error:(id*)arg2;
+ (NSDictionary *)mutateParameters:(NSDictionary *)arg1 usingFieldValues:(NSDictionary *)arg2 assetURLs:(NSDictionary *)arg3 requiredFields:(id*)arg4 assetNames:(id*)arg5 error:(id*)arg6;

- (id)filter:(id)arg1;

@end
