/* Generated by RuntimeBrowser.
 */

@protocol HMHearingTestAudiogramImportFlowProviding

@required

- (void)didTapImportAudiogramLinkIn:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 6: HMHearingTestMainViewController *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*

@end
