/* Generated by RuntimeBrowser.
 */

@protocol ICAccountCryptoStrategy <ICCloudSyncingObjectCryptoStrategy>

@required

- (void)removePassphrase;
- (bool)setPassphrase:(NSString *)arg1 hint:(NSString *)arg2;

@end
