/* Generated by RuntimeBrowser.
 */

@protocol ICCloudContextDelegate <NSObject>

@required

- (NSArray *)accountIDsForCloudContext:(ICCloudContext *)arg1 managedObjectContext:(NSManagedObjectContext *)arg2;
- (NSManagedObjectContext *)backgroundContextForCloudContext:(ICCloudContext *)arg1;
- (void)cloudContext:(ICCloudContext *)arg1 didExceedQuotaForRecordID:(CKRecordID *)arg2 accountID:(NSString *)arg3;
- (void)cloudContext:(ICCloudContext *)arg1 didFetchShare:(CKShare *)arg2 accountID:(NSString *)arg3;
- (void)cloudContext:(ICCloudContext *)arg1 didFetchUserRecord:(CKRecord *)arg2 accountID:(NSString *)arg3;
- (void)cloudContext:(ICCloudContext *)arg1 didPushRecordID:(CKRecordID *)arg2 accountID:(NSString *)arg3;
- (bool)cloudContext:(ICCloudContext *)arg1 hasContextOptions:(unsigned long long)arg2;
- (void)cloudContext:(ICCloudContext *)arg1 receivedZoneNotFound:(CKRecordZoneID *)arg2 accountID:(NSString *)arg3;
- (void)cloudContext:(ICCloudContext *)arg1 sharedZoneWasDeleted:(CKRecordZoneID *)arg2 accountID:(NSString *)arg3;
- (void)cloudContext:(ICCloudContext *)arg1 userDidDeleteRecordZoneWithID:(CKRecordZoneID *)arg2 accountID:(NSString *)arg3;
- (NSPersistentStoreCoordinator *)persistentStoreCoordinatorForCloudContext:(ICCloudContext *)arg1;
- (NSManagedObjectContext *)viewContextForCloudContext:(ICCloudContext *)arg1;

@optional

- (NSDictionary *)containersByAccountIDForCloudContext:(ICCloudContext *)arg1;
- (NSString *)overrideAccountIDForCloudContext:(ICCloudContext *)arg1;

@end
