/* Generated by RuntimeBrowser.
 */

@protocol INAddTasksIntentHandlingPrivate <INAddTasksIntentHandling>

@optional

- (void)resolveContactEventTriggerForAddTasks:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: INAddTasksIntent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, INAddTasksContactEventTriggerResolutionResult *, void*
- (void)resolveContactEventTriggerForAddTasks:(void *)arg1 withCompletion:(void *)arg2; // needs 2 arg types, found 7: INAddTasksIntent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, INContactEventTriggerResolutionResult *, void*
- (void)resolveTargetTaskListMembersForAddTasks:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: INAddTasksIntent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)resolveTargetTaskListMembersForAddTasks:(void *)arg1 withCompletion:(void *)arg2; // needs 2 arg types, found 7: INAddTasksIntent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)resolveTaskReferenceForAddTasks:(void *)arg1 withCompletion:(void *)arg2; // needs 2 arg types, found 7: INAddTasksIntent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, INTaskReferenceResolutionResult *, void*

@end
