/* Generated by RuntimeBrowser.
 */

@protocol MKFWeekDayScheduleRulePublicExtensions

@required

- (void)updateFromWeekDayScheduleRule:(HMWeekDayScheduleRule *)arg1;
- (HMWeekDayScheduleRule *)weekDayScheduleRule;

@end
