/* Generated by RuntimeBrowser.
 */

@protocol MTRPluginProtobufMessageTransport <NSObject>

@required

- (bool)deregisterForRequestMessageWithType:(NSNumber *)arg1 forSessionID:(NSUUID *)arg2;
- (bool)registerForRequestMessageWithType:(NSNumber *)arg1 requestHandler:(SEL)arg2 forSessionID:(NSUUID *)arg3;
- (void)removeDelegate:(id <MTRPluginProtobufMessageTransportDelegate>)arg1;
- (void)sendMessageToPrimaryHomeHub:(MTRPluginProtobufMessage *)arg1;
- (void)sendMessageToRemotePeer:(MTRPluginProtobufMessage *)arg1 peerDestination:(id)arg2;
- (void)setDelegate:(id <MTRPluginProtobufMessageTransportDelegate>)arg1 delegateQueue:(NSObject<OS_dispatch_queue> *)arg2;
- (void)setDelegate:(id <MTRPluginProtobufMessageTransportDelegate>)arg1 delegateQueue:(NSObject<OS_dispatch_queue> *)arg2 forSessionID:(NSUUID *)arg3;
- (bool)start;
- (bool)stop;

@end
