/* Generated by RuntimeBrowser.
 */

@protocol NFSecureTransactionServicesHandoverHybridSessionCallbacksInterface <NFSecureTransactionServicesHandoverBaseSessionCallbacksInterface, NFTNEPCallbackProtocol, NFContactlessPaymentSessionCallbacks>

@required

- (void)connectionHandoverProcessCompleted;
- (void)connectionHandoverProcessFailure:(NSError *)arg1;
- (void)connectionHandoverTNEPServiceSelected:(NSString *)arg1;

@end
