/* Generated by RuntimeBrowser.
 */

@protocol PAAccessEventRecord <NSObject>

@required

- (NSNumber *)accessCount;
- (NSString *)accessorBundleID;
- (NSString *)category;
- (NSDate *)endDate;
- (NSString *)identifier;
- (NSDate *)startDate;
- (long long)timing;

@end
