/* Generated by RuntimeBrowser.
 */

@protocol PXGStackLayoutSublayoutAlignmentDelegate <NSObject>

@optional

- (bool)stackLayout:(PXGStackLayout *)arg1 shouldAlignSublayoutToVisibleBottomEdge:(PXGLayout *)arg2;
- (bool)stackLayout:(PXGStackLayout *)arg1 shouldAlignSublayoutToVisibleTopEdge:(PXGLayout *)arg2;

@end
