/* Generated by RuntimeBrowser.
 */

@protocol REMeshPayload <NSObject, NSSecureCoding>

@required

- (unsigned long long)estimatePayloadContainerOverheadSize;
- (NSArray *)instances;
- (bool)isLimitedRenderAsset;
- (bool)isShareable;
- (struct FixedInlineArray<NS::SharedPtr<MTL::Buffer>, 8UL> { struct SharedPtr<MTL::Buffer> { struct Buffer {} *x_1_1_1; } x1[8]; })meshPayloadBuffersWithDevice:(id <MTLDevice>)arg1;
- (NSArray *)models;
- (NSArray *)parts;
- (struct FixedInlineArray<unsigned long, 8UL> { unsigned long long x1[8]; })payloadBufferSizes;
- (NSArray *)skeletons;
- (unsigned long long)totalPayloadSize;

@optional

- (void)makeBoundingBoxes:(void*)arg1 perPartPerInstanceBoundingBoxes:(void*)arg2;
- (struct MeshCollection { struct DynamicArray<re::MeshModel> { struct Allocator {} *x_1_1_1; unsigned long long x_1_1_2; unsigned long long x_1_1_3; unsigned int x_1_1_4; struct MeshModel {} *x_1_1_5; } x1; })makeMeshCollection:(const void*)arg1;

@end
