/* Generated by RuntimeBrowser.
 */

@protocol SFCalendarEvent <NSObject>

@required

- (NSDictionary *)dictionaryRepresentation;
- (NSDate *)endDate;
- (SFStructuredLocation *)endLocation;
- (NSTimeZone *)endTimeZone;
- (bool)isAllDay;
- (NSData *)jsonData;
- (SFStructuredLocation *)location;
- (NSString *)notes;
- (void)setEndDate:(NSDate *)arg1;
- (void)setEndLocation:(SFStructuredLocation *)arg1;
- (void)setEndTimeZone:(NSTimeZone *)arg1;
- (void)setIsAllDay:(bool)arg1;
- (void)setLocation:(SFStructuredLocation *)arg1;
- (void)setNotes:(NSString *)arg1;
- (void)setStartDate:(NSDate *)arg1;
- (void)setStartTimeZone:(NSTimeZone *)arg1;
- (void)setTitle:(NSString *)arg1;
- (void)setUrl:(NSURL *)arg1;
- (NSDate *)startDate;
- (NSTimeZone *)startTimeZone;
- (NSString *)title;
- (NSURL *)url;

@end
