/* Generated by RuntimeBrowser.
 */

@protocol ULXPCRequestProtocol <NSObject>

@required

- (void)connectWithServiceIdentifier:(NSUUID *)arg1 legacyServiceIdentifier:(NSUUID *)arg2 andRequestIdentifier:(NSUUID *)arg3;
- (void)createCustomLocationOfInterestAtCurrentLocationWithConfiguration:(ULCustomLoiConfiguration *)arg1;
- (void)deleteServiceWithIdentifier:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: NSUUID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)disconnectWithRequestIdentifier:(NSUUID *)arg1;
- (void)donateMicroLocationTruthTagWithTagUUID:(void *)arg1 correspondingToTriggerUUID:(void *)arg2 handler:(void *)arg3; // needs 3 arg types, found 8: NSUUID *, NSUUID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)donateMicroLocationTruthTagWithTagUUID:(void *)arg1 forRecordingEventsBetweenDate:(void *)arg2 andDate:(void *)arg3 handler:(void *)arg4; // needs 4 arg types, found 9: NSUUID *, NSDate *, NSDate *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)exportDatabaseWithReply:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)getMicroLocationInternalVersionWithReply:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, void*
- (void)getRecordingTriggerUUIDAndRequestMicroLocationRecordingScanWithAdditionalInformation:(void *)arg1 shouldForceRecording:(void *)arg2 handler:(void *)arg3; // needs 3 arg types, found 9: NSDictionary *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)labelRequestIdentifier:(NSUUID *)arg1 withPlaceIdentifier:(NSUUID *)arg2 withReturnIdentifier:(NSUUID *)arg3;
- (void)purgeDatabaseWithReply:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)queryServicesWithReply:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)removeCustomLocationOfInterestWithIdentifier:(NSString *)arg1;
- (void)requestAllModelsLearningWithRequestIdentifier:(NSUUID *)arg1;
- (void)requestCurrentMicroLocationWithAdditionalInformation:(NSDictionary *)arg1;
- (void)requestMicroLocationRecordingScanWithAdditionalInformation:(NSDictionary *)arg1;
- (void)requestObservationWithRequestIdentifier:(NSUUID *)arg1;
- (void)requestPredictionWithRequestIdentifier:(NSUUID *)arg1;
- (void)startUpdatingWithConfiguration:(ULUpdateConfiguration *)arg1 withRequestIdentifier:(NSUUID *)arg2;
- (void)stopUpdatingWithRequestIdentifier:(NSUUID *)arg1;

@end
