/* Generated by RuntimeBrowser.
 */

@protocol WBSHistoryImporterDelegate

@required

- (void)addVisitWithURLString:(NSString *)arg1 visitTime:(double)arg2 title:(NSString *)arg3 loadSuccessful:(bool)arg4 httpGet:(bool)arg5 redirectSourceURLString:(NSString *)arg6 redirectSourceVisitTime:(double)arg7 visitCount:(unsigned long long)arg8;
- (void)finishWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
