/* Generated by RuntimeBrowser.
 */

@protocol WFOutOfProcessWorkflowControllerVendor <NSObject>

@required

- (oneway void)computeFinderResizedSizesForImages:(void *)arg1 inSizes:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSArray<__WFContextualActionFile__> *, NSArray<__WFFinderImageResizeDescriptor__> *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSDictionary *, NSError *, void*
- (oneway void)extractVariableContentFromEncodedReference:(void *)arg1 forEncodedExpectedType:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSData *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (oneway void)fetchDisplayValueForRequest:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSData *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (oneway void)fetchToolInvocationSummaryForInvocation:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSData *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (oneway void)getCurrentProgressCompletedWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSNumber *, NSError *, void*
- (oneway void)handleIncomingFileForRemoteExecutionWithURL:(NSURL *)arg1 withIdentifier:(NSString *)arg2;
- (oneway void)injectContentAsVariable:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: WFAnyToolKitVariableContent *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, WFAnyPropertyListObject *, NSError *, void*
- (oneway void)pauseWorkflowAndWriteStateToDisk:(WFWorkflowRunningContext *)arg1;
- (oneway void)performQuery:(void *)arg1 inValueSet:(void *)arg2 toolInvocation:(void *)arg3 completionHandler:(void *)arg4; // needs 4 arg types, found 10: NSData *, NSData *, NSData *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)prewarmRunnerWithCompletion:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (oneway void)reindexToolKitDatabaseWithRequest:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: WFToolKitIndexingRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (oneway void)resolveDeferredValueFromEncodedStorage:(void *)arg1 forEncodedExpectedType:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSData *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (oneway void)resumeRunningFromContext:(void *)arg1 withRequest:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: WFWorkflowRunningContext *, WFWorkflowRunRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, WFWorkflowRunResult *, NSError *, void*
- (oneway void)runActionFromRunRequestData:(void *)arg1 runningContext:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSData *, WFWorkflowRunningContext *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, WFWorkflowRunResult *, NSError *, void*
- (oneway void)runToolWithInvocation:(NSData *)arg1;
- (oneway void)runWorkflowWithDescriptor:(void *)arg1 request:(void *)arg2 inEnvironment:(void *)arg3 runningContext:(void *)arg4 completion:(void *)arg5; // needs 5 arg types, found 11: WFWorkflowRunDescriptor *, WFWorkflowRunRequest *, NSNumber *, WFWorkflowRunningContext *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, WFWorkflowRunResult *, NSError *, void*
- (oneway void)stopWithError:(NSError *)arg1;
- (oneway void)updateRunViewSource:(WFWorkflowRunViewSource *)arg1;

@end
