/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriContactsIntents.framework/SiriContactsIntents
 */

@interface _TtGC19SiriContactsIntents17BaseIntentHandlerCS_28ModifyContactAttributeIntentCS_36ModifyContactAttributeIntentResponseCS_56ModifyContactAttributeRelatedSiriMatchesResolutionResult_ : NSObject {
    void $__lazy_storage_$_meCard;
    void contactResolver;
    void contactService;
    void passedPrereqs;
}

- (void).cxx_destruct;
- (id)init;

@end
