/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherMaps.framework/WeatherMaps
 */

@interface WeatherMaps.OverlayTileViewportManager : _TtCs12_SwiftObject {
    void layer;
    void lock;
    void overlayDescriptor;
    void progressReporter;
    void renderContext;
    void textureLoaderQueue;
    void tileLoaderFactory;
    void tileLoaders;
}

@end
