/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface BitrateLimits : NSObject {
    unsigned long long  defaultValue;
    unsigned long long  defaultValue2G;
    unsigned long long  defaultValueCellular;
    NSArray * limits;
}

@property (nonatomic, readonly) NSArray *limits;

- (void)capDefaultValues:(unsigned long long)arg1;
- (id)commonAudioOnlyLimits;
- (id)commonAudioOnlyLimitsLegacy;
- (id)commonAudioVideoLimits;
- (void)dealloc;
- (unsigned long long)defaultValueForNetwork:(bool)arg1;
- (id)initWithOperatingMode:(unsigned char)arg1 withBitrateCap:(unsigned long long)arg2 useCaseWatchContinuity:(bool)arg3;
- (id)limits;
- (void)setUpDefaultValuesAudioVideo;
- (void)setupDefaultValuesAudio;

@end
