/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface _TtC15ConversationKitP33_437EB4956F8C313AB56D9B5E6A4F0C8C32ScreenSharingControlStateManager : _TtCs12_SwiftObject {
    void screenSharingAvailable;
    void shareMenuButtonState;
}

@end
