/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface ConversationKit.ParticipantListViewConstraintManager : _TtCs12_SwiftObject {
    void bottomConstraint;
    void bottomConstraintVertical;
    void constraints;
    void containerLeadingConstraint;
    void controlsLeadingConstraint;
    void heightConstraint;
    void leadingConstraintVertical;
    void topConstraint;
    void topConstraintVertical;
    void trailingConstraint;
    void trailingConstraintVertical;
    void type;
}

@end
