/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVMobileChromelessContainerView : AVView {
    <AVMobileChromelessContainerViewDelegate> * _delegate;
    NSArray * _itemViews;
    double  _spacing;
}

@property (nonatomic) <AVMobileChromelessContainerViewDelegate> *delegate;
@property (nonatomic, retain) NSArray *itemViews;
@property (nonatomic) double spacing;

- (void).cxx_destruct;
- (id)delegate;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (id)itemViews;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg1;
- (void)setItemViews:(id)arg1;
- (void)setSpacing:(double)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (double)spacing;

@end
