/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
 */

@interface SSCAMetalLayerSession : NSObject <SSCAMLTimeInterval, SignpostJSONRepresentable> {
    SSOnGlassCAMetalDrawableStats * _cachedStats;
    SSInflightCAMetalLayerIntervalStats * _inFlightStats;
    bool  _includeTimelines;
    unsigned long long  _layerID;
    NSMutableArray * _mutableConfigurationTimeline;
    NSMutableArray * _mutableOnGlassDrawableIntervalTimeline;
    NSMutableArray * _mutableStatsTimeline;
    double  _timebaseRatio;
    SSCAMetalLayerStats * _totalSessionStats;
}

@property (nonatomic, retain) SSOnGlassCAMetalDrawableStats *cachedStats;
@property (nonatomic, readonly) NSArray *configurationTimeline;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDate *endDate;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SSInflightCAMetalLayerIntervalStats *inFlightStats;
@property (nonatomic, readonly) bool includeTimelines;
@property (nonatomic, readonly) unsigned long long layerID;
@property (nonatomic, readonly) NSMutableArray *mutableConfigurationTimeline;
@property (nonatomic, retain) NSMutableArray *mutableOnGlassDrawableIntervalTimeline;
@property (nonatomic, readonly) NSMutableArray *mutableStatsTimeline;
@property (nonatomic, readonly) SSOnGlassCAMetalDrawableStats *onGlassDrawableIntervalStats;
@property (nonatomic, readonly) NSArray *onGlassDrawableIntervalTimeline;
@property (nonatomic, readonly) NSDate *startDate;
@property (nonatomic, readonly) NSArray *statsTimeline;
@property (readonly) Class superclass;
@property (nonatomic, readonly) double timebaseRatio;
@property (nonatomic, readonly) SSCAMetalLayerStats *totalSessionStats;

- (void).cxx_destruct;
- (id)_dictionaryRepresentation:(bool)arg1;
- (id)_ingestAggregation:(id)arg1 timebaseRatio:(double)arg2 parentClientSession:(id)arg3 parentAccumulator:(id)arg4;
- (id)_ingestConfigurationInterval:(id)arg1;
- (id)_ingestOnGlassDrawableInterval:(id)arg1;
- (id)_sessionFromFilteredResults:(id)arg1 configurationTimeline:(id)arg2 errorOut:(id*)arg3;
- (id)cachedStats;
- (id)configurationTimeline;
- (id)debugDescription;
- (id)dictionaryRepresentation;
- (unsigned long long)durationMachContinuousTime;
- (double)durationMs;
- (unsigned long long)durationNanoseconds;
- (float)durationSeconds;
- (id)endDate;
- (unsigned long long)endMachContinuousTime;
- (double)endMs;
- (unsigned long long)endNanoseconds;
- (double)endSeconds;
- (id)inFlightStats;
- (bool)includeTimelines;
- (id)initWithID:(unsigned long long)arg1 includeTimelines:(bool)arg2 timebaseRatio:(double)arg3;
- (id)jsonDescription:(unsigned long long)arg1;
- (unsigned long long)layerID;
- (id)layerSessionFilteredToStartDate:(id)arg1 endDate:(id)arg2 errorOut:(id*)arg3;
- (id)layerSessionFilteredToStartMCT:(unsigned long long)arg1 endMCT:(unsigned long long)arg2 errorOut:(id*)arg3;
- (id)mutableConfigurationTimeline;
- (id)mutableOnGlassDrawableIntervalTimeline;
- (id)mutableStatsTimeline;
- (id)onGlassDrawableIntervalStats;
- (id)onGlassDrawableIntervalTimeline;
- (void)setCachedStats:(id)arg1;
- (void)setInFlightStats:(id)arg1;
- (void)setMutableOnGlassDrawableIntervalTimeline:(id)arg1;
- (id)startDate;
- (unsigned long long)startMachContinuousTime;
- (double)startMs;
- (unsigned long long)startNanoseconds;
- (double)startSeconds;
- (id)statsTimeline;
- (double)timebaseRatio;
- (id)totalSessionStats;

@end
