/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TelephonyBlastDoorSupport.framework/TelephonyBlastDoorSupport
 */

@interface _TtCV25TelephonyBlastDoorSupport13XMLTreeParser7Element : NSObject <NSXMLParserDelegate> {
    void attributes;
    void children;
    void errorContext;
    void name;
    void parent;
    void text;
}

- (void).cxx_destruct;
- (id)init;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;

@end
