/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoubleAgent.framework/DoubleAgent
 */

@interface AppleDoubleParser : NSObject {
    struct attr_header { struct apple_double_header { unsigned int x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3[4]; unsigned short x_1_1_4; struct apple_double_entry { unsigned int x_5_2_1; unsigned int x_5_2_2; unsigned int x_5_2_3; } x_1_1_5[2]; unsigned char x_1_1_6[32]; unsigned char x_1_1_7[2]; } x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7[3]; unsigned short x8; unsigned short x9; } * _attrHeader;
    bool  _emptyFinderInfo;
    int  _fileDescriptor;
    struct apple_double_header { unsigned int x1; unsigned int x2; unsigned int x3[4]; unsigned short x4; struct apple_double_entry { unsigned int x_5_1_1; unsigned int x_5_1_2; unsigned int x_5_1_3; } x5[2]; unsigned char x6[32]; unsigned char x7[2]; } * _fileHeader;
    unsigned long long  _fileSize;
    struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; } * _finderinfo;
    struct attr_entry { unsigned int x1; unsigned int x2; unsigned short x3; unsigned char x4; unsigned char x5[1]; } * _firstAttrEntry;
    unsigned long long  _headerSize;
    bool  _isAllocateXattr;
    NSMutableData * _rawHeader;
    bool  _readOnly;
    struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; } * _rsrcfork;
}

@property struct attr_header { struct apple_double_header { unsigned int x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3[4]; unsigned short x_1_1_4; struct apple_double_entry { unsigned int x_5_2_1; unsigned int x_5_2_2; unsigned int x_5_2_3; } x_1_1_5[2]; unsigned char x_1_1_6[32]; unsigned char x_1_1_7[2]; } x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7[3]; unsigned short x8; unsigned short x9; }*attrHeader;
@property bool emptyFinderInfo;
@property int fileDescriptor;
@property struct apple_double_header { unsigned int x1; unsigned int x2; unsigned int x3[4]; unsigned short x4; struct apple_double_entry { unsigned int x_5_1_1; unsigned int x_5_1_2; unsigned int x_5_1_3; } x5[2]; unsigned char x6[32]; unsigned char x7[2]; }*fileHeader;
@property unsigned long long fileSize;
@property struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*finderinfo;
@property struct attr_entry { unsigned int x1; unsigned int x2; unsigned short x3; unsigned char x4; unsigned char x5[1]; }*firstAttrEntry;
@property unsigned long long headerSize;
@property bool isAllocateXattr;
@property (retain) NSMutableData *rawHeader;
@property bool readOnly;
@property struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*rsrcfork;

- (void).cxx_destruct;
- (void)allocateXattrNamed:(id)arg1 sized:(unsigned long long)arg2 how:(unsigned int)arg3 reply:(id /* block */)arg4;
- (struct attr_header { struct apple_double_header { unsigned int x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3[4]; unsigned short x_1_1_4; struct apple_double_entry { unsigned int x_5_2_1; unsigned int x_5_2_2; unsigned int x_5_2_3; } x_1_1_5[2]; unsigned char x_1_1_6[32]; unsigned char x_1_1_7[2]; } x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7[3]; unsigned short x8; unsigned short x9; }*)attrHeader;
- (bool)createAttrHeaderIfNeeded:(id*)arg1;
- (bool)emptyFinderInfo;
- (int)fileDescriptor;
- (struct apple_double_header { unsigned int x1; unsigned int x2; unsigned int x3[4]; unsigned short x4; struct apple_double_entry { unsigned int x_5_1_1; unsigned int x_5_1_2; unsigned int x_5_1_3; } x5[2]; unsigned char x6[32]; unsigned char x7[2]; }*)fileHeader;
- (unsigned long long)fileSize;
- (bool)fillEmptyAppleDoubleFile:(id*)arg1;
- (struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*)finderinfo;
- (struct attr_entry { unsigned int x1; unsigned int x2; unsigned short x3; unsigned char x4; unsigned char x5[1]; }*)firstAttrEntry;
- (unsigned long long)headerSize;
- (void)initEmptyResourceFork:(struct rsrcfork_header { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned char x5[112]; unsigned char x6[128]; unsigned int x7; unsigned int x8; unsigned int x9; unsigned int x10; unsigned int x11; unsigned short x12; unsigned char x13; unsigned char x14; unsigned short x15; unsigned short x16; unsigned short x17; }*)arg1;
- (id)initWithFileDescriptor:(int)arg1 fileSize:(long long)arg2 isAllocateXattr:(bool)arg3;
- (id)initWithFileDescriptor:(int)arg1 isAllocateXattr:(bool)arg2;
- (bool)isAllocateXattr;
- (bool)isXattrNameValid:(struct attr_entry { unsigned int x1; unsigned int x2; unsigned short x3; unsigned char x4; unsigned char x5[1]; }*)arg1;
- (bool)isXattrProtected:(const char *)arg1;
- (void)listXattrs:(struct list_xattrs_result { unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned char x8[34860]; }*)arg1;
- (void)lookupXattrNamed:(id)arg1 reply:(id /* block */)arg2;
- (bool)parseAttrHeader:(id*)arg1;
- (bool)parseFileHeader:(id*)arg1;
- (bool)parseFinderInfoAndResourceFork:(id*)arg1;
- (id)rawHeader;
- (bool)readOnly;
- (bool)readRawHeader:(id*)arg1;
- (void)removeXattrNamed:(id)arg1 reply:(id /* block */)arg2;
- (struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*)rsrcfork;
- (void)setAttrHeader:(struct attr_header { struct apple_double_header { unsigned int x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3[4]; unsigned short x_1_1_4; struct apple_double_entry { unsigned int x_5_2_1; unsigned int x_5_2_2; unsigned int x_5_2_3; } x_1_1_5[2]; unsigned char x_1_1_6[32]; unsigned char x_1_1_7[2]; } x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7[3]; unsigned short x8; unsigned short x9; }*)arg1;
- (void)setEmptyFinderInfo:(bool)arg1;
- (void)setFileDescriptor:(int)arg1;
- (void)setFileHeader:(struct apple_double_header { unsigned int x1; unsigned int x2; unsigned int x3[4]; unsigned short x4; struct apple_double_entry { unsigned int x_5_1_1; unsigned int x_5_1_2; unsigned int x_5_1_3; } x5[2]; unsigned char x6[32]; unsigned char x7[2]; }*)arg1;
- (void)setFileSize:(unsigned long long)arg1;
- (void)setFinderinfo:(struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*)arg1;
- (void)setFirstAttrEntry:(struct attr_entry { unsigned int x1; unsigned int x2; unsigned short x3; unsigned char x4; unsigned char x5[1]; }*)arg1;
- (void)setHeaderSize:(unsigned long long)arg1;
- (void)setIsAllocateXattr:(bool)arg1;
- (void)setRawHeader:(id)arg1;
- (void)setReadOnly:(bool)arg1;
- (void)setRsrcfork:(struct apple_double_entry { unsigned int x1; unsigned int x2; unsigned int x3; }*)arg1;
- (bool)shiftDataDownAtOffset:(unsigned int)arg1 length:(unsigned int)arg2 delta:(unsigned long long)arg3 error:(id*)arg4;
- (bool)shiftDataUpAtOffset:(unsigned int)arg1 length:(unsigned int)arg2 delta:(unsigned long long)arg3 error:(id*)arg4;
- (void)swapAttrHeader:(struct attr_header { struct apple_double_header { unsigned int x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3[4]; unsigned short x_1_1_4; struct apple_double_entry { unsigned int x_5_2_1; unsigned int x_5_2_2; unsigned int x_5_2_3; } x_1_1_5[2]; unsigned char x_1_1_6[32]; unsigned char x_1_1_7[2]; } x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7[3]; unsigned short x8; unsigned short x9; }*)arg1;
- (void)swapFileHeader;
- (bool)updateFileSize:(id*)arg1;
- (void)updateFileSizeExplicit:(long long)arg1;
- (bool)writeHeaderToDiskUpToLength:(unsigned int)arg1 error:(id*)arg2;

@end
