/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthMedicationsDaemonPlugin.framework/HealthMedicationsDaemonPlugin
 */

@interface HDOntologyPregnancyTrimesterLactationRatingsProvider : NSObject

+ (id)pregnancyTrimesterLactationRatingsForConcept:(id)arg1;

@end
