/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
 */

@interface BMSleepModeEvent_v3 : BMSleepModeEvent

- (id)initWithProto:(id)arg1;

@end
