/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDCHIPXPCListener : HMFObject <HMFLogging, NSXPCListenerDelegate> {
    NSXPCInterface * _exportedInterface;
    HMDHomeManager * _homeManager;
    NSXPCListener * _listener;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSMutableSet * _mutableConnections;
    HMDProcessMonitor * _processMonitor;
    NSObject<OS_dispatch_queue> * _processMonitorQueue;
    NSXPCInterface * _remoteObjectInterface;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSXPCInterface *exportedInterface;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) HMDHomeManager *homeManager;
@property (readonly) NSXPCListener *listener;
@property (nonatomic, readonly) NSMutableSet *mutableConnections;
@property (nonatomic, readonly) HMDProcessMonitor *processMonitor;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *processMonitorQueue;
@property (nonatomic, readonly) NSXPCInterface *remoteObjectInterface;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *workQueue;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)createClientConnectionWithRemoteObjectProxy:(id)arg1 homeManager:(id)arg2 connection:(id)arg3 backgroundModeEntitled:(bool)arg4;
- (id)exportedInterface;
- (id)homeManager;
- (id)initWithHomeManager:(id)arg1;
- (id)listener;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)mutableConnections;
- (id)processMonitor;
- (id)processMonitorQueue;
- (id)remoteObjectInterface;
- (void)start;
- (void)stop;
- (id)workQueue;

@end
