/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDLegacyCloudDatabase : HMBCloudDatabase

+ (id)recordZoneIDForLegacyName:(id)arg1;

- (id)createLegacyZone:(id)arg1 controllerIdentity:(id)arg2 delegate:(id)arg3 error:(id*)arg4;
- (id)initWithLocalDatabase:(id)arg1 configuration:(id)arg2;
- (id)mirrorLegacyZone:(id)arg1 controllerIdentity:(id)arg2 delegate:(id)arg3 error:(id*)arg4;

@end
