/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDModernTransportMessageContext : NSObject <HMFLogging, HMFTimerDelegate> {
    <HMDNetworkActivityWrapperFactory> * _activityFactory;
    id /* block */  _completionHandler;
    <HMDDateProvider> * _dateProvider;
    HMFMessageDestination * _destination;
    bool  _didFallback;
    bool  _didNotifyDeviceReachability;
    bool  _didSucceedSending;
    bool  _didTimeout;
    id /* block */  _fallbackCompletionBlock;
    HMFTimer * _fallbackTimer;
    NSUUID * _identifier;
    NSMapTable * _inProgressTransportToStartTimeMap;
    <HMMLogEventSubmitting> * _logEventSubmitter;
    HMDRemoteMessage * _message;
    NSUUID * _messageID;
    NSString * _messageName;
    HMDNetworkActivityWrapper * _messageNetworkActivity;
    long long  _messageQualityOfService;
    id /* block */  _messageResponseHandler;
    double  _messageTimeout;
    long long  _messageType;
    HMDModernTransportMessageContextOptions * _options;
    NSMutableSet * _remainingTransports;
    double  _requestStartTime;
    id /* block */  _responseCompletionBlock;
    HMFTimer * _responseTimer;
    unsigned long long  _successfulResponseCount;
    <HMDTimerProvider> * _timerProvider;
}

@property (readonly) <HMDNetworkActivityWrapperFactory> *activityFactory;
@property (copy) id /* block */ completionHandler;
@property (readonly) <HMDDateProvider> *dateProvider;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) HMFMessageDestination *destination;
@property (nonatomic) bool didFallback;
@property (nonatomic) bool didNotifyDeviceReachability;
@property (nonatomic, readonly) bool didSucceedSending;
@property (nonatomic) bool didTimeout;
@property (nonatomic, readonly) bool expectsResponse;
@property (copy) id /* block */ fallbackCompletionBlock;
@property (retain) HMFTimer *fallbackTimer;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) NSMapTable *inProgressTransportToStartTimeMap;
@property (nonatomic, readonly, copy) NSSet *inProgressTransports;
@property (readonly) <HMMLogEventSubmitting> *logEventSubmitter;
@property (retain) HMDRemoteMessage *message;
@property (nonatomic, readonly) NSUUID *messageID;
@property (nonatomic, readonly, copy) NSString *messageName;
@property (nonatomic, readonly) HMDNetworkActivityWrapper *messageNetworkActivity;
@property (nonatomic, readonly) long long messageQualityOfService;
@property (nonatomic, readonly, copy) id /* block */ messageResponseHandler;
@property (nonatomic, readonly) double messageTimeout;
@property (nonatomic, readonly) long long messageType;
@property (nonatomic, readonly) HMDModernTransportMessageContextOptions *options;
@property (nonatomic, readonly, copy) NSSet *remainingTransports;
@property double requestStartTime;
@property (copy) id /* block */ responseCompletionBlock;
@property (retain) HMFTimer *responseTimer;
@property (nonatomic, readonly) unsigned long long successfulResponseCount;
@property (readonly) Class superclass;
@property (nonatomic, readonly) double timeout;
@property (readonly) <HMDTimerProvider> *timerProvider;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)activityFactory;
- (void)completeSendingOverTransport:(id)arg1 withError:(id)arg2;
- (id /* block */)completionHandler;
- (id)dateProvider;
- (id)destination;
- (bool)didFallback;
- (bool)didNotifyDeviceReachability;
- (bool)didSucceedSending;
- (bool)didTimeout;
- (void)done;
- (bool)expectsResponse;
- (id /* block */)fallbackCompletionBlock;
- (id)fallbackTimer;
- (id)identifier;
- (id)inProgressTransportToStartTimeMap;
- (id)inProgressTransports;
- (id)initWithMessage:(id)arg1 options:(id)arg2 completionHandler:(id /* block */)arg3 dateProvider:(id)arg4 timerProvider:(id)arg5;
- (id)initWithMessage:(id)arg1 options:(id)arg2 completionHandler:(id /* block */)arg3 dateProvider:(id)arg4 timerProvider:(id)arg5 activityFactory:(id)arg6 logEventSubmitter:(id)arg7;
- (id)logEventSubmitter;
- (id)message;
- (id)messageID;
- (id)messageName;
- (id)messageNetworkActivity;
- (long long)messageQualityOfService;
- (id /* block */)messageResponseHandler;
- (double)messageTimeout;
- (long long)messageType;
- (id)options;
- (id)preparedMessageWithTimeout:(double)arg1;
- (void)receivedResponseOverTransport:(id)arg1 withError:(id)arg2;
- (id)remainingTransports;
- (double)requestStartTime;
- (id /* block */)responseCompletionBlock;
- (id)responseTimer;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setDidFallback:(bool)arg1;
- (void)setDidNotifyDeviceReachability:(bool)arg1;
- (void)setDidTimeout:(bool)arg1;
- (void)setFallbackCompletionBlock:(id /* block */)arg1;
- (void)setFallbackTimer:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setRequestStartTime:(double)arg1;
- (void)setResponseCompletionBlock:(id /* block */)arg1;
- (void)setResponseTimer:(id)arg1;
- (void)startResponseTimerWithTimeInterval:(double)arg1 queue:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)startSendingOverTransport:(id)arg1;
- (void)startTransportFallbackTimerWithTimeInterval:(double)arg1 queue:(id)arg2 completionHandler:(id /* block */)arg3;
- (unsigned long long)successfulResponseCount;
- (double)timeout;
- (double)timeoutRemaining;
- (void)timerDidFire:(id)arg1;
- (id)timerProvider;

@end
