/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemonLegacy.framework/HomeKitDaemonLegacy
 */

@interface HMDSharedUserInviteOwnerSendLogEventBuilder : HMDSharedUserInviteLogEventBuilder <HMFLogging> {
    HMDHome * _home;
    HMDSharedUserInviteOwnerSendLogEvent * _inviteLogEvent;
    unsigned long long  addUserToShareBeginTime;
    unsigned long long  createShareBeginTime;
    unsigned long long  sendInvitationBeginTime;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) HMDHome *home;
@property (readonly) HMDSharedUserInviteOwnerSendLogEvent *inviteLogEvent;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)cancel;
- (id)home;
- (id)initWithHome:(id)arg1 sessionIdentifier:(id)arg2 invitationType:(unsigned long long)arg3;
- (id)initWithHome:(id)arg1 sessionIdentifier:(id)arg2 invitationType:(unsigned long long)arg3 logEventSubmitter:(id)arg4 currentUpTicksBlock:(id /* block */)arg5 submissionTimerFactory:(id /* block */)arg6;
- (id)inviteLogEvent;
- (bool)isReady;
- (void)markAddUserBegin;
- (void)markAddUserEnd;
- (void)markCreateShareBegin;
- (void)markCreateShareEnd;
- (void)markSendInviteBegin;
- (void)markSendInviteEnd;
- (void)markUserAlreadyAddedToShare;
- (void)submit;

@end
