/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIIntelligenceSupport.framework/UIIntelligenceSupport
 */

@interface UIIntelligenceSupport.UIIntelligenceCollectionRemoteContextWrapper : NSObject <NSSecureCoding> {
    void remoteContext;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
