/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUIServices.framework/ControlCenterUIServices
 */

@interface CCUISControlsGalleryResult : NSObject {
    void control;
    void promptsForUserConfiguration;
}

@property (nonatomic, readonly) CCUISConfiguredControl *control;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) bool promptsForUserConfiguration;

- (void).cxx_destruct;
- (id)control;
- (id)description;
- (id)init;
- (id)initWithControl:(id)arg1 promptsForUserConfiguration:(bool)arg2;
- (bool)promptsForUserConfiguration;

@end
