/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BusinessChatService.framework/BusinessChatService
 */

@interface BCSCallerIdParquetMessage : PBCodable <NSCopying> {
    struct { 
        unsigned int phoneHash : 1; 
        unsigned int isVerified : 1; 
    }  _has;
    NSMutableArray * _intents;
    bool  _isVerified;
    NSData * _logo;
    NSString * _logoFormat;
    NSMutableArray * _names;
    long long  _phoneHash;
    NSString * _phoneNumber;
}

@property (nonatomic) bool hasIsVerified;
@property (nonatomic, readonly) bool hasLogo;
@property (nonatomic, readonly) bool hasLogoFormat;
@property (nonatomic) bool hasPhoneHash;
@property (nonatomic, readonly) bool hasPhoneNumber;
@property (nonatomic, retain) NSMutableArray *intents;
@property (nonatomic) bool isVerified;
@property (nonatomic, retain) NSData *logo;
@property (nonatomic, retain) NSString *logoFormat;
@property (nonatomic, retain) NSMutableArray *names;
@property (nonatomic) long long phoneHash;
@property (nonatomic, retain) NSString *phoneNumber;

+ (Class)intentType;
+ (Class)nameType;

- (void).cxx_destruct;
- (void)addIntent:(id)arg1;
- (void)addName:(id)arg1;
- (void)clearIntents;
- (void)clearNames;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasIsVerified;
- (bool)hasLogo;
- (bool)hasLogoFormat;
- (bool)hasPhoneHash;
- (bool)hasPhoneNumber;
- (unsigned long long)hash;
- (id)intentAtIndex:(unsigned long long)arg1;
- (id)intents;
- (unsigned long long)intentsCount;
- (bool)isEqual:(id)arg1;
- (bool)isVerified;
- (id)logo;
- (id)logoFormat;
- (void)mergeFrom:(id)arg1;
- (id)nameAtIndex:(unsigned long long)arg1;
- (id)names;
- (unsigned long long)namesCount;
- (long long)phoneHash;
- (id)phoneNumber;
- (bool)readFrom:(id)arg1;
- (void)setHasIsVerified:(bool)arg1;
- (void)setHasPhoneHash:(bool)arg1;
- (void)setIntents:(id)arg1;
- (void)setIsVerified:(bool)arg1;
- (void)setLogo:(id)arg1;
- (void)setLogoFormat:(id)arg1;
- (void)setNames:(id)arg1;
- (void)setPhoneHash:(long long)arg1;
- (void)setPhoneNumber:(id)arg1;
- (void)writeTo:(id)arg1;

@end
