/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemoteManagementModel.framework/RemoteManagementModel
 */

@interface RMModelStatusPasscodeCompliance : RMModelStatusBase

+ (id)statusItemType;
+ (id)supportedOS;

- (bool)isArrayValue;

@end
