/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GenerativeAssistantCommon.framework/GenerativeAssistantCommon
 */

@interface GenerativeAssistantCommon.MetricsUtils : _TtCs12_SwiftObject {
    void performanceMetrics;
    void signpostIntervals;
    void usecasesAndEvents;
}

@end
