/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RoomPlan.framework/RoomPlan
 */

@interface DelaunayPoint : NSObject {
    void _value;
}

@property (readonly) void value;

- (id)initWithValue;
- (void)value;

@end
