/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@interface CTLazuliSystemCapablities : NSObject <NSCopying, NSSecureCoding> {
    bool  _autoAcceptChat;
    bool  _autoAcceptGroupChat;
    NSURL * _exploderUri;
    bool  _fileTransferAutoAccept;
    NSNumber * _fileTransferMaxRecipients;
    NSURL * _fileTransferUrl;
    NSNumber * _maxFileTransferSize;
    NSNumber * _maxGroupSize;
}

@property (nonatomic) bool autoAcceptChat;
@property (nonatomic) bool autoAcceptGroupChat;
@property (nonatomic, retain) NSURL *exploderUri;
@property (nonatomic) bool fileTransferAutoAccept;
@property (nonatomic, retain) NSNumber *fileTransferMaxRecipients;
@property (nonatomic, retain) NSURL *fileTransferUrl;
@property (nonatomic, retain) NSNumber *maxFileTransferSize;
@property (nonatomic, retain) NSNumber *maxGroupSize;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (bool)autoAcceptChat;
- (bool)autoAcceptGroupChat;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)exploderUri;
- (bool)fileTransferAutoAccept;
- (id)fileTransferMaxRecipients;
- (id)fileTransferUrl;
- (id)initWithCoder:(id)arg1;
- (id)initWithReflection:(const void*)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToCTLazuliSystemCapablities:(id)arg1;
- (id)maxFileTransferSize;
- (id)maxGroupSize;
- (void)setAutoAcceptChat:(bool)arg1;
- (void)setAutoAcceptGroupChat:(bool)arg1;
- (void)setExploderUri:(id)arg1;
- (void)setFileTransferAutoAccept:(bool)arg1;
- (void)setFileTransferMaxRecipients:(id)arg1;
- (void)setFileTransferUrl:(id)arg1;
- (void)setMaxFileTransferSize:(id)arg1;
- (void)setMaxGroupSize:(id)arg1;

@end
