/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@interface CTXPCGetRegistrationStatusResponse : CTXPCResponseMessage

@property (nonatomic, readonly) NSString *status;

- (id)initWithStatus:(id)arg1;
- (id)status;

@end
