/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileStoreUI.framework/MobileStoreUI
 */

@interface SUUINavigationDocumentController : NSObject <IKAppNavigationController> {
    SUUIClientContext * _clientContext;
    <SUUINavigationDocumentDelegate> * _delegate;
    UINavigationController * _moreNavigationController;
    UINavigationController * _navigationController;
    UINavigationController * _overrideNavigationController;
    NSMutableArray * _pendingNavigationStackEnsureConsistencyRequests;
    NSMutableArray * _stackItems;
}

@property (nonatomic, retain) SUUIClientContext *clientContext;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (nonatomic) <SUUINavigationDocumentDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSArray *documentStackItems;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UINavigationController *moreNavigationController;
@property (nonatomic, readonly) UINavigationController *navigationController;
@property (nonatomic, retain) UINavigationController *overrideNavigationController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_activeNavigationController;
- (void)_applyDocumentReplacementForOldStackItem:(id)arg1 atOldIndex:(long long)arg2 withStackItem:(id)arg3;
- (void)_ensureStackConsistencyForNavigationControllerOperation:(long long)arg1 operationDidComplete:(bool)arg2;
- (void)_handleStackDidChange;
- (void)_scheduleFlushingPendingNavigationStackEnsureConsistencyRequestsWithTransitionCoordinator:(id)arg1;
- (void)_unloadAllStackItems;
- (id)asNilStringIfUndefined:(id)arg1;
- (void)clear;
- (id)clientContext;
- (id)delegate;
- (id)documentStackItems;
- (id)documents;
- (void)ensureStackConsistencyForNavigationControllerOperation:(long long)arg1 operationDidComplete:(bool)arg2;
- (id)initWithNavigationController:(id)arg1;
- (void)insertDocument:(id)arg1 beforeDocument:(id)arg2 options:(id)arg3;
- (bool)isStopPageBagValueOverrideEnabledForTab:(id)arg1;
- (bool)isStopPageEnabledForTab:(id)arg1;
- (id)moreNavigationController;
- (id)navigationController;
- (id)overrideNavigationController;
- (void)popAllDocuments;
- (void)popDocument;
- (void)popToDocument:(id)arg1;
- (void)popToRootDocument;
- (void)pushDocument:(id)arg1 options:(id)arg2;
- (void)removeDocument:(id)arg1;
- (void)replaceDocument:(id)arg1 withDocument:(id)arg2 options:(id)arg3;
- (void)setClientContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMoreNavigationController:(id)arg1;
- (void)setOverrideNavigationController:(id)arg1;
- (void)setStackItems:(id)arg1 animated:(bool)arg2;
- (void)showStopPageForTab:(id)arg1 replacementAppAdamId:(id)arg2 title:(id)arg3 subtitle:(id)arg4 artwork:(id)arg5 deeplinkUrl:(id)arg6 force:(bool)arg7 purchasesUrl:(id)arg8 wishlistButtonTitle:(id)arg9 showWishlistButton:(bool)arg10;

@end
