/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestions.framework/SiriSuggestions
 */

@interface SiriSuggestions.AssistantSuggestionsTieringSelector : _TtCs12_SwiftObject {
    void config;
}

@end
