/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestions.framework/SiriSuggestions
 */

@interface SiriSuggestions.AppEntityCountBasedSignalExtractor : _TtCs12_SwiftObject {
    void appEntityTypeTransformer;
}

@end
