/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityReaderDaemon.framework/ProximityReaderDaemon
 */

@interface ProximityReaderDaemon.SPRReaderProxy : _TtCs12_SwiftObject {
    void cachedSPRConfigurator;
    void cachedSPRMonitor;
    void cachedSPRPINController;
    void cachedSPRReader;
    void mockSPRReader;
    void mocked;
    void monitorQueue;
}

@end
