/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityReaderDaemon.framework/ProximityReaderDaemon
 */

@interface ProximityReaderDaemon.SecureChannel : _TtCs12_SwiftObject {
    void akUrlSession;
    void urlSession;
}

@end
