/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DoNotDisturbServer.framework/DoNotDisturbServer
 */

@interface DNDSServerDomain : PTDomain

+ (id)domainGroupName;
+ (id)domainName;
+ (id)rootSettings;
+ (Class)rootSettingsClass;

@end
