/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SensitiveContentAnalysisUI.framework/SensitiveContentAnalysisUI
 */

@interface SCUIReportEvidence : NSObject {
    NSString * _chatRoomName;
    unsigned long long  _flags;
    NSDate * _incidentDate;
    NSString * _localeIdentifier;
    NSDate * _reportCreationDate;
    long long  _reportingApplication;
    NSArray * _suspects;
    NSArray * _unsortedChatTranscript;
    SCUIReportVictim * _victim;
}

@property (copy) NSString *chatRoomName;
@property unsigned long long flags;
@property (copy) NSDate *incidentDate;
@property (readonly, copy) NSString *localeIdentifier;
@property (readonly, copy) NSDate *reportCreationDate;
@property (readonly) long long reportingApplication;
@property (readonly, copy) NSArray *suspects;
@property (copy) NSArray *unsortedChatTranscript;
@property (readonly, copy) SCUIReportVictim *victim;

- (void).cxx_destruct;
- (id)chatRoomName;
- (unsigned long long)flags;
- (id)incidentDate;
- (id)initWithVictim:(id)arg1 suspects:(id)arg2 application:(long long)arg3;
- (id)initWithVictimHandle:(id)arg1 media:(id)arg2 selectedMediaObject:(id)arg3 chat:(id)arg4;
- (id)initWithVictimHandle:(id)arg1 sensitiveContentMedia:(id)arg2 chat:(id)arg3;
- (id)localeIdentifier;
- (id)reportCreationDate;
- (long long)reportingApplication;
- (void)setChatRoomName:(id)arg1;
- (void)setFlags:(unsigned long long)arg1;
- (void)setIncidentDate:(id)arg1;
- (void)setUnsortedChatTranscript:(id)arg1;
- (id)suspects;
- (id)unsortedChatTranscript;
- (id)victim;

@end
