/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
 */

@interface _CHSIntentReferenceBufChanges : NSObject {
    unsigned char  _changeTypeIntentData;
    unsigned char  _changeTypePartialIntentData;
    unsigned char  _changeTypeSchemaData;
    unsigned char  _changeTypeStableHash;
    unsigned int  _replacementIntentData;
    unsigned int  _replacementPartialIntentData;
    unsigned int  _replacementSchemaData;
    long long  _replacementStableHash;
}

- (void)omitIntentData;
- (void)omitPartialIntentData;
- (void)omitSchemaData;
- (void)omitStableHash;
- (void)preserveIntentData;
- (void)preservePartialIntentData;
- (void)preserveSchemaData;
- (void)preserveStableHash;
- (void)replaceIntentData:(id)arg1;
- (void)replacePartialIntentData:(id)arg1;
- (void)replaceSchemaData:(id)arg1;
- (void)replaceStableHash:(long long)arg1;

@end
