/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
 */

@interface ChronoServices.RelevanceCacheTransaction : _TtCs12_SwiftObject {
    void cache;
    void committed;
    void tempFilename;
    void writer;
}

@end
