/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsUI.framework/PodcastsUI
 */

@interface _TtCC10PodcastsUI18PlaybackController15QueueController : _TtCs12_SwiftObject {
    void playbackController;
}

@end
