/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsUI.framework/PodcastsUI
 */

@interface PodcastsUI.ClickLocationTracker : _TtCs12_SwiftObject {
    void elements;
}

@end
