/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VDAF.framework/VDAF
 */

@interface VDAF.XofHmacSha256Aes128 : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  hmac;
    void stream;
}

@end
