/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MessagesSettingsUI.framework/MessagesSettingsUI
 */

@interface CKiCloudSettingsUtils : NSObject

+ (id)iCloudSettingsSyncText;
+ (id)lastSyncedDateStringForDate:(id)arg1 inContext:(long long)arg2;
+ (id)localizedStringWithKey:(id)arg1 inPlistNamed:(id)arg2;
+ (id)sharedNumberFormatter;
+ (id)specifierWithTitle:(id)arg1 target:(id)arg2 selector:(SEL)arg3;

@end
