/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface AMSUIAuthenticateTaskCoordinator : AMSAuthenticateTaskCoordinator

- (id)_authenticateTaskForItem:(id)arg1;
- (id)_authenticateTaskForItem:(id)arg1 authenticationResults:(id)arg2;
- (id)handleRequest:(id)arg1 presentingViewController:(id)arg2;

@end
