/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface PPMUtilities : NSObject

+ (double)PPMConfirmedValueWithValue:(double)arg1 newValue:(double)arg2;
+ (double)PPMScaledValueUsingValue:(double)arg1;

@end
