/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourUI.framework/SeymourUI
 */

@interface SeymourUI.RemoteBrowsingSourceCoordinator : _TtCs12_SwiftObject {
    void environment;
    void eventHub;
    void remoteBrowsingClient;
    void source;
    void state;
    void subscriptionToken;
}

@end
