/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PerfPowerServicesReader.framework/PerfPowerServicesReader
 */

@interface AWDMETRICSCellularPowerLogNRFRCoverage : PBCodable <NSCopying> {
    int  _fR1;
    int  _fR2;
    struct { 
        unsigned int timestamp : 1; 
        unsigned int fR1 : 1; 
        unsigned int fR2 : 1; 
        unsigned int subsId : 1; 
    }  _has;
    unsigned int  _subsId;
    unsigned long long  _timestamp;
}

@property (nonatomic) int fR1;
@property (nonatomic) int fR2;
@property (nonatomic) bool hasFR1;
@property (nonatomic) bool hasFR2;
@property (nonatomic) bool hasSubsId;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) unsigned int subsId;
@property (nonatomic) unsigned long long timestamp;

- (int)StringAsFR1:(id)arg1;
- (int)StringAsFR2:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (int)fR1;
- (id)fR1AsString:(int)arg1;
- (int)fR2;
- (id)fR2AsString:(int)arg1;
- (bool)hasFR1;
- (bool)hasFR2;
- (bool)hasSubsId;
- (bool)hasTimestamp;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setFR1:(int)arg1;
- (void)setFR2:(int)arg1;
- (void)setHasFR1:(bool)arg1;
- (void)setHasFR2:(bool)arg1;
- (void)setHasSubsId:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setSubsId:(unsigned int)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (unsigned int)subsId;
- (unsigned long long)timestamp;
- (void)writeTo:(id)arg1;

@end
