/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesEditor.framework/NotesEditor
 */

@interface ICPaperKitTextFindingResult : ICTextFindingResult {
    unsigned long long  _order;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _searchResultRect;
}

@property (nonatomic) unsigned long long order;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } searchResultRect;

+ (double)scaleForDrawingBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

- (long long)compare:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForHighlightInTextView:(id)arg1;
- (id)framesForHighlightInTextView:(id)arg1;
- (void)generateFindPreviewImageForPaperKitAttachment:(id)arg1 completion:(id /* block */)arg2;
- (unsigned long long)order;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })searchResultRect;
- (void)selectInTextView:(id)arg1;
- (void)setOrder:(unsigned long long)arg1;
- (void)setSearchResultRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

@end
