/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesEditor.framework/NotesEditor
 */

@interface NotesEditor.TranscriptViewController : UIViewController <ICScrollViewKeyboardResizerDelegate, NSTextContentManagerDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, UITextViewDelegate> {
    void $__lazy_storage_$_scrollViewResizer;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  activeSegment;
    void audioController;
    void currentlyDragging;
    void currentlyScrolling;
    void hapticImpactIntensityForSelectionChange;
    void interactionTimer;
    void isAutoScrollingForSegmentChange;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastScrolledDate;
    void longPressRecognizer;
    void model;
    void paragraphRanges;
    void playbackTime;
    void previousContentOffset;
    void previousParagraphRange;
    void previousSpeaker;
    void queryEntered;
    void representableAdapter;
    void selectActiveSegmentGR;
    void selectionFeedbackGenerator;
}

- (void).cxx_destruct;
- (void)audioDidStopWithNotification:(id)arg1;
- (void)audioPlaybackTimeDidChangeWithNotification:(id)arg1;
- (double)consumedBottomAreaForResizer:(id)arg1;
- (void)dealloc;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)inactivityTimerFired;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)keyboardResizerScrollView;
- (void)loadView;
- (void)longPress:(id)arg1;
- (void)pan:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint { double x1; double x2; })arg2 targetContentOffset:(struct CGPoint { double x1; double x2; }*)arg3;
- (void)tap:(id)arg1;
- (double)topInsetForResizer:(id)arg1;
- (void)userDidInteract;
- (void)viewDidAppear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
