/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCNewsTabiEventAggregationArticleUndislikedConditions : FCNewsTabiEventAggregationBaseEventConditions

@end
