/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCPeopleAlsoReadFeedItemService : NSObject <FCFeedItemServiceType> {
    <FCNewsAppConfigurationManager> * _configurationManager;
    <FCContentContext> * _contentContext;
    FCReadingHistory * _readingHistory;
}

@property (nonatomic, readonly) <FCNewsAppConfigurationManager> *configurationManager;
@property (nonatomic, readonly) <FCContentContext> *contentContext;
@property (nonatomic, readonly) FCReadingHistory *readingHistory;

- (void).cxx_destruct;
- (id)configurationManager;
- (id)contentContext;
- (void)fetchFeedItemsWithCursor:(id)arg1 completion:(id /* block */)arg2;
- (id)init;
- (id)initWithConfigurationManager:(id)arg1 contentContext:(id)arg2 readingHistory:(id)arg3;
- (id)readingHistory;

@end
