/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@interface GKTextModerator : NSObject {
    void implementation;
}

@property (nonatomic, readonly) NSLocale *locale;

+ (id)defaultTextModerator;
+ (id)forLocale:(id)arg1;
+ (bool)isAvailable;
+ (bool)isAvailableForLocale:(id)arg1;
+ (id)localeAgnosticTextModerator;

- (void).cxx_destruct;
- (id)init;
- (id)locale;
- (bool)shouldFilter:(id)arg1;

@end
