/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LinkServices.framework/LinkServices
 */

@interface LNBundleConnectionPolicy : NSObject <NSCopying> {
    NSString * _appBundleIdentifier;
    NSString * _bundleIdentifier;
    NSString * _processInstanceIdentifier;
}

@property (nonatomic, readonly, copy) NSString *appBundleIdentifier;
@property (nonatomic, readonly) NSString *bundleIdentifier;
@property (nonatomic, readonly, copy) NSString *processInstanceIdentifier;

- (void).cxx_destruct;
- (id)appBundleIdentifier;
- (id)bundleIdentifier;
- (id)connectionWithError:(id*)arg1;
- (id)connectionWithUserIdentity:(id)arg1 error:(id*)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)initWithBundleIdentifier:(id)arg1 appBundleIdentifier:(id)arg2 processInstanceIdentifier:(id)arg3;
- (bool)isEqual:(id)arg1;
- (id)processInstanceIdentifier;

@end
