/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LinkServices.framework/LinkServices
 */

@interface LNSpotlightCascadeHandler : NSObject

+ (id)_getSearchQuery:(id)arg1 context:(id)arg2;
+ (void)handleDeletionStream:(id)arg1 items:(id)arg2 bundleId:(id)arg3 completionHandler:(id /* block */)arg4;
+ (void)handleFullSetStream:(id)arg1 items:(id)arg2 bundleId:(id)arg3 quota:(unsigned long long)arg4 indexName:(id)arg5 serialNumber:(unsigned long long)arg6 completionHandler:(id /* block */)arg7;
+ (void)handleIncrementalStream:(id)arg1 items:(id)arg2 bundleId:(id)arg3 existingItemCount:(unsigned long long)arg4 quota:(unsigned long long)arg5 completionHandler:(id /* block */)arg6;

@end
