/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface _SFPBRFSummaryItemPairCardSection : PBCodable <NSSecureCoding, _SFPBRFSummaryItemPairCardSection> {
    _SFPBRFTextProperty * _text_1;
    _SFPBRFTextProperty * _text_2;
    _SFPBRFTextProperty * _text_3;
    _SFPBRFTextProperty * _text_4;
    _SFPBRFTextProperty * _text_5;
    _SFPBRFTextProperty * _text_6;
    _SFPBRFTextProperty * _text_7;
    _SFPBRFTextProperty * _text_8;
    _SFPBRFVisualProperty * _thumbnail_1;
    _SFPBRFVisualProperty * _thumbnail_2;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (readonly) Class superclass;
@property (nonatomic, retain) _SFPBRFTextProperty *text_1;
@property (nonatomic, retain) _SFPBRFTextProperty *text_2;
@property (nonatomic, retain) _SFPBRFTextProperty *text_3;
@property (nonatomic, retain) _SFPBRFTextProperty *text_4;
@property (nonatomic, retain) _SFPBRFTextProperty *text_5;
@property (nonatomic, retain) _SFPBRFTextProperty *text_6;
@property (nonatomic, retain) _SFPBRFTextProperty *text_7;
@property (nonatomic, retain) _SFPBRFTextProperty *text_8;
@property (nonatomic, retain) _SFPBRFVisualProperty *thumbnail_1;
@property (nonatomic, retain) _SFPBRFVisualProperty *thumbnail_2;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFacade:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setText_1:(id)arg1;
- (void)setText_2:(id)arg1;
- (void)setText_3:(id)arg1;
- (void)setText_4:(id)arg1;
- (void)setText_5:(id)arg1;
- (void)setText_6:(id)arg1;
- (void)setText_7:(id)arg1;
- (void)setText_8:(id)arg1;
- (void)setThumbnail_1:(id)arg1;
- (void)setThumbnail_2:(id)arg1;
- (id)text_1;
- (id)text_2;
- (id)text_3;
- (id)text_4;
- (id)text_5;
- (id)text_6;
- (id)text_7;
- (id)text_8;
- (id)thumbnail_1;
- (id)thumbnail_2;
- (void)writeTo:(id)arg1;

@end
