/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface _SFPBSafariTableOfContentsItem : PBCodable <NSSecureCoding, _SFPBSafariTableOfContentsItem> {
    NSString * _elementPath;
    NSString * _text;
    NSString * _trailingText;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *elementPath;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *text;
@property (nonatomic, copy) NSString *trailingText;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)elementPath;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFacade:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setElementPath:(id)arg1;
- (void)setText:(id)arg1;
- (void)setTrailingText:(id)arg1;
- (id)text;
- (id)trailingText;
- (void)writeTo:(id)arg1;

@end
