/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface SFStoreButtonItem : SFButtonItem <NSCopying, NSSecureCoding, SFStoreButtonItem> {
    struct { 
        unsigned int shouldOpenAppAfterInstallCompletes : 1; 
        unsigned int identifierType : 1; 
    }  _has;
    NSString * _identifier;
    int  _identifierType;
    bool  _shouldOpenAppAfterInstallCompletes;
}

@property (nonatomic, retain) SFButtonItemAppearance *buttonAppearance;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic) int identifierType;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) bool shouldOpenAppAfterInstallCompletes;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long uniqueId;

// Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasIdentifierType;
- (bool)hasShouldOpenAppAfterInstallCompletes;
- (unsigned long long)hash;
- (id)identifier;
- (int)identifierType;
- (id)initWithCoder:(id)arg1;
- (id)initWithProtobuf:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (void)setIdentifier:(id)arg1;
- (void)setIdentifierType:(int)arg1;
- (void)setShouldOpenAppAfterInstallCompletes:(bool)arg1;
- (bool)shouldOpenAppAfterInstallCompletes;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (Class)_searchUIButtonItemGeneratorClass;
- (Class)searchUI_viewControllerClass;

@end
