/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BlastDoor.framework/BlastDoor
 */

@interface BlastDoorLinkIsRichLinkAttribute : NSObject {
    void linkIsRichLinkAttribute;
}

@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) bool isRichLink;
@property (nonatomic, readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } range;

- (id)description;
- (id)init;
- (bool)isRichLink;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })range;

@end
