/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoHomeIntents.framework/NanoHomeIntents
 */

@interface NHOIntentLocalization : NSObject

+ (id)actionSetRectangularWidgetText;
+ (id)currentLocationEnergyWidgetName;
+ (id)electricityRatesWidgetName;
+ (id)electricityUsageWidgetName;
+ (id)forecastEnergyWidgetName;
+ (id)homeSpecificElectricityRatesWidgetNameWithHomeName:(id)arg1;
+ (id)homeSpecificElectricityUsageWidgetNameWithHomeName:(id)arg1;
+ (id)homeSpecificEnergyWidgetNameWithHomeName:(id)arg1;
+ (id)launcherWidgetName;
+ (id)smartStackWidgetName;

- (void).cxx_destruct;
- (id)init;

@end
