/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosIntelligence.framework/PhotosIntelligence
 */

@interface PhotosIntelligence.StoryStatistics : _TtCs12_SwiftObject {
    void chapterStatistics;
    void errorStatistics;
    void memoryStatistics;
    void musicStatistics;
    void queryUnderstandingStatistics;
    void traitsStatistics;
}

@end
