/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosIntelligence.framework/PhotosIntelligence
 */

@interface PNWallpaperAlbumSuggestionGenerator : NSObject {
    void albumLocalIdentifier;
    void assetCollection;
    void photoLibrary;
    void suggestionContext;
    void suggestionSubtype;
}

+ (id)cloudIdentifierForShuffleUserAlbumWithAssetCollection:(id)arg1 photoLibrary:(id)arg2;
+ (id)shuffleUserAlbumForCloudIdentifier:(id)arg1 photoLibrary:(id)arg2;

- (void).cxx_destruct;
- (id)assetsForDate:(id)arg1 numberOfAssets:(long long)arg2;
- (id)init;
- (id)initWithAssetCollection:(id)arg1 photoLibrary:(id)arg2;
- (id)updateSuggestionsForDate:(id)arg1 numberOfSuggestions:(long long)arg2;

@end
