/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ManagedSettingsObjC.framework/ManagedSettingsObjC
 */

@interface MONewsSettingsGroup : MOSettingsGroup

@property (nonatomic, retain) NSNumber *denyNews;

+ (id)denyNewsMetadata;
+ (id)groupName;

- (id)denyNews;
- (void)setDenyNews:(id)arg1;

@end
