/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
 */

@interface CPLayoutMaker : NSObject

- (bool)column:(id)arg1 fits:(id)arg2;
- (void)makeLayouts:(id)arg1 from:(id)arg2;

@end
