/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TypistFramework.framework/TypistFramework
 */

@interface TypistKeyboardPunjabi : TypistKeyboard

- (id)addAccentKeyAction:(id)arg1;
- (id)getPostfixKey:(id)arg1;
- (id)init:(id)arg1 options:(id)arg2;

@end
