/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ImagePlayground.framework/ImagePlayground
 */

@interface ImagePlayground.CuratedPromptsEmbeddingStorageManager : _TtCs12_SwiftObject {
    void dbClient;
}

@end
