/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ImagePlayground.framework/ImagePlayground
 */

@interface ImagePlayground.MagicViewModel : _TtCs12_SwiftObject {
    void $__lazy_storage_$_animatedEffectsViewModel;
    void $__lazy_storage_$_creationContextFactory;
    void $__lazy_storage_$_descriptionFieldWithSuggestionsViewModel;
    void $__lazy_storage_$_errorViewModel;
    void $__lazy_storage_$_floatingbubblesViewModel;
    void $__lazy_storage_$_imageConditioningRepresentationsManager;
    void $__lazy_storage_$_magicButtonsBarViewModel;
    void $__lazy_storage_$_previewsViewModel;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _$observationRegistrar;
    void _adjustedState;
    void _canDismissDescriptionFieldWithSuggestions;
    void _creationViewStyle;
    void _currentHittedLimitation;
    void _currentLocalizedGenerationUpscalingError;
    void _currentlyUpscalingInBackground;
    void _didAppear;
    void _isBottomViewVisible;
    void _isCoachingTextViewVisible;
    void _isFloatingBubblesViewVisible;
    void _isLoadingRecipe;
    void _isMagicEditDebugViewVisible;
    void _latestEffectViewSize;
    void _loadRecipeTask;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _onBoardingDescription;
    void _pendingDisclosures;
    void _previewsSavedInBackground;
    void _representations;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _selectedPerson;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _selectedStyle;
    void _shouldShowPersonalizationSheet;
    void _state;
    void context;
    void delegate;
    void imageGenerationManager;
    void lastRepresentationsDidContainAPerson;
    void magicViewFullHeightForKeyboardScrolling;
    void magicViewTextFieldFrame;
    void magicViewTopButtonsFrame;
    void previewsStore;
    void servicesFetcher;
    void sessionUndoManager;
}

@end
