/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ImagePlayground.framework/ImagePlayground
 */

@interface ImagePlayground.GPServiceSideExportedObject : _TtCs12_SwiftObject <ImagePlayground.GPServiceProtocol> {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _image;
    void _promptElements;
    void _recipeData;
    void composingViewModel;
    void extensionState;
    void playgroundHomeViewModel;
}

- (void)didFinishServiceConfiguration;
- (void)setIsLoadingRecipe:(bool)arg1;
- (void)setPromptElements:(id)arg1;
- (void)setRecipeData:(id)arg1;
- (void)setSourceImage:(id)arg1;
- (void)startUpscaling;
- (void)willBeginServiceConfiguration;

@end
