/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/LockedCameraCapture.framework/LockedCameraCapture
 */

@interface LockedCameraCapture.LockedCameraCaptureSession : _TtCs12_SwiftObject {
    void _secureCaptureSession;
}

@end
