/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.DebugFormatConsoleAnimator : _TtCs12_SwiftObject {
    void editor;
    void isDirty;
    void viewController;
}

@end
