/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FeedSponsorshipAdReferenceService : _TtCs12_SwiftObject {
    void feedSponsorshipAdService;
    void tagService;
}

@end
