/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.SharingActivityItemFactory : _TtCs12_SwiftObject {
    void commandCenter;
    void puzzleDifficultyDescriptionProvider;
    void puzzleRankProvider;
    void shareLinkImageProvider;
    void shareLinkProvider;
    void shareLinkPuzzleImageProvider;
    void shareLinkTextProvider;
}

@end
