/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.PuzzleStatsProcessor : _TtCs12_SwiftObject {
    void puzzlePlayStateProvider;
}

@end
