/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.ResetPuzzleProgressCommandHandler : _TtCs12_SwiftObject {
    void historyService;
}

@end
