/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosSwiftUICore.framework/PhotosSwiftUICore
 */

@interface PhotosSwiftUICore.PhotosEventCellFactory : _TtCs12_SwiftObject {
    void colorFactory;
}

@end
