/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PosterBoardUIServices.framework/PosterBoardUIServices
 */

@interface PRUISInlinePosterEditingViewController : UIViewController <PRUISExternallyHostedPosterEditingServiceDelegate, PRUISInlinePosterEditingPlaceholderViewControllerDelegate, PRUISModalRemoteViewControllerDelegate> {
    <PRUISInlinePosterEditingViewControllerDelegate> * _delegate;
    FBSDisplayConfiguration * _displayConfiguration;
    <PRUISModalEntryPoint> * _entryPoint;
    PRUISModalRemoteViewController * _fallbackViewController;
    <PRUISExternallyHostedPosterEditingRequest> * _remoteEditingRequest;
    PRUISExternallyHostedPosterEditingService * _remoteEditingService;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (nonatomic) <PRUISInlinePosterEditingViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) FBSDisplayConfiguration *displayConfiguration;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_getEditingViewControllerIfPossible;
- (bool)_isPresentingRemoteOrLocalEditingUI;
- (void)_shared_didDismissWithResponse:(id)arg1;
- (void)_shared_willDismissWithResponse:(id)arg1;
- (id)delegate;
- (void)didEndEditingWithResponse:(id)arg1;
- (id)displayConfiguration;
- (id)initWithEntryPoint:(id)arg1;
- (void)modalRemoteViewController:(id)arg1 didDismissWithResponse:(id)arg2;
- (void)modalRemoteViewController:(id)arg1 willDismissWithResponse:(id)arg2;
- (void)placeholderViewController:(id)arg1 requestsDismissalWithAnimation:(bool)arg2;
- (long long)preferredStatusBarStyle;
- (long long)preferredStatusBarUpdateAnimation;
- (bool)prefersStatusBarHidden;
- (void)sendRequestDismissalAction;
- (void)setDelegate:(id)arg1;
- (void)setDisplayConfiguration:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)willEndEditingWithResponse:(id)arg1;

@end
