/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
 */

@interface WBSApplicationManifestFetcher : NSObject {
    NSArray * _completionHandlers;
    _WKApplicationManifest * _manifest;
    long long  _state;
    WKWebView * _webView;
}

+ (double)_longestEdgeForIcon:(id)arg1;
+ (long long)_preferredPurposeForIcons:(id)arg1;
+ (long long)_primaryPurposeForPurposes:(id)arg1;
+ (void)downloadImagesForManifest:(id)arg1 linkIconParameters:(id)arg2 usingWebView:(id)arg3 withCompletionHandler:(id /* block */)arg4;

- (void).cxx_destruct;
- (void)getApplicationManifestWithCompletionHandler:(id /* block */)arg1;
- (id)initWithWebView:(id)arg1;

@end
