/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
 */

@interface WBSWindowEntity : NSObject {
    NSString * _identifier;
    bool  _isPrivate;
    NSString * _title;
}

@property (nonatomic, readonly, copy) NSString *identifier;
@property (nonatomic, readonly) bool isPrivate;
@property (nonatomic, readonly, copy) NSString *title;

- (void).cxx_destruct;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1 title:(id)arg2 isPrivate:(bool)arg3;
- (bool)isPrivate;
- (id)title;

@end
