/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StocksPersonalization.framework/StocksPersonalization
 */

@interface StocksPersonalization.StocksTabiScoringContextEventProcessor : _TtGC4Tabi18WorkEventProcessorV21StocksPersonalization28StocksTabiArticleScoringWork_ <FCOperationThrottlerDelegate> {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  scoringContext;
    void scoringContextQueue;
    void scoringContextThrottler;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  scoringContextURL;
}

- (void).cxx_destruct;
- (id)init;
- (void)operationThrottler:(id)arg1 performAsyncOperationWithCompletion:(id /* block */)arg2;

@end
