/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HumanUI.framework/HumanUI
 */

@interface HumanUI.RendererMesh : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _skeletons;
}

@end
