/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PassKitUI.LegacyHeadUnitPairingFlowItem : NSObject <CARSetupHeadUnitPairingPromptDelegate> {
    void context;
    void delegate;
    void hupPrompt;
    void identifier;
    void presentationConfiguration;
}

- (void).cxx_destruct;
- (void)headUnitPairingPrompt:(id)arg1 didFinishWithResult:(bool)arg2;
- (id)init;

@end
