/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PassKitUI.ProvisioningManateeSetupFlowItem : NSObject {
    void context;
    void delegate;
    void dismissalConfiguration;
    void feature;
    void identifier;
    void isRequirementOptional;
    void promptedUserToUpgrade;
    void reporter;
    void requirements;
    void securityController;
}

- (void).cxx_destruct;
- (id)init;

@end
