/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKAddPassesAboutWalletViewController : UIViewController {
    UIButton * _doneButton;
    UILabel * _firstBodyLabel;
    UIImageView * _imageView;
    UIScrollView * _scrollView;
    UILabel * _secondBodyLabel;
    UIStackView * _stackView;
    UILabel * _subtitleLabel;
    UILabel * _titleLabel;
}

- (void).cxx_destruct;
- (void)_closeButtonPressed:(id)arg1;
- (void)_setUpConstraints;
- (void)_setUpDoneButton;
- (void)_setUpDoneButtonConstraints;
- (void)_setUpFirstBodyLabel;
- (void)_setUpImageView;
- (void)_setUpImageViewConstraints;
- (void)_setUpScrollView;
- (void)_setUpScrollViewConstraints;
- (void)_setUpSecondBodyLabel;
- (void)_setUpStackView;
- (void)_setUpStackViewConstraints;
- (void)_setUpSubtitleLabel;
- (void)_setUpTitleLabel;
- (void)_setUpView;
- (void)_setUpViews;
- (id)amendLabel:(id)arg1;
- (void)dismissViewController;
- (void)viewDidLoad;

@end
