/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKBannerPresentable : NSObject <BNHostedContentProviding, BNPresentable, PKBannerViewControllerPresentable, SBUISystemApertureElementProviding> {
    id /* block */  _didFinishHandler;
    id /* block */  _didStartHandler;
    id /* block */  _factory;
    PKBannerPresentationManager * _manager;
    bool  _needsRevoke;
    bool  _posted;
    <BNPresentableContext> * _presentableContext;
    NSString * _requestIdentifier;
    bool  _revoked;
    UIViewController<PKBannerViewController><BNPresentableObserving><SBUISystemApertureElement> * _viewController;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (getter=isDraggingDismissalEnabled, nonatomic, readonly) bool draggingDismissalEnabled; /* unknown property attribute: ? */
@property (getter=isDraggingInteractionEnabled, nonatomic, readonly) bool draggingInteractionEnabled; /* unknown property attribute: ? */
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSSet *preferredBackgroundActivitiesToSuppress; /* unknown property attribute: ? */
@property (nonatomic, readonly) long long presentableBehavior; /* unknown property attribute: ? */
@property (nonatomic) <BNPresentableContext> *presentableContext; /* unknown property attribute: ? */
@property (nonatomic, readonly) long long presentableType; /* unknown property attribute: ? */
@property (nonatomic, readonly) bool providesHostedContent;
@property (nonatomic, readonly, copy) NSString *requestIdentifier;
@property (nonatomic, readonly, copy) NSString *requesterIdentifier;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <SBUISystemApertureElement> *systemApertureElement; /* unknown property attribute: ? */
@property (nonatomic, readonly) UIViewController<SBUISystemApertureElement> *systemApertureElementViewController;
@property (getter=isTouchOutsideDismissalEnabled, nonatomic, readonly) bool touchOutsideDismissalEnabled; /* unknown property attribute: ? */
@property (nonatomic, readonly) UIViewController *viewController; /* unknown property attribute: ? */

- (void).cxx_destruct;
- (id)init;
- (bool)isDraggingInteractionEnabled;
- (id)presentableContext;
- (void)presentableDidAppearAsBanner:(id)arg1;
- (void)presentableDidDisappearAsBanner:(id)arg1 withReason:(id)arg2;
- (void)presentableWillAppearAsBanner:(id)arg1;
- (void)presentableWillDisappearAsBanner:(id)arg1 withReason:(id)arg2;
- (void)presentableWillNotAppearAsBanner:(id)arg1 withReason:(id)arg2;
- (bool)providesHostedContent;
- (id)requestIdentifier;
- (id)requesterIdentifier;
- (void)revoke;
- (void)setPresentableContext:(id)arg1;
- (id)systemApertureElementViewController;
- (void)userInteractionDidEndForBannerForPresentable:(id)arg1;
- (void)userInteractionWillBeginForBannerForPresentable:(id)arg1;
- (id)viewController;

@end
