/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPeerPaymentRecurringPaymentAmountDetailRowItem : PKPeerPaymentRecurringPaymentDetailRowItem {
    PKCurrencyAmount * _currencyAmount;
    NSString * _title;
}

@property (nonatomic, retain) PKCurrencyAmount *currencyAmount;
@property (nonatomic, retain) NSString *title;

- (void).cxx_destruct;
- (id)currencyAmount;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)setCurrencyAmount:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
