/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/LocalAuthenticationEmbeddedUI.framework/LocalAuthenticationEmbeddedUI
 */

@interface LAPSPasscodeChangeAuthorizerDTOAdapter : NSObject <LAPSPasscodeChangeAuthorizer> {
    LAPSPasscodeChangeAuthorizationOptions * _options;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_authorizeOperationWithIdentifier:(id)arg1 options:(id)arg2 completion:(id /* block */)arg3;
- (void)_authorizePasscodeChangeWithCompletion:(id /* block */)arg1;
- (void)_authorizePasscodeRecoveryWithCompletion:(id /* block */)arg1;
- (void)_authorizePasscodeRemovalWithCompletion:(id /* block */)arg1;
- (void)_authorizePasscodeVerificationWithCompletion:(id /* block */)arg1;
- (void)authorizeWithCompletion:(id /* block */)arg1;
- (id)initWithOptions:(id)arg1;

@end
