/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FinanceKitUI.framework/FinanceKitUI
 */

@interface _TtCV12FinanceKitUI18AddOrderButtonView11Coordinator : NSObject {
    void action;
}

- (void).cxx_destruct;
- (void)callback;
- (id)init;

@end
