/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FinanceKitUI.framework/FinanceKitUI
 */

@interface FinanceKitUI.BankConnectConsentDeletionListener : NSObject <NSFetchedResultsControllerDelegate> {
    void context;
    void fetchController;
    void institutionID;
    void onDeletionOfLastConsent;
}

- (void).cxx_destruct;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (id)init;

@end
