/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/FinanceKitUI.framework/FinanceKitUI
 */

@interface FinanceKitUI.AccountStartDateModel : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _$observationRegistrar;
    void _sharingStartDate;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  account;
}

@end
