/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionButtonSelector.framework/ActionButtonSelector
 */

@interface ABAntialiasedImageView : UIImageView

+ (Class)layerClass;

@end
