/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthBalanceDaemon.framework/HealthBalanceDaemon
 */

@interface HealthBalanceDaemon.EWMABaselineCalculator : _TtCs12_SwiftObject {
    void activityType;
    void acuteBaselines;
    void acuteFactor;
    void chronicBaselineThreshold;
    void chronicBaselines;
    void chronicFactor;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  firstDayWithData;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastDayIndex;
    void results;
}

@end
