/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKitInternal.framework/AppStoreKitInternal
 */

@interface AppStoreKitInternal.TodayCardMediaSingleLockup : AppStoreKitInternal.TodayCardMedia {
    void condensedAdLockupWithIconBackground;
}

@end
