/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriMessagesFlow.framework/SiriMessagesFlow
 */

@interface SiriMessagesFlow.SearchForMessagesAppResolutionOnDeviceFlowStrategy : _TtCs12_SwiftObject {
    void appName;
    void intent;
    void responseProducerType;
}

@end
