/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoKit.framework/ChronoKit
 */

@interface _TtCC9ChronoKit19ChronoMetadataStore12MutableStore : _TtCs12_SwiftObject {
    void configuredWidgetStore;
    void extensionStore;
    void hostStore;
    void publicTokenStore;
    void pushSubscriptionStore;
    void pushTokenStore;
    void remoteActivityArchiveBudgetStore;
    void remoteActivitySubscriptionStore;
    void remoteExtensionsStore;
    void snapshotConfigurationStore;
    void stateReplicatorDeviceMetadataStore;
    void stateReplicatorPairingRelationshipStore;
    void stateReplicatorRecordMetadataStore;
}

@end
