/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosGraph.framework/PhotosGraph
 */

@interface PhotosGraph.SocialGroupsRandom : _TtCs12_SwiftObject {
    void futureLookupResults;
    void priority;
    void supportsFutureLookup;
    void triggerResults;
}

@end
