/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
 */

@interface WBSJSONWriter : NSObject {
    NSFileHandle * _fileHandle;
    unsigned long long  _options;
    NSOutputStream * _outputStream;
    NSMutableArray * _stateStack;
}

@property (nonatomic, readonly) long long currentDepth;
@property (nonatomic, readonly) long long currentEntryKind;
@property (nonatomic, readonly) NSFileHandle *fileHandle;
@property (nonatomic, readonly) unsigned long long options;
@property (nonatomic, readonly) NSOutputStream *outputStream;

+ (void)initialize;

- (void).cxx_destruct;
- (bool)_checkCurrentState:(id)arg1 doesNotContainKey:(id)arg2 error:(id*)arg3;
- (bool)_checkHasNoRootWithError:(id*)arg1;
- (id)_currentEntryStateOfKind:(long long)arg1 error:(id*)arg2;
- (id)_dataForJSONObject:(id)arg1 error:(id*)arg2;
- (id)_prefixStringForCurrentDepth;
- (bool)_writeBuffer:(const char *)arg1 length:(long long)arg2 error:(id*)arg3;
- (bool)_writeCommaIfNeededForState:(id)arg1 error:(id*)arg2;
- (bool)_writeConstantASCIIString:(const char *)arg1 error:(id*)arg2;
- (bool)_writeData:(id)arg1 error:(id*)arg2;
- (bool)_writeObjectKey:(id)arg1 error:(id*)arg2;
- (bool)_writePrettyPrintedData:(id)arg1 forEntry:(id)arg2 error:(id*)arg3;
- (bool)_writeString:(id)arg1 error:(id*)arg2;
- (bool)addEntry:(id)arg1 forKey:(id)arg2 error:(id*)arg3;
- (bool)appendAndBeginArrayWithError:(id*)arg1;
- (bool)appendAndBeginObjectWithError:(id*)arg1;
- (bool)appendEntry:(id)arg1 error:(id*)arg2;
- (bool)beginArrayForKey:(id)arg1 error:(id*)arg2;
- (bool)beginArrayWithError:(id*)arg1;
- (bool)beginObjectForKey:(id)arg1 error:(id*)arg2;
- (bool)beginObjectWithError:(id*)arg1;
- (bool)closeCurrentEntryWithError:(id*)arg1;
- (long long)currentDepth;
- (long long)currentEntryKind;
- (id)fileHandle;
- (bool)finishEncodingWithError:(id*)arg1;
- (id)initWithFileHandle:(id)arg1;
- (id)initWithFileHandle:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithOutputStream:(id)arg1;
- (id)initWithOutputStream:(id)arg1 options:(unsigned long long)arg2;
- (unsigned long long)options;
- (id)outputStream;

@end
