/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkoutCore.framework/WorkoutCore
 */

@interface WorkoutCore.MeanDistributionByTime : _TtCs12_SwiftObject {
    void analyzer;
}

@end
