/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VisualIntelligence.framework/VisualIntelligence
 */

@interface VisualIntelligence.EncryptedSearchLTR : _TtCs12_SwiftObject {
    void model;
}

@end
