/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PrivateFederatedLearning.framework/PrivateFederatedLearning
 */

@interface PrivateFederatedLearning.PFLPluginError : _TtCs12_SwiftObject {
    void rawValue;
}

@end
