/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformLibrary.framework/IntelligencePlatformLibrary
 */

@interface CCAppShortcutEntityContent : CCItemMessage <CCItemContent, CCItemFieldEnumerable, CCJSONDescribing> {
    NSString * _entityInstanceIdentifier;
    NSArray * _entitySynonyms;
    NSString * _entityTitle;
    NSString * _entityTypeIdentifier;
    NSString * _providerClass;
}

@property (nonatomic, readonly) NSString *entityInstanceIdentifier;
@property (nonatomic, readonly) NSArray *entitySynonyms;
@property (nonatomic, readonly) NSString *entityTitle;
@property (nonatomic, readonly) NSString *entityTypeIdentifier;
@property (nonatomic, readonly) NSString *providerClass;

+ (Class)contentMessageClass;
+ (id)descriptionForTypeIdentifier:(unsigned short)arg1;
+ (unsigned short)itemType;
+ (Class)metaContentMessageClass;

- (void).cxx_destruct;
- (id)entityInstanceIdentifier;
- (id)entitySynonyms;
- (id)entityTitle;
- (id)entityTypeIdentifier;
- (void)enumerateFieldsUsingBlock:(id /* block */)arg1 parentFieldType:(unsigned short)arg2;
- (id)initWithEntityTitle:(id)arg1 entityInstanceIdentifier:(id)arg2 entityTypeIdentifier:(id)arg3 providerClass:(id)arg4 entitySynonyms:(id)arg5 error:(id*)arg6;
- (id)initWithEntityTitle:(id)arg1 entityInstanceIdentifier:(id)arg2 entityTypeIdentifier:(id)arg3 providerClass:(id)arg4 error:(id*)arg5;
- (id)initWithJSONDictionary:(id)arg1 error:(id*)arg2;
- (bool)initializeFieldValuesFromData:(id)arg1 error:(id*)arg2;
- (id)jsonDictionary;
- (id)providerClass;

@end
