/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformLibrary.framework/IntelligencePlatformLibrary
 */

@interface CCSerializedSetDevice : CCItemMessage {
    NSString * _deviceIdentifier;
    bool  _hasOptions;
    unsigned int  _options;
}

@property (nonatomic, readonly) NSString *deviceIdentifier;
@property (nonatomic) bool hasOptions;
@property (nonatomic, readonly) unsigned int options;

+ (Class)contentMessageClass;
+ (id)descriptionForTypeIdentifier:(unsigned short)arg1;
+ (unsigned short)itemType;
+ (Class)metaContentMessageClass;

- (void).cxx_destruct;
- (id)deviceIdentifier;
- (void)enumerateFieldsUsingBlock:(id /* block */)arg1 parentFieldType:(unsigned short)arg2;
- (bool)hasOptions;
- (id)initWithDeviceIdentifier:(id)arg1 options:(id)arg2 error:(id*)arg3;
- (id)initWithJSONDictionary:(id)arg1 error:(id*)arg2;
- (bool)initializeFieldValuesFromData:(id)arg1 error:(id*)arg2;
- (id)jsonDictionary;
- (unsigned int)options;
- (void)setHasOptions:(bool)arg1;

@end
