/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PoirotBlocks.framework/PoirotBlocks
 */

@interface _TtCV12PoirotBlocks16BiomeTableConfig29SchematizedBiomeLibraryConfig : _TtCs12_SwiftObject {
    void _schema;
    void _schemaProvider;
    void identifier;
    void requiresPublisher;
    void stream;
    void tableName;
    void useCase;
}

@end
