/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface _BMHomeKitLibraryNode : _BMLibraryNode

+ (id)Client;
+ (id)identifier;
+ (id)streamNames;
+ (id)streamWithName:(id)arg1;
+ (id)sublibraries;
+ (id)validKeyPaths;

@end
