/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface BMFeedbackTextToImageEvaluationData : BMEventBase <BMStoreData> {
    BMEvaluationCommonMetadata * _commonMetadata;
    unsigned int  _dataVersion;
    BMImageContent * _generatedContent;
    BMTextContent * _originalContent;
}

@property (nonatomic, readonly) BMEvaluationCommonMetadata *commonMetadata;
@property (nonatomic, readonly) unsigned int dataVersion;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) BMImageContent *generatedContent;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) BMTextContent *originalContent;
@property (readonly) Class superclass;

+ (id)columns;
+ (id)eventWithData:(id)arg1 dataVersion:(unsigned int)arg2;
+ (unsigned int)latestDataVersion;
+ (id)protoFields;
+ (id)validKeyPaths;

- (void).cxx_destruct;
- (id)commonMetadata;
- (unsigned int)dataVersion;
- (id)description;
- (id)generatedContent;
- (id)initByReadFrom:(id)arg1;
- (id)initWithCommonMetadata:(id)arg1 originalContent:(id)arg2 generatedContent:(id)arg3;
- (id)initWithJSONDictionary:(id)arg1 error:(id*)arg2;
- (bool)isEqual:(id)arg1;
- (id)jsonDictionary;
- (id)originalContent;
- (id)serialize;
- (void)writeTo:(id)arg1;

@end
