/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface BMSafariWindowProxy : BMEventBase <BMStoreData> {
    bool  _accessedPropertyDirectly;
    unsigned int  _dataVersion;
    NSString * _domain;
    bool  _hasAccessedPropertyDirectly;
    bool  _hasRaw_visited;
    NSString * _openedDomain;
    int  _property;
    double  _raw_visited;
}

@property (nonatomic, readonly) bool accessedPropertyDirectly;
@property (nonatomic, readonly) unsigned int dataVersion;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSString *domain;
@property (nonatomic) bool hasAccessedPropertyDirectly;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *openedDomain;
@property (nonatomic, readonly) int property;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSDate *visited;

+ (id)columns;
+ (id)eventWithData:(id)arg1 dataVersion:(unsigned int)arg2;
+ (unsigned int)latestDataVersion;
+ (id)protoFields;
+ (id)validKeyPaths;

- (void).cxx_destruct;
- (bool)accessedPropertyDirectly;
- (unsigned int)dataVersion;
- (id)description;
- (id)domain;
- (bool)hasAccessedPropertyDirectly;
- (id)initByReadFrom:(id)arg1;
- (id)initWithDomain:(id)arg1 openedDomain:(id)arg2 visited:(id)arg3 property:(int)arg4 accessedPropertyDirectly:(id)arg5;
- (id)initWithJSONDictionary:(id)arg1 error:(id*)arg2;
- (bool)isEqual:(id)arg1;
- (id)jsonDictionary;
- (id)openedDomain;
- (int)property;
- (id)serialize;
- (void)setHasAccessedPropertyDirectly:(bool)arg1;
- (id)visited;
- (void)writeTo:(id)arg1;

@end
