/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeLibrary.framework/BiomeLibrary
 */

@interface BMUserFocusInferredMode_v1 : BMUserFocusInferredMode

- (int)modeType;
- (int)origin;

@end
