/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OmniSearch.framework/OmniSearch
 */

@interface OmniSearch.LocalSearchManager : SwiftNativeNSObject <SPQueryTaskDelegate> {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  continuation;
    void queryTask;
    void sections;
    void session;
}

- (void)didReceiveResponse:(id)arg1;
- (id)init;
- (void)resultsDidBecomeInvalid:(id)arg1;

@end
