/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVOX.framework/SiriVOX
 */

@interface SVXAnnouncer : NSObject {
    NSHashTable * _listeners;
    struct __CFDictionary { } * _protocolOptionalInstanceMethodSignaturesBySelector;
    struct __CFDictionary { } * _protocolRequiredInstanceMethodSignaturesBySelector;
}

@property (nonatomic, retain) NSHashTable *listeners;
@property (nonatomic) struct __CFDictionary { }*protocolOptionalInstanceMethodSignaturesBySelector;
@property (nonatomic) struct __CFDictionary { }*protocolRequiredInstanceMethodSignaturesBySelector;

+ (id)protocol;

- (void).cxx_destruct;
- (void)_accessListenersUsingBlock:(id /* block */)arg1;
- (void)addListener:(id)arg1;
- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (id)init;
- (id)listeners;
- (id)methodSignatureForSelector:(SEL)arg1;
- (struct __CFDictionary { }*)protocolOptionalInstanceMethodSignaturesBySelector;
- (struct __CFDictionary { }*)protocolRequiredInstanceMethodSignaturesBySelector;
- (void)removeAllListeners;
- (void)removeListener:(id)arg1;
- (bool)respondsToSelector:(SEL)arg1;
- (void)setListeners:(id)arg1;
- (void)setProtocolOptionalInstanceMethodSignaturesBySelector:(struct __CFDictionary { }*)arg1;
- (void)setProtocolRequiredInstanceMethodSignaturesBySelector:(struct __CFDictionary { }*)arg1;

@end
