/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVOX.framework/SiriVOX
 */

@interface SVXSpeechSynthesisConfigurationStateManager : NSObject {
    <SVXClientAudioSystemServicing> * _clientAudioSystemServicing;
    SVXSpeechSynthesisConfiguration * _currentConfiguration;
}

@property (nonatomic, retain) <SVXClientAudioSystemServicing> *clientAudioSystemServicing;
@property (nonatomic, readonly) SVXSpeechSynthesisConfiguration *currentConfiguration;

- (void).cxx_destruct;
- (id)clientAudioSystemServicing;
- (id)currentConfiguration;
- (void)setClientAudioSystemServicing:(id)arg1;
- (bool)updateConfiguration:(id)arg1;

@end
