/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVOX.framework/SiriVOX
 */

@interface SVXSpeechSynthesisResultConverter : NSObject

- (id)toServiceCommandResult:(id)arg1;

@end
