/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PIInpaintCombinedMaskNode : NURenderNode

@property (nonatomic, readonly) unsigned long long mode;

- (id)_evaluateImage:(out id*)arg1;
- (id)_evaluateImageGeometry:(out id*)arg1;
- (id)_evaluateImageProperties:(out id*)arg1;
- (id)_scaleImage:(id)arg1 toSize:(struct CGSize { double x1; double x2; })arg2;
- (id)initWithSettings:(id)arg1 inputs:(id)arg2;
- (id)initWithSettings:(id)arg1 inputs:(id)arg2 mode:(unsigned long long)arg3;
- (id)inputNode;
- (id)maskImageForIdentifier:(id)arg1 error:(out id*)arg2;
- (unsigned long long)mode;
- (id)resolvedNodeWithCachedInputs:(id)arg1 settings:(id)arg2 pipelineState:(id)arg3 error:(out id*)arg4;
- (bool)shouldCacheNodeForPipelineState:(id)arg1;

@end
