/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcuts.framework/VoiceShortcuts
 */

@interface VoiceShortcuts.ToolKitHighPriorityDeferredDeltaIndexingTask : _TtCs12_SwiftObject

@end
