/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcuts.framework/VoiceShortcuts
 */

@interface VoiceShortcuts.ToolKitCascadeSyncEngine : _TtCs12_SwiftObject {
    void cascadeQueue;
    void setChangeListener;
    void syncingQueue;
}

- (void)handleToolKitDatabaseChangedNotificationWithNotification:(id)arg1;

@end
