/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNContactPickerServiceViewController : CNContactPickerContentViewController <CNContactPickerContentDelegate>

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)_filteredContact:(id)arg1 withKeys:(id)arg2;
- (id)_filteredProperty:(id)arg1;
- (void)_logPrivacyAccountingAccessEvent;
- (void)_logPrivateAccessEventForContactPickerUsage;
- (id)init;
- (void)pickerDidCancel;
- (void)pickerDidCompleteWithNewContact:(id)arg1;
- (void)pickerDidSelectAddNewContact;
- (void)pickerDidSelectContact:(id)arg1 property:(id)arg2;
- (void)pickerDidSelectContacts:(id)arg1 properties:(id)arg2;
- (bool)shouldRecordPrivateAccessToAggregator;
- (void)viewDidAppear:(bool)arg1;

@end
