/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface ContactsButtonSlotTraits : NSObject <NSCopying, NSSecureCoding> {
    void avatarBGColor;
    void bgColor;
    void captionTextField;
    void contentSizeCategory;
    void displayScale;
    void fgColor;
    void font;
    void hostAppBundlePath;
    void tintColor;
    void trailingEdgeFromAvatar;
    void widthOfAvatar;
}

@property (nonatomic, readonly) NSString *debugDescription;

+ (void)setSupportsSecureCoding:(bool)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(void*)arg1;
- (id)debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end
