/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
 */

@interface CSDateTag : CSNumericAnalysisTag {
    NSDate * _date;
}

@property (nonatomic, readonly) NSDate *date;

- (void).cxx_destruct;
- (id)date;
- (void)encodeWithCSCoder:(id)arg1;
- (id)initWithDate:(id)arg1 confidence:(double)arg2;

@end
