/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherUI.framework/WeatherUI
 */

@interface WeatherUI.SunriseSunsetViewModelFactory : _TtCs12_SwiftObject {
    void stringBuilder;
    void sunriseSunsetEventCalculator;
}

@end
