/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Blackbeard.framework/Blackbeard
 */

@interface Blackbeard.MetricAccountEventDetour : _TtCs12_SwiftObject {
    void eventHub;
    void platform;
}

@end
