/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface _PXPhotosLayoutWithSectionHeadersSpec : PXPhotosLayoutSpec {
    PXPhotosSectionHeaderLayoutSpec * _sectionHeaderSpec;
}

- (void).cxx_destruct;
- (id)initWithExtendedTraitCollection:(id)arg1 options:(unsigned long long)arg2 gridStyle:(long long)arg3 wantsToggleSidebarButton:(bool)arg4 shouldMakeSpaceForLeadingChrome:(bool)arg5;
- (id)sectionHeaderSpec;

@end
