/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PhotosUICore.LemonadeActiveSearchUpdater : _TtCs12_SwiftObject {
    void currentActiveSearch;
    void pendingUpdateForContainer;
    void pendingUpdateForIsEditing;
    void pendingUpdateForSearchText;
}

@end
