/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PhotosUICore.PhotosLaunchScheduler : _TtCs12_SwiftObject {
    void loadTimeout;
    void priorityOrder;
    void queue;
    void queue_features;
}

@end
