/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGNamedImageViewConfiguration : NSObject <NSCopying> {
    NSBundle * _bundle;
    long long  _contentMode;
    NSString * _imageName;
}

@property (nonatomic, retain) NSBundle *bundle;
@property (nonatomic) long long contentMode;
@property (nonatomic, copy) NSString *imageName;

- (void).cxx_destruct;
- (id)bundle;
- (long long)contentMode;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)hash;
- (id)imageName;
- (id)initWithImageName:(id)arg1 contentMode:(long long)arg2 bundle:(id)arg3;
- (bool)isEqual:(id)arg1;
- (void)setBundle:(id)arg1;
- (void)setContentMode:(long long)arg1;
- (void)setImageName:(id)arg1;

@end
