/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXLemonadeCollectionCustomizationFoldersFactory : NSObject

+ (id)foldersCustomizationViewControllerWithRootCollectionList:(id)arg1;

- (id)init;

@end
