/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXSKCloudServiceSetupMessageIdentifier : NSObject

+ (id)addMusic;
+ (id)connect;
+ (id)join;
+ (id)playMusic;

@end
