/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceActions.framework/VoiceActions
 */

@interface VoiceActions.VAKeywordSpottedEvent : NSObject {
    void audioBytes;
    void hostTime;
    void intervalFromEndOfSpeech;
    void keyword;
    void score;
    void silenceAfter;
    void silenceBefore;
    void speechDuring;
}

- (void).cxx_destruct;
- (id)init;

@end
