/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceActions.framework/VoiceActions
 */

@interface VoiceActions.VAAVSAudioEncoderModel : VoiceActions.VAAudioEncoderModel {
    void audioBufferMaxSamples;
    void audioEncModel;
    void bufferDurationSeconds;
    void embeddingMaxFrames;
    void embeddingRate;
    void featureBuffer;
    void featureExtractor;
    void frameCount;
    void modelHopSize;
    void modelWindowSize;
    void sampleRate;
}

@end
