/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PrivateSearchCore.framework/PrivateSearchCore
 */

@interface PrivateSearchCore.CallContextImpl : _TtCs12_SwiftObject {
    void clientContext;
}

@end
