/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PrivateSearchCore.framework/PrivateSearchCore
 */

@interface PrivateSearchCore.InMemoryStore : _TtCs12_SwiftObject {
    void bitArrays;
    void queue;
}

@end
