/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenSharingAccessibilityService.framework/ScreenSharingAccessibilityService
 */

@interface ScreenSharingAccessibilityService.ScreenSharingAnnotationDisplayManager : _TtCs12_SwiftObject {
    void $__lazy_storage_$_displayManager;
    void viewController;
}

@end
