/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIAlertControllerInteractionController : UIPercentDrivenInteractiveTransition <UIForceInteractionController, UIInteractionProgressObserver> {
    UIAlertController * _alertController;
    <UIViewControllerContextTransitioning> * _context;
}

@property (nonatomic, retain) UIAlertController *alertController;
@property (nonatomic, readonly) long long completionCurve; /* unknown property attribute: ? */
@property (nonatomic, readonly) double completionSpeed; /* unknown property attribute: ? */
@property (nonatomic, retain) <UIViewControllerContextTransitioning> *context;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool wantsInteractiveStart; /* unknown property attribute: ? */

- (void).cxx_destruct;
- (id)alertController;
- (id)context;
- (void)interactionProgress:(id)arg1 didEnd:(bool)arg2;
- (void)interactionProgressDidUpdate:(id)arg1;
- (void)setAlertController:(id)arg1;
- (void)setContext:(id)arg1;
- (void)startInteractiveTransition:(id)arg1;

@end
