/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIUpdateLinkTrackingScene : _UIUpdateLinkTracking {
    bool  _sceneForeground;
}

- (bool)_canEngage;
- (void)_sceneEnterForeground;
- (void)_sceneExitForeground;

@end
