/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIWTCUnderlineDrawingView : UIView {
    UIColor * _color;
    UIBezierPath * _path;
}

@property (nonatomic, retain) UIColor *color;
@property (nonatomic, retain) UIBezierPath *path;

- (void).cxx_destruct;
- (id)color;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)path;
- (void)setColor:(id)arg1;
- (void)setPath:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
