/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIDocumentViewControllerLaunchOptions : NSObject <_UIDocumentLandingPresenter, _UIDocumentLandingPresenterDefaultDocumentCreating> {
    UIDocumentViewController * __documentViewController;
    UIBackgroundConfiguration * _background;
    UIView * _backgroundAccessoryView;
    UIDocumentBrowserViewController * _browserViewController;
    NSURL * _createdDocumentURL;
    UIDocumentBrowserViewController * _defaultBrowserViewController;
    NSString * _documentCreationIntent;
    UIView * _documentTargetView;
    NSURL * _documentURL;
    struct { 
        unsigned int isCreatingDocument : 1; 
        unsigned int hasUpdatedDocumentTargetView : 1; 
    }  _flags;
    UIView * _foregroundAccessoryView;
    UIAction * _primaryAction;
    UIAction * _secondaryAction;
    UIMenu * _secondaryMenu;
    NSString * _title;
}

@property (setter=_setSecondaryMenu:, nonatomic, copy) UIMenu *_secondaryMenu;
@property (nonatomic, retain) UIBackgroundConfiguration *background;
@property (nonatomic, retain) UIView *backgroundAccessoryView;
@property (nonatomic, retain) UIDocumentBrowserViewController *browserViewController;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIView *documentTargetView;
@property (nonatomic, retain) UIView *foregroundAccessoryView;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) UIAction *primaryAction;
@property (nonatomic, copy) UIAction *secondaryAction;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;

+ (id)createDocumentActionWithIntent:(id)arg1;

- (void).cxx_destruct;
- (void)_dismissBrowserViewController;
- (void)_prepareBrowserViewController:(id)arg1;
- (void)_presentAlertForDocumentAtURL:(id)arg1 error:(id)arg2 isImport:(bool)arg3;
- (void)_replaceDocumentWithDocumentAtURL:(id)arg1 isImport:(bool)arg2;
- (id)_secondaryMenu;
- (void)_setNeedsUpdateDocumentUnavailableConfiguration;
- (void)_setSecondaryMenu:(id)arg1;
- (id)background;
- (id)backgroundAccessoryView;
- (id)browserViewController;
- (void)documentLandingBrowser:(id)arg1 didImportDocumentAtURL:(id)arg2 toDestinationURL:(id)arg3;
- (void)documentLandingBrowser:(id)arg1 didPickDocumentsAtURLs:(id)arg2;
- (void)documentLandingBrowser:(id)arg1 didRequestDocumentCreationWithHandler:(id /* block */)arg2;
- (void)documentLandingBrowser:(id)arg1 failedToImportDocumentAtURL:(id)arg2 error:(id)arg3;
- (void)documentLandingBrowserDidEndDocumentCreation:(id)arg1 importedURL:(id)arg2 canceled:(bool)arg3 error:(id)arg4;
- (void)documentLandingBrowserWillStartDocumentCreation:(id)arg1;
- (id)documentTargetView;
- (id)foregroundAccessoryView;
- (id)init;
- (id)primaryAction;
- (id)secondaryAction;
- (void)setBackground:(id)arg1;
- (void)setBackgroundAccessoryView:(id)arg1;
- (void)setBrowserViewController:(id)arg1;
- (void)setDocumentTargetView:(id)arg1;
- (void)setForegroundAccessoryView:(id)arg1;
- (void)setPrimaryAction:(id)arg1;
- (void)setSecondaryAction:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
