/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIEmojiAndStickerCollectionViewConfiguration : NSObject {
    UITextInputTraits * _textInputTraits;
}

@property (nonatomic, retain) UITextInputTraits *textInputTraits;

- (void).cxx_destruct;
- (void)setTextInputTraits:(id)arg1;
- (id)textInputTraits;

@end
