/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITabGroup : UITab <_UITabGroup> {
    bool  _allowsReordering;
    NSArray * _children;
    NSString * _defaultChildIdentifier;
    NSArray * _displayOrder;
    NSArray * _displayOrderIdentifiers;
    bool  _isUpdatingManagedNavigationController;
    UINavigationController * _managingNavigationController;
    UITab * _selectedChild;
    NSArray * _sidebarActions;
    unsigned long long  _sidebarAppearance;
    <UITraitChangeRegistration> * _sizeClassTraitRegistration;
}

@property (nonatomic) bool allowsReordering;
@property (nonatomic, copy) NSArray *children;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (nonatomic, copy) NSString *defaultChildIdentifier;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSArray *displayOrder;
@property (nonatomic, copy) NSArray *displayOrderIdentifiers;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UINavigationController *managingNavigationController;
@property (nonatomic, retain) UITab *selectedChild;
@property (nonatomic, copy) NSArray *sidebarActions;
@property (nonatomic) unsigned long long sidebarAppearance;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_canBeReordered;
- (bool)_canReorderChild:(id)arg1;
- (id)_defaultChildForSelection;
- (void)_didChangeTabModel:(id)arg1;
- (id)_displayedViewController;
- (void)_elementsDidChange;
- (id)_existingDisplayedViewController;
- (id)_filteredDisplayOrderIdentifiers;
- (void)_invalidateDisplayOrder;
- (bool)_isCustomizable;
- (bool)_isGroup;
- (id)_orderedChildrenForDisplayOrder:(id)arg1;
- (void)_performWithoutUpdatingManagingNavigationController:(id /* block */)arg1;
- (void)_registerManagingNavigationTraitsIfNeeded;
- (void)_selectElement:(id)arg1 notifyOnReselection:(bool)arg2 performBeforeNotifyingDelegate:(id /* block */)arg3;
- (void)_selectedElementDidChange;
- (id)_selectedTabHierarchy;
- (bool)_setDisplayOrderIdentifiers:(id)arg1;
- (void)_updateDescriptionWithBuilder:(id)arg1 recursive:(bool)arg2;
- (void)_updateForManagingNavigationStackChange;
- (void)_updateManagingNavigationStackFromTraitUpdate;
- (void)_updateManagingNavigationStackUsingTransition:(unsigned long long)arg1;
- (void)_updateManagingNavigationStackUsingTransition:(unsigned long long)arg1 isExplicit:(bool)arg2;
- (void)_validateSelectedElement;
- (bool)allowsReordering;
- (id)children;
- (id)defaultChildIdentifier;
- (id)displayOrder;
- (id)displayOrderIdentifiers;
- (id)initWithTitle:(id)arg1 image:(id)arg2 identifier:(id)arg3 children:(id)arg4 viewControllerProvider:(id /* block */)arg5;
- (id)initWithTitle:(id)arg1 image:(id)arg2 identifier:(id)arg3 viewControllerProvider:(id /* block */)arg4;
- (id)managingNavigationController;
- (id)managingTabGroup;
- (id)selectedChild;
- (void)setAllowsReordering:(bool)arg1;
- (void)setChildren:(id)arg1;
- (void)setDefaultChildIdentifier:(id)arg1;
- (void)setDisplayOrderIdentifiers:(id)arg1;
- (void)setManagingNavigationController:(id)arg1;
- (void)setSelectedChild:(id)arg1;
- (void)setSidebarActions:(id)arg1;
- (void)setSidebarAppearance:(unsigned long long)arg1;
- (id)sidebarActions;
- (unsigned long long)sidebarAppearance;
- (id)tabForIdentifier:(id)arg1;

@end
