/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UITraitDisplayCornerRadius : NSObject <UICGFloatTraitDefinition, UITraitDefinitionPrivate>

+ (bool)_isPrivate;
+ (bool)affectsColorAppearance;
+ (double)defaultValue;
+ (bool)defaultValueRepresentsUnspecified;
+ (id)identifier;
+ (id)name;

@end
