/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ManagedSettings.framework/ManagedSettings
 */

@interface ManagedSettings.NotificationCenterReceiver : _TtCs12_SwiftObject {
    void name;
    void subscription;
}

@end
