/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HoverTextUI.framework/HoverTextUI
 */

@interface HoverTextUI.AXRuntimeClient : NSObject {
    void _isEnabled;
    void axObserver;
    void currentInputModeDidChange;
    void didReceiveAnnouncement;
    void didReceiveNotification;
    void elementVisualsUpdated;
    void focusedApplicationsDidChange;
    void keyboardWillChangeFrame;
    void keyboardWillHide;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
    void loupeStateChanged;
    void nativeFocusItemDidChange;
    void pasteOccurred;
    void runloop;
    void subscribeToNotifications;
    void updateTypingDisplayMode;
    void valueChanged;
}

- (void).cxx_destruct;
- (id)init;

@end
