/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftXPC.dylib
 */

@interface _TtCV3XPC18XPCReceivedMessage26XPCReceivedMessageMetadata : _TtCs12_SwiftObject {
    void isSync;
    void requiresHandoff;
}

@end
