/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameControllerFoundation.framework/GameControllerFoundation
 */

@interface __IOGCFastPathRoyaReplayClient : __IOGCFastPathClient <GCIUnknownObjC> {
    const struct IOCFPlugInInterfaceStruct { void *x1; int (*x2)(); int (*x3)(); int (*x4)(); unsigned short x5; unsigned short x6; int (*x7)(); int (*x8)(); int (*x9)(); } * _IOCFPlugInVTBL;
    const struct IOGCFastPathClientInterface { void *x1; int (*x2)(); int (*x3)(); int (*x4)(); unsigned short x5; unsigned short x6; unsigned int x7; int (*x8)(); int (*x9)(); int (*x10)(); int (*x11)(); int (*x12)(); int (*x13)(); int (*x14)(); } * _IOGCFastPathClientVTBL;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSDictionary * _propertyTable;
    unsigned long long  _providerID;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (unsigned long long)_cfTypeID;
- (int)queryInterface:(struct { unsigned char x1; unsigned char x2; unsigned char x3; unsigned char x4; unsigned char x5; unsigned char x6; unsigned char x7; unsigned char x8; unsigned char x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned char x13; unsigned char x14; unsigned char x15; unsigned char x16; })arg1 outInterface:(void**)arg2;

@end
