/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameControllerFoundation.framework/GameControllerFoundation
 */

@interface GCIONotificationPort : NSObject {
    NSObject<OS_dispatch_source> * _cancellationSource;
    struct IONotificationPort { } * _port;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)init;
- (id)initWithMainPort:(unsigned int)arg1;
- (id)initWithMainPort:(unsigned int)arg1 queue:(id)arg2;
- (id)initWithMainPort:(unsigned int)arg1 queue:(id)arg2 cancellationHandler:(id /* block */)arg3;
- (id)initWithQueue:(id)arg1;
- (id)redactedDescription;
- (void)setQueue:(id)arg1 cancellationHandler:(id /* block */)arg2;

@end
