/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameControllerFoundation.framework/GameControllerFoundation
 */

@interface IOGCFastPathProxyServer : NSObject {
    NSObject<OS_xpc_object> * _listener;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void).cxx_destruct;
- (void)activate;
- (id)init;
- (id)initWithServerName:(id)arg1;
- (void)invalidate;

@end
