/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceDiscoveryUI.framework/DeviceDiscoveryUI
 */

@interface DDPeoplePickerSceneClientSettings : UIApplicationSceneClientSettings

@property (nonatomic, readonly) NSUUID *connectedDeviceUUID;

- (id)connectedDeviceUUID;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;

@end
