/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAudioInjectionServices : NSObject

+ (id)GetConnectionForDaemon:(int)arg1;
+ (bool)audioInjectionEnabled;
+ (void)connectDeviceWithUUID:(id)arg1 completion:(id /* block */)arg2;
+ (void)connectDeviceWithUUID:(id)arg1 handlingDaemon:(int)arg2 completion:(id /* block */)arg3;
+ (void)createAudioInjectionDeviceWithType:(long long)arg1 deviceName:(id)arg2 deviceID:(id)arg3 productID:(id)arg4 completion:(id /* block */)arg5;
+ (void)createAudioInjectionDeviceWithType:(long long)arg1 deviceName:(id)arg2 deviceID:(id)arg3 productID:(id)arg4 handlingDaemon:(int)arg5 completion:(id /* block */)arg6;
+ (void)disconnectDeviceWithUUID:(id)arg1 completion:(id /* block */)arg2;
+ (void)disconnectDeviceWithUUID:(id)arg1 handlingDaemon:(int)arg2 completion:(id /* block */)arg3;
+ (id)getAudioInjectionXPCConnectionForCoreSpeechD;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 completion:(id /* block */)arg3;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 handlingDaemon:(int)arg3 completion:(id /* block */)arg4;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withNumChannels:(unsigned long long)arg3 completion:(id /* block */)arg4;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withNumChannels:(unsigned long long)arg3 handlingDaemon:(int)arg4 completion:(id /* block */)arg5;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withNumChannels:(unsigned long long)arg3 withUserIntentOptions:(id)arg4 completion:(id /* block */)arg5;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withNumChannels:(unsigned long long)arg3 withUserIntentOptions:(id)arg4 handlingDaemon:(int)arg5 completion:(id /* block */)arg6;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withfadingTimeWindowLength:(unsigned long long)arg3 completion:(id /* block */)arg4;
+ (void)injectAudio:(id)arg1 toDeviceWithUUID:(id)arg2 withfadingTimeWindowLength:(unsigned long long)arg3 handlingDaemon:(int)arg4 completion:(id /* block */)arg5;
+ (void)pingpong:(id)arg1 completion:(id /* block */)arg2;
+ (void)primaryInputDeviceUUIDWithCompletion:(id /* block */)arg1;
+ (void)primaryInputDeviceUUIDWithhandlingDaemon:(int)arg1 WithCompletion:(id /* block */)arg2;
+ (bool)setAudioInjectionMode:(bool)arg1;

@end
