/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestionsIntelligence.framework/SiriSuggestionsIntelligence
 */

@interface _TtCO27SiriSuggestionsIntelligence27SiriSuggestionsIntelligence33SiriSettingsAppIdValidatorFactory : _TtCs12_SwiftObject

@end
