/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HealthUI.AudiogramLongitudinalChartDataSource : HKHealthQueryChartCacheDataSource {
    void analyticsManager;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDisplayType:(id)arg1 healthStore:(id)arg2;
- (id /* block */)mappingFunctionForContext:(id)arg1;
- (id)queriesForRequest:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)queryDescription;
- (bool)supportsChartQueryDataGeneration;

@end
