/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKUIIconUtilties : NSObject

+ (id)appleDeviceIconForHardwareVersion:(id)arg1;

@end
