/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FindMyBluetooth.framework/FindMyBluetooth
 */

@interface FindMyBluetooth.Service : _TtCs12_SwiftObject {
    void autoDiscoverCount;
    void characteristics;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  discoverCharacteristicsContinuation;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  id;
    void owningPeripheral;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  peerPath;
    void underlyingObject;
}

@end
