/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/_StoreKit_SwiftUI.framework/_StoreKit_SwiftUI
 */

@interface _StoreKit_SwiftUI.SubscriptionStoreViewEventConfiguration : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  appearTimestamp;
    void appliesSubscriptionOffer;
    void buttonLabelContent;
    void buttonLabelLayout;
    void controlStyle;
    void didSendAppearEvent;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  disappearTimestamp;
    void displaysPolicies;
    void displaysRedeemCode;
    void displaysRestorePurchases;
    void displaysSignIn;
    void displaysSubscriptionOffer;
    void hasEntitlement;
    void initializer;
    void plansDisplayed;
    void plansRequested;
    void privacyDestinationType;
    void purchaseResult;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  purchaseTimestamp;
    void purchasedPlanIndex;
    void purchasedProductID;
    void tosDestinationType;
    void usesCustomMarketingContent;
    void usesInAppPurchaseCompletion;
    void usesInAppPurchaseOptions;
    void usesInAppPurchaseStart;
    void visibleRelationships;
}

@end
