/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/_StoreKit_SwiftUI.framework/_StoreKit_SwiftUI
 */

@interface _TtC17_StoreKit_SwiftUIP33_50FF1239C03AA9C7A25F8F26DA9F9CBB15ErrorController : UIViewController

- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end
