/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Network.framework/Network
 */

@interface NWURLLoaderTCP : NSObject <NWURLLoader> {
    bool  _TLS;
    bool  _addedTLS;
    bool  _cancelled;
    <NWURLLoaderClient> * _client;
    NWURLSessionTaskConfiguration * _configuration;
    NSObject<OS_nw_connection> * _connection;
    NWURLError * _error;
    NSString * _hostname;
    NSObject<OS_sec_trust> * _peerTrustInternal;
    NSMutableArray * _pendingWork;
    long long  _port;
    NSObject<OS_dispatch_queue> * _queue;
    bool  _ready;
}

@property (nonatomic, readonly) bool allowsWrite;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *multipartMixedReplaceBoundary;
@property (nonatomic, readonly) NSObject<OS_sec_trust> *peerTrust;
@property (nonatomic, readonly) bool requestComplete;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSObject<OS_nw_http_fields> *trailerFields;
@property (nonatomic, readonly) NSObject<OS_nw_connection> *underlyingConnection;

- (void).cxx_destruct;
- (bool)allowsWrite;
- (id)multipartMixedReplaceBoundary;
- (void)notifyRequestCompletion:(id /* block */)arg1;
- (id)peerTrust;
- (void)readDataOfMinimumIncompleteLength:(unsigned long long)arg1 maximumLength:(unsigned long long)arg2 completionHandler:(id /* block */)arg3;
- (void)readResponse:(id /* block */)arg1;
- (bool)requestComplete;
- (void)start:(id /* block */)arg1;
- (void)stop;
- (id)takeCachedResponse;
- (id)trailerFields;
- (id)underlyingConnection;
- (void)updateClient:(id)arg1;
- (void)writeData:(id)arg1 complete:(bool)arg2 completionHandler:(id /* block */)arg3;

@end
