/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/GamePolicy
 */

@interface GamePolicy.GameModeCCUIStatusBundleInfo : NSObject <NSSecureCoding> {
    void bundleIdentifier;
    void executableDisplayName;
    void isAAAGame;
    void isSystemService;
    void state;
    void usedRecently;
}

+ (void)setSupportsSecureCoding:(bool)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithExecutableDisplayName:(id)arg1 bundleIdentifier:(id)arg2 isSystemService:(bool)arg3 isAAAGame:(bool)arg4 usedRecently:(bool)arg5 state:(long long)arg6;

@end
