/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthAppServices.framework/HealthAppServices
 */

@interface HealthAppAnalyticsStore : NSObject <_HKXPCExportable> {
    HKHealthStore * _healthStore;
    HKTaskServerProxyProvider * _proxyProvider;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (void)setUserDidAccept:(bool)arg1 currentAgreement:(id)arg2 completion:(id /* block */)arg3;

- (void).cxx_destruct;
- (void)connectionInvalidated;
- (id)exportedInterface;
- (id)initWithHealthStore:(id)arg1;
- (id)remoteInterface;
- (void)setUserDidAccept:(bool)arg1 agreement:(id)arg2 version:(long long)arg3 completion:(id /* block */)arg4;
- (void)setUserDidAccept:(bool)arg1 currentAgreement:(id)arg2 completion:(id /* block */)arg3;

@end
