/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LighthouseCoreMLFeatureStore.framework/LighthouseCoreMLFeatureStore
 */

@interface LCFFeatureStoreContextId : NSObject

+ (id)getContextId;

@end
