/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PencilKit.framework/PencilKit
 */

@interface PKDrawingOverlayCache : NSObject {
    NSObject<OS_dispatch_queue> * _accessQueue;
    NSCache * _memoryCache;
}

+ (id)sharedCache;

- (void).cxx_destruct;
- (void)clearMemoryCache;
- (id)init;
- (void)overlayDrawingForDrawingUUID:(id)arg1 tintColor:(id)arg2 completion:(id /* block */)arg3;

@end
