/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PencilKit.framework/PencilKit
 */

@interface PKLassoTool : PKTool

- (id)_defaultItemIdentifier;
- (id)_initWithInk:(id)arg1;
- (bool)_isLassoTool;
- (Class)_toolPickerItemClass;
- (id)init;

@end
