/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIDistanceGradientFromRedMask : CIFilter {
    CIImage * inputImage;
    NSNumber * inputMaximumDistance;
}

@property (nonatomic, retain) CIImage *inputImage;
@property (nonatomic, retain) NSNumber *inputMaximumDistance;

+ (id)customAttributes;

- (id)inputImage;
- (id)inputMaximumDistance;
- (id)outputImage;
- (void)setInputImage:(id)arg1;
- (void)setInputMaximumDistance:(id)arg1;

@end
