/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TranslationDaemon.framework/TranslationDaemon
 */

@interface FTMutableTTSWordPhonemes : FTTTSWordPhonemes

@property (nonatomic, copy) NSArray *phonemes;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (id)phonemes;
- (void)setPhonemes:(id)arg1;

@end
