/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsTransport.framework/NewsTransport
 */

@interface NTPBNotificationItemListRecord : PBCodable <NSCopying> {
    NSString * _algoID;
    NTPBRecordBase * _base;
    struct { 
        unsigned int notificationSource : 1; 
    }  _has;
    NSMutableArray * _notificationItemIDs;
    int  _notificationSource;
}

@property (nonatomic, retain) NSString *algoID;
@property (nonatomic, retain) NTPBRecordBase *base;
@property (nonatomic, readonly) bool hasAlgoID;
@property (nonatomic, readonly) bool hasBase;
@property (nonatomic) bool hasNotificationSource;
@property (nonatomic, retain) NSMutableArray *notificationItemIDs;
@property (nonatomic) int notificationSource;

+ (Class)notificationItemIDsType;

- (void)addNotificationItemIDs:(id)arg1;
- (id)algoID;
- (id)base;
- (void)clearNotificationItemIDs;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasAlgoID;
- (bool)hasBase;
- (bool)hasNotificationSource;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)notificationItemIDs;
- (id)notificationItemIDsAtIndex:(unsigned long long)arg1;
- (unsigned long long)notificationItemIDsCount;
- (int)notificationSource;
- (bool)readFrom:(id)arg1;
- (void)setAlgoID:(id)arg1;
- (void)setBase:(id)arg1;
- (void)setHasNotificationSource:(bool)arg1;
- (void)setNotificationItemIDs:(id)arg1;
- (void)setNotificationSource:(int)arg1;
- (void)writeTo:(id)arg1;

@end
