/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DockKitCore.framework/DockKitCore
 */

@interface DockKitCore.SystemController : DockKitCore.System {
    void accessory;
}

- (void).cxx_destruct;
- (id)initWithAccessory:(id)arg1 id:(long long)arg2 type:(long long)arg3 name:(id)arg4;
- (id)initWithCoder:(id)arg1;
- (id)initWithId:(long long)arg1 type:(long long)arg2 name:(id)arg3;

@end
