/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppIntentsServices.framework/AppIntentsServices
 */

@interface AppIntentsServices.RemoteAppIntentsListener : _TtCs12_SwiftObject

@end
