/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriUIBridge.framework/SiriUIBridge
 */

@interface SUIBIntelligenceFlowActionSummary : NSObject <NSSecureCoding> {
    NSString * _formatString;
    NSDictionary * _parameterSummaries;
}

@property (nonatomic, readonly, copy) NSString *formatString;
@property (nonatomic, readonly, copy) NSDictionary *parameterSummaries;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)formatString;
- (id)init;
- (id)initWithBuilder:(id /* block */)arg1;
- (id)initWithCoder:(id)arg1;
- (id)parameterMatches;
- (id)parameterSummaries;

@end
