/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSIgnoredSiriSuggestedSitesDatabaseController : WBSSQLiteStore

+ (unsigned long long)thresholdForHidingIgnoredSiriSuggestedSites;

- (void)_addIgnoredSiriSuggestedSiteWithURLString:(id)arg1 inProfile:(id)arg2 withQuery:(id)arg3 visitedURLString:(id)arg4;
- (int)_createFreshDatabaseSchema;
- (int)_currentSchemaVersion;
- (id)_dateAtWhichIgnoredSiriSuggestedSitesArePruned;
- (id)_getIgnoredSiriSuggestedSitesURLStringsInProfile:(id)arg1 withQuery:(id)arg2;
- (int)_migrateToSchemaVersion:(int)arg1;
- (int)_migrateToSchemaVersion_2;
- (int)_migrateToSchemaVersion_3;
- (void)_removeIgnoredSiriSuggestedSitesBeforeDate:(id)arg1;
- (void)_removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 afterDate:(id)arg2;
- (void)_removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 query:(id)arg2;
- (void)_removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 visitedURLHost:(id)arg2;
- (void)_removeIgnoredSiriSuggestedSitesWithURLHost:(id)arg1 inProfile:(id)arg2;
- (void)_updateTimestampsOfIgnoredSiriSuggestedSitesInProfile:(id)arg1 query:(id)arg2 visitedURLString:(id)arg3;
- (void)addIgnoredSiriSuggestedSiteWithURLString:(id)arg1 inProfile:(id)arg2 withQuery:(id)arg3 visitedURLString:(id)arg4;
- (void)getIgnoredSiriSuggestedSitesURLStringsInProfile:(id)arg1 withQuery:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)pruneIgnoredSiriSuggestedSites;
- (void)removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 afterDate:(id)arg2;
- (void)removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 query:(id)arg2;
- (void)removeIgnoredSiriSuggestedSitesInProfile:(id)arg1 visitedURLHost:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)removeIgnoredSiriSuggestedSitesWithURLHost:(id)arg1 inProfile:(id)arg2;
- (void)updateTimestampsOfIgnoredSiriSuggestedSitesInProfile:(id)arg1 query:(id)arg2 visitedURLString:(id)arg3;

@end
