/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSPageTestBundle : NSObject <WBSTestBundle> {
    NSArray * _allTests;
    NSString * _identifier;
}

@property (nonatomic, readonly) NSArray *allTests;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *identifier;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)allTests;
- (id)identifier;
- (id)initWithIdentifier:(id)arg1 tests:(id)arg2;

@end
