/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSScribbleQuirksManager : NSObject {
    NSDictionary * _quirksDictionary;
}

- (void).cxx_destruct;
- (id)init;
- (id)quirksForHighLevelDomain:(id)arg1;

@end
