/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHAP.framework/CoreHAP
 */

@interface HAPHTTPClientDependencyFactory : NSObject <HAPHTTPClientDependencyFactory>

- (id)createHTTPClientWithQueue:(id)arg1;

@end
