/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorSearch.framework/VectorSearch
 */

@interface VectorSearch.VSKColumnTypeWrapper : NSObject {
    void wrappedValue;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithDoubleDefaultValue:(id)arg1;
- (id)initWithIntegerDefaultValue:(id)arg1;
- (id)initWithStringDefaultValue:(id)arg1;

@end
