/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorSearch.framework/VectorSearch
 */

@interface VectorSearch.VSKConfigWrapper : NSObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  wrappedConfig;
}

+ (id)clientVersionWithBaseDirectory:(id)arg1 error:(id*)arg2;

- (void).cxx_destruct;
- (id)getClientVersion;
- (id)init;
- (id)initWithBaseDirectory:(id)arg1 distanceMetric:(long long)arg2 filterableAttributes:(id)arg3 dimension:(long long)arg4 averagePartitionSize:(long long)arg5 batchSize:(long long)arg6 batchFactor:(long long)arg7 tradeOffParameterBetweenClusteringAndBalance:(float)arg8 enableFTS:(bool)arg9 dataType:(long long)arg10 maxIndexConstructionBatches:(id)arg11 readOnly:(bool)arg12 pretokenizationEnabled:(bool)arg13 prefixIndices:(id)arg14 perConnectionPeakMemory:(id)arg15 clientVersion:(id)arg16 error:(id*)arg17;
- (id)initWithBaseDirectory:(id)arg1 distanceMetric:(long long)arg2 filterableAttributes:(id)arg3 dimension:(long long)arg4 includePayload:(bool)arg5 numberOfProbes:(long long)arg6 averagePartitionSize:(long long)arg7 batchSize:(long long)arg8 batchFactor:(long long)arg9 tradeOffParameterBetweenClusteringAndBalance:(float)arg10 enableFTS:(bool)arg11 dataType:(long long)arg12 maxIndexConstructionBatches:(id)arg13 readOnly:(bool)arg14 pretokenizationEnabled:(bool)arg15 prefixIndices:(id)arg16 perConnectionPeakMemory:(id)arg17 clientVersion:(id)arg18 error:(id*)arg19;
- (id)initWithBaseDirectory:(id)arg1 includePayload:(bool)arg2 numberOfProbes:(long long)arg3 readOnly:(bool)arg4 perConnectionPeakMemory:(id)arg5 error:(id*)arg6;
- (id)initWithBaseDirectory:(id)arg1 readOnly:(bool)arg2 perConnectionPeakMemory:(id)arg3 error:(id*)arg4;

@end
