/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeepThoughtBiomeFoundation.framework/DeepThoughtBiomeFoundation
 */

@interface DeepThoughtBiomeFoundation.POICategoryEventFeatureExtractor : DeepThoughtBiomeFoundation.IntraEventFeatureExtractor

- (id)init;

@end
