/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherData.framework/WeatherData
 */

@interface _TtCV11WeatherData17FlatBufferBuilder13VTableStorage : _TtCs12_SwiftObject {
    void capacity;
    void maxOffset;
    void memory;
    void memoryInUse;
    void numOfFields;
    void size;
    void writtenIndex;
}

@end
