/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GESS.framework/GESS
 */

@interface GESSAlgGeometryQuality : NSObject {
    struct GeometryQuality { 
        float avgEdgeLength; 
        float avgVertexValence; 
        float vertexValenceDeviation; 
        float edgeLengthSD; 
        float faceAngleSD; 
        struct Box3T<float> { 
            struct Vector3T<float> { 
                union UnionType { 
                    /* Warning: Unrecognized filer type: '"' using 'void*' */ void*v; 
                } vec; 
            } min_; 
            struct Vector3T<float> { 
                union UnionType { 
                    void*v; 
                } vec; 
            } max_; 
        } aabb; 
    }  _qualityImpl;
}

@property GESSMathAABB *AABB;
@property float averageEdgeLength;
@property float averageVertexValence;
@property float edgeLengthStandardDeviation;
@property float faceAngleStandardDeviation;
@property float vertexValenceDeviation;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)AABB;
- (float)averageEdgeLength;
- (float)averageVertexValence;
- (id)description;
- (float)edgeLengthStandardDeviation;
- (float)faceAngleStandardDeviation;
- (void)setAABB:(id)arg1;
- (void)setAverageEdgeLength:(float)arg1;
- (void)setAverageVertexValence:(float)arg1;
- (void)setEdgeLengthStandardDeviation:(float)arg1;
- (void)setFaceAngleStandardDeviation:(float)arg1;
- (void)setQualityImpl:(const void*)arg1;
- (void)setVertexValenceDeviation:(float)arg1;
- (float)vertexValenceDeviation;

@end
