/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CarPlay.framework/CarPlay
 */

@interface CPTrip : NSObject <NSSecureCoding> {
    MKMapItem * _destination;
    NSArray * _destinationNameVariants;
    NSUUID * _identifier;
    MKMapItem * _origin;
    NSArray * _routeChoices;
    bool  _sendsNavigationMetadata;
    id  _userInfo;
}

@property (nonatomic, readonly) MKMapItem *destination;
@property (nonatomic, copy) NSArray *destinationNameVariants;
@property (nonatomic, retain) NSUUID *identifier;
@property (nonatomic, readonly) MKMapItem *origin;
@property (nonatomic, readonly, copy) NSArray *routeChoices;
@property (nonatomic) bool sendsNavigationMetadata;
@property (nonatomic, retain) id userInfo;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (id)destination;
- (id)destinationNameVariants;
- (short)destinationTimeZoneOffsetFromGMT;
- (void)encodeWithCoder:(id)arg1;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithOrigin:(id)arg1 destination:(id)arg2 routeChoices:(id)arg3;
- (id)origin;
- (id)routeChoices;
- (bool)sendsNavigationMetadata;
- (void)setDestinationNameVariants:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setSendsNavigationMetadata:(bool)arg1;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
