/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenSharingKit.framework/ScreenSharingKit
 */

@interface ScreenSharingKit.SharingBackedAuthenticationPrimitives : NSObject <SFAuthenticationManagerDelegate> {
    void approveByMacDelegate;
    void authenticationManager;
    void authenticationQueue;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  continuityDevice;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  disableDeviceContinuation;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  resetGeneration;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  trustDeviceContinuation;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  unlockDeviceContinuation;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  unlockGeneration;
}

- (void).cxx_destruct;
- (id)init;
- (void)manager:(id)arg1 didCompleteAuthenticationForSessionWithID:(id)arg2;
- (void)manager:(id)arg1 didDisableAuthenticationForSessionWithID:(id)arg2;
- (void)manager:(id)arg1 didEnableAuthenticationForSessionWithID:(id)arg2;
- (void)manager:(id)arg1 didFailAuthenticationForSessionWithID:(id)arg2 error:(id)arg3;
- (void)manager:(id)arg1 didFailToDisableDeviceForSessionWithID:(id)arg2 error:(id)arg3;
- (void)manager:(id)arg1 didFailToEnableDeviceForSessionWithID:(id)arg2 error:(id)arg3;
- (void)manager:(id)arg1 didReceiveRequestToApproveForSessionID:(id)arg2 info:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)manager:(id)arg1 didStartAuthenticationForSessionWithID:(id)arg2;

@end
