/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.OfferListCardLayout : VideosUI.ViewLayout {
    void buttonLayout;
    void cardType;
    void imageLayout;
}

@end
