/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.AppEnvironment : VideosUI.OptimizedObservableObject {
    void _sidebarSafeAreaInset;
    void _sizeClass;
    void _windowSize;
    void isRTL;
    void sidebarWidth;
}

@end
