/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ReportingPlugin.framework/ReportingPlugin
 */

@interface ReportingPlugin.PeopleSuggestionInference : NSObject {
    void id;
}

- (void).cxx_destruct;
- (id)init;

@end
