/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ReportingPlugin.framework/ReportingPlugin
 */

@interface ReportingPlugin.AppSuggestionsJointEvent : NSObject {
    void engagedModelRanks;
    void engagement;
    void inferenceModels;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  timestamp;
}

- (void).cxx_destruct;
- (id)init;

@end
