/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TokenGenerationInference.framework/TokenGenerationInference
 */

@interface TokenGenerationInference.KVLRUCache : _TtCs12_SwiftObject {
    void currentTokenCount;
    void endNode;
    void maximumTokenCount;
    void nodeByTokens;
    void startNode;
}

@end
