/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriMessageTypes.framework/SiriMessageTypes
 */

@interface SiriMessageTypes.StoppedListeningForTextContinuationMessage : SiriMessageTypes.RequestMessageBase {
    void lastTRPId;
}

@property (nonatomic, readonly) NSString *description;

- (void).cxx_destruct;
- (id)description;

@end
