/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriMessageTypes.framework/SiriMessageTypes
 */

@interface SiriMessageTypes.VoiceCommandContextMessage : SiriMessageTypes.RequestMessageBase {
    void abortCommandSuppression;
    void cursorInVisibleText;
    void disambiguationActive;
    void favorCommandSuppression;
    void postfixText;
    void prefixText;
    void selectedText;
    void undoEvent;
}

- (void).cxx_destruct;

@end
