/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriMessageTypes.framework/SiriMessageTypes
 */

@interface SiriMessageTypes.StartLocalRequestMessage : SiriMessageTypes.StartRequestMessageBase

@end
