/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightServices.framework/SpotlightServices
 */

@interface SSIntentBasedSectionConfiguration : NSObject {
    NSDictionary * _sectionDisplayStrategies;
}

@property (nonatomic, retain) NSDictionary *sectionDisplayStrategies;

- (void).cxx_destruct;
- (id)sectionDisplayStrategies;
- (void)setSectionDisplayStrategies:(id)arg1;

@end
