/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/BrowserEngineKit.framework/BrowserEngineKit
 */

@interface _BEBurnableBlock : NSObject {
    id /* block */  _block;
    NSObject<OS_dispatch_source> * _timer;
}

- (void).cxx_destruct;
- (void)_cancelTimerIfNeeded;
- (void)dealloc;
- (id)initWithTimeout:(double)arg1 block:(id /* block */)arg2 defaultInputProvider:(id /* block */)arg3;
- (bool)performWithInput:(id)arg1;

@end
