/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LocalAuthenticationCoreUI.framework/LocalAuthenticationCoreUI
 */

@interface LACUIKeyboardView : UIView {
    LACUIKeyboardInternal * _keyboard;
}

- (void).cxx_destruct;
- (void)_setup;
- (id)init;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;

@end
