/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/LocalAuthenticationCoreUI.framework/LocalAuthenticationCoreUI
 */

@interface LACUIFaceIDSpinnerView : UIView {
    CALayer * _faceLayer;
    LACUIPackagedView * _packagedView;
    long long  _state;
}

@property (nonatomic, readonly) CALayer *faceLayer;
@property (nonatomic) long long state;

- (void).cxx_destruct;
- (void)_setup;
- (id)faceLayer;
- (id)init;
- (id)initWithInitialState:(long long)arg1;
- (void)setState:(long long)arg1;
- (long long)state;

@end
