/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaAnalysis.framework/MediaAnalysis
 */

@interface MADTextEmbeddingThreshold : NSObject {
    struct { 
        void *data; 
        void *reserved; 
        unsigned long long dim[4]; 
        unsigned long long stride[4]; 
        unsigned long long width; 
        unsigned long long height; 
        unsigned long long channels; 
        unsigned long long batch_number; 
        unsigned long long sequence_length; 
        unsigned long long stride_width; 
        unsigned long long stride_height; 
        unsigned long long stride_channels; 
        unsigned long long stride_batch_number; 
        unsigned long long stride_sequence_length; 
        int storage_type; 
    }  _biasBuffer;
    void * _context;
    struct CF<__CVBuffer *> { 
        struct __CVBuffer {} *value_; 
    }  _inputBuffer;
    struct { 
        void *plan; 
        int network_index; 
    }  _network;
    void * _plan;
    NSObject<OS_dispatch_queue> * _queue;
    struct { 
        void *data; 
        void *reserved; 
        unsigned long long dim[4]; 
        unsigned long long stride[4]; 
        unsigned long long width; 
        unsigned long long height; 
        unsigned long long channels; 
        unsigned long long batch_number; 
        unsigned long long sequence_length; 
        unsigned long long stride_width; 
        unsigned long long stride_height; 
        unsigned long long stride_channels; 
        unsigned long long stride_batch_number; 
        unsigned long long stride_sequence_length; 
        int storage_type; 
    }  _scaleBuffer;
}

+ (float)computeThresholdBase:(float)arg1;
+ (id)createForEmbeddingVersion:(unsigned long long)arg1;
+ (unsigned long long)embeddingLength;
+ (unsigned long long)embeddingVersion;
+ (id)modelName;
+ (float)thresholdBase;

- (id).cxx_construct;
- (void).cxx_destruct;
- (int)_createPlan;
- (int)_loadResources;
- (int)_processEmbedding:(id)arg1 bias:(float*)arg2 scale:(float*)arg3 threshold:(float*)arg4;
- (void)dealloc;
- (id)init;
- (int)loadResources;
- (int)processEmbedding:(id)arg1 bias:(float*)arg2 scale:(float*)arg3 threshold:(float*)arg4;

@end
