/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface _HKObjectTypeAnchor : NSObject <NSSecureCoding> {
    NSDictionary * _anchors;
    NSUUID * _databaseIdentifier;
}

@property (nonatomic, readonly, copy) NSDictionary *anchors;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)anchors;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithAnchors:(id)arg1 databaseIdentifier:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
