/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKProductVersions : NSObject

+ (id)activePairedDeviceSystemBuildVersion;
+ (id)productBuildVersionForDeviceType:(long long)arg1;

@end
