/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RealityIO.framework/RealityIO
 */

@interface _TtC9RealityIOP33_783E2DD2D14FB2A3AA99C56BAEE17E6A31REAudioFileConfigurationWrapper : _TtCs12_SwiftObject {
    void config;
}

@end
