/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RealityIO.framework/RealityIO
 */

@interface RealityIO.ImageBasedLightBuilder : _TtCs12_SwiftObject {
    void buildOrder;
    void currentBlendIBLAssetPath;
    void currentIBLAssetPath;
    void currentMode;
    void didBuild;
}

@end
