/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface IMAP2Helpers.StateCapture : _TtCs12_SwiftObject {
    void didTearDown;
    void handle;
    void targetQueue;
}

@end
