/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MicroLocationDaemon.framework/MicroLocationDaemon
 */

@interface MicroLocationDaemon.ULEncryption : NSObject

+ (id)decryptData:(id)arg1 keyLabel:(id)arg2;
+ (bool)decryptFile:(id)arg1 destinationPath:(id)arg2 keyLabel:(id)arg3 keychainClass:(Class)arg4;
+ (id)encryptData:(id)arg1 keyLabel:(id)arg2;
+ (bool)encryptFile:(id)arg1 destinationPath:(id)arg2 keyLabel:(id)arg3 keychainClass:(Class)arg4;

- (void).cxx_destruct;
- (id)init;

@end
