/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXMailSenderImportanceWeights : NSObject {
    NSDictionary * _mailSenderImportanceWeights;
}

- (void).cxx_destruct;
- (id)init;
- (double)isContactChatPinnedInMessage;
- (double)isEmergencyContact;
- (double)isFavoriteContact;
- (double)isFrequentlyContacted;
- (double)isFromMailingList;
- (double)isVIP;
- (double)isiCloudFamilyMember;
- (double)mailContactHasBeencontactedToday;
- (double)speedOfResponseToMailContact;

@end
