/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.PromiseCardViewController : UIViewController {
    void activityIndicatorOffset;
    void activityIndicatorView;
    void defaultCardSplitViewPresentationForState;
    void defaultCardViewBehavior;
    void viewControllerState;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end
