/* Generated by RuntimeBrowser
   Image: /usr/lib/libmrc.dylib
 */

@interface OS_mrc_dns_proxy_state_inquiry : OS_mrc_object <OS_mrc_dns_proxy_state_inquiry>

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

@end
