/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/OnBoardingKit.framework/OnBoardingKit
 */

@interface OBTemplateHeaderDetailLabel : UILabel {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _bodyRange;
    NSNumber * _spansAllLinesOverride;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _titleRange;
}

@property (nonatomic) struct _NSRange { unsigned long long x1; unsigned long long x2; } bodyRange;
@property (nonatomic, retain) NSNumber *spansAllLinesOverride;
@property (nonatomic) struct _NSRange { unsigned long long x1; unsigned long long x2; } titleRange;

- (void).cxx_destruct;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })bodyRange;
- (void)overrideSpansAllLines:(unsigned long long)arg1;
- (void)setBodyRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (void)setDetailedTextHeader:(id)arg1 detailedTextBody:(id)arg2;
- (void)setSpansAllLinesOverride:(id)arg1;
- (void)setText:(id)arg1;
- (void)setTitleRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)spansAllLinesOverride;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })titleRange;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateAttributedTextWithString:(id)arg1;

@end
