/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CameraUI.framework/CameraUI
 */

@interface CAMPhotoVideoModeSwitch : UIControl <CEKAdditiveAnimatorDelegate> {
    CEKAdditiveAnimator * __animator;
    bool  __isTouching;
    UIView * __knob;
    UIImageView * __knobSelectionPhotoImageView;
    UIImageView * __knobSelectionVideoImageView;
    UIImageView * __photoImageView;
    UIView * __track;
    UIImageView * __videoImageView;
    unsigned long long  _mode;
    long long  _orientation;
}

@property (nonatomic, readonly) CEKAdditiveAnimator *_animator;
@property (setter=_setIsTouching:, nonatomic) bool _isTouching;
@property (nonatomic, readonly) UIView *_knob;
@property (nonatomic, readonly) UIImageView *_knobSelectionPhotoImageView;
@property (nonatomic, readonly) UIImageView *_knobSelectionVideoImageView;
@property (nonatomic, readonly) UIImageView *_photoImageView;
@property (nonatomic, readonly) UIView *_track;
@property (nonatomic, readonly) UIImageView *_videoImageView;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long mode;
@property (nonatomic) long long orientation;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_animator;
- (bool)_isTouching;
- (id)_knob;
- (id)_knobSelectionPhotoImageView;
- (id)_knobSelectionVideoImageView;
- (double)_knobXPosition;
- (id)_photoImageView;
- (void)_setIsTouching:(bool)arg1;
- (void)_swipe:(id)arg1;
- (void)_touchCancel:(id)arg1;
- (void)_touchCommit:(id)arg1;
- (void)_touchStart:(id)arg1;
- (id)_track;
- (double)_trackBorderWidth;
- (double)_trackColorAlpha;
- (double)_trackColorWhite;
- (void)_updateAnimatedValuesWithAnimator:(id)arg1;
- (void)_updateKnobAnimated:(bool)arg1;
- (id)_videoImageView;
- (void)animator:(id)arg1 didUpdateValuesForKeys:(id)arg2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })knobFrame;
- (void)layoutSubviews;
- (unsigned long long)mode;
- (long long)orientation;
- (void)setMode:(unsigned long long)arg1;
- (void)setMode:(unsigned long long)arg1 animated:(bool)arg2;
- (void)setOrientation:(long long)arg1;
- (void)setOrientation:(long long)arg1 animated:(bool)arg2;
- (void)toggleModeAnimated:(bool)arg1;

@end
