/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/_MusicKit_SwiftUI.framework/_MusicKit_SwiftUI
 */

@interface _MusicKit_SwiftUI.ArtworkLoadingObserver : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _$observationRegistrar;
    void handler;
}

@end
