/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/StickerKit.framework/StickerKit
 */

@interface _UIEmojiAndStickerCollectionViewController : UIViewController {
    id  _configuration;
    <_UIEmojiAndStickerCollectionViewControllerDelegate> * _delegate;
    <_UIKeyboardEmojiKeyDisplayController> * _emojiKeyManager;
    NSArray * _searchResults;
}

@property (nonatomic, retain) id configuration;
@property (nonatomic) <_UIEmojiAndStickerCollectionViewControllerDelegate> *delegate;
@property (nonatomic, readonly) <_UIKeyboardEmojiKeyDisplayController> *emojiKeyManager;
@property (nonatomic, retain) NSArray *searchResults;

+ (id)newInstanceWithConfiguration:(id)arg1;

- (void).cxx_destruct;
- (id)configuration;
- (id)delegate;
- (id)emojiKeyManager;
- (id)searchResults;
- (void)setConfiguration:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setSearchResults:(id)arg1;

@end
