/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SettingsCellularUI.framework/SettingsCellularUI
 */

@interface PSUIAppDescription : NSObject {
    NSString * _bundleID;
    UIImage * _icon;
    NSURL * _iconURL;
    NSURL * _installURL;
    bool  _installed;
    NSString * _installedLabel;
    NSString * _name;
    NSString * _publisher;
    NSString * _subtitle;
}

@property (nonatomic, copy) NSString *bundleID;
@property (nonatomic, retain) UIImage *icon;
@property (nonatomic, copy) NSURL *iconURL;
@property (nonatomic, copy) NSURL *installURL;
@property (nonatomic) bool installed;
@property (nonatomic, copy) NSString *installedLabel;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *publisher;
@property (nonatomic, copy) NSString *subtitle;

- (void).cxx_destruct;
- (id)bundleID;
- (id)description;
- (id)icon;
- (id)iconURL;
- (id)initWithAMSMediaResponseDictionary:(id)arg1;
- (id)installURL;
- (bool)installed;
- (id)installedLabel;
- (id)name;
- (id)publisher;
- (void)setBundleID:(id)arg1;
- (void)setIcon:(id)arg1;
- (void)setIconURL:(id)arg1;
- (void)setInstallURL:(id)arg1;
- (void)setInstalled:(bool)arg1;
- (void)setInstalledLabel:(id)arg1;
- (void)setName:(id)arg1;
- (void)setPublisher:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (id)subtitle;

@end
