/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreServices.framework/CoreServices
 */

@interface _LSRemotePlaceholderEnumerator : _LSApplicationRecordEnumerator

- (id)_applicationRecordWithContext:(struct LSContext { id x1; }*)arg1 bundleIdentifierOrUnit:(unsigned int)arg2;

@end
