/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SleepDaemon.framework/SleepDaemon
 */

@interface HDSPActivityWakeDetector : NSObject <HDSPEnvironmentAware, HDSPNotificationObserver, HDSPWakeDetector> {
    HDSPEnvironment * _environment;
    bool  _isDetecting;
    <HDSPWakeDetectorDelegate> * _wakeDetectorDelegate;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) HDSPEnvironment *environment;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isDetecting;
@property (readonly) Class superclass;
@property (nonatomic, readonly) unsigned long long type;
@property (nonatomic) <HDSPWakeDetectorDelegate> *wakeDetectorDelegate;

- (void).cxx_destruct;
- (id)environment;
- (void)environmentDidBecomeReady:(id)arg1;
- (id)initWithEnvironment:(id)arg1;
- (bool)isDetecting;
- (id)notificationListener:(id)arg1 didReceiveNotificationWithName:(id)arg2;
- (void)notifyForActivityDetectedOnDate:(id)arg1;
- (void)setWakeDetectorDelegate:(id)arg1;
- (void)startDetecting;
- (void)stopDetecting;
- (unsigned long long)type;
- (id)wakeDetectorDelegate;

@end
