/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeEnergyDaemon.framework/HomeEnergyDaemon
 */

@interface HomeEnergyDaemon.UsagePointRecordsManager : _TtCs12_SwiftObject {
    void sharedContext;
    void usagePoint;
}

@end
