/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PnROnDeviceFramework.framework/PnROnDeviceFramework
 */

@interface PnROnDeviceFramework.IEPlannerGrainSpec : _TtCs12_SwiftObject {
    void actionResolverRequestToLastResolverEventTime;
    void lastQueryDecorationEventToPlanCreatedTime;
    void lastResolverEventToResponseGeneratedTime;
    void planCreatedToActionResolverRequestTime;
    void planCreatedToLastResolverEventTime;
    void plannerGrainDimensions;
    void plannerResponseTime;
    void resolverTotalQueryTime;
    void spanIds;
    void startToActionResolverRequestTime;
    void startToContextRetrievedTime;
    void startToEntitySpanMatchedTime;
    void startToLastQueryDecorationEventTime;
    void startToLastResolverEventTime;
    void startToPlanCreatedTime;
    void startToToolsRetrievedTime;
}

@end
