/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iCloudQuotaUI.framework/iCloudQuotaUI
 */

@interface ICQUIOSLOPresenter : NSObject <ICQLiftUIPresenterDelegate, ICQPurchaseDelegate, ICQUIRemoteUIPresenterDelegate> {
    <ICQUIOSLOPresenterDelegate> * _delegate;
    ICQLiftUIPresenter * _liftUIPresenter;
    ICQLink * _link;
    ICQOffer * _offer;
    ICQLink * _postPurchaseFlowLink;
    UIViewController * _presenter;
    ICQPurchase * _purchase;
    NSDictionary * _purchaseParams;
    ICQUIRemoteUIPresenter * _remoteUIPresenter;
}

@property (nonatomic, readonly) NSString *_sceneIdentifier;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (nonatomic) <ICQUIOSLOPresenterDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)parsePurchaseParams:(id)arg1;

- (void).cxx_destruct;
- (id)_createPostPurchaseICQLink;
- (void)_handlePostPurchaseFlow;
- (void)_handlePostPurchaseLiftUIFlow;
- (void)_handlePostPurchaseRemoteUIFlow;
- (id)_sceneIdentifier;
- (void)beginOSLOPurchaseFlow;
- (id)delegate;
- (void)handleAuthenticateRequest:(id)arg1 purchase:(id)arg2 completion:(id /* block */)arg3;
- (void)handleDialogRequest:(id)arg1 purchase:(id)arg2 completion:(id /* block */)arg3;
- (void)handleEngagementRequest:(id)arg1 purchase:(id)arg2 completion:(id /* block */)arg3;
- (id)initWithOffer:(id)arg1 link:(id)arg2 presenter:(id)arg3;
- (bool)isLiftUIFlow;
- (void)liftUIPresenterDidCancel:(id)arg1;
- (void)liftUIPresenterDidComplete:(id)arg1;
- (void)remoteUIFlowManager:(id)arg1 didCompleteFlowWithSuccess:(bool)arg2 error:(id)arg3;
- (void)remoteUIFlowManager:(id)arg1 didDismissWithError:(id)arg2;
- (void)remoteUIFlowManager:(id)arg1 didLoadWithSuccess:(bool)arg2 error:(id)arg3;
- (void)setDelegate:(id)arg1;

@end
