/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AudioServerDriverTransports_IOA2.framework/AudioServerDriverTransports_IOA2
 */

@interface ASDTIOA2OffsetStream : ASDTIOA2Stream {
    long long  _sampleTimeOffset;
}

@property (nonatomic) long long sampleTimeOffset;

- (id /* block */)readInputBlock;
- (long long)sampleTimeOffset;
- (void)setSampleTimeOffset:(long long)arg1;

@end
