/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/InstalledContentLibrary.framework/InstalledContentLibrary
 */

@interface MIMachOImageSlice : NSObject {
    int  _cpuSubtype;
    int  _cpuType;
    unsigned int  _minOSVersion;
    unsigned int  _platform;
    unsigned int  _sdkVersion;
}

@property (nonatomic) int cpuSubtype;
@property (nonatomic) int cpuType;
@property (nonatomic) unsigned int minOSVersion;
@property (nonatomic) unsigned int platform;
@property (nonatomic) unsigned int sdkVersion;

- (int)cpuSubtype;
- (int)cpuType;
- (id)description;
- (id)initWithCPUType:(int)arg1 cpuSubtype:(int)arg2 platform:(unsigned int)arg3 sdkVersion:(unsigned int)arg4 minOSVersion:(unsigned int)arg5;
- (unsigned int)minOSVersion;
- (unsigned int)platform;
- (unsigned int)sdkVersion;
- (void)setCpuSubtype:(int)arg1;
- (void)setCpuType:(int)arg1;
- (void)setMinOSVersion:(unsigned int)arg1;
- (void)setPlatform:(unsigned int)arg1;
- (void)setSdkVersion:(unsigned int)arg1;

@end
