/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/IntelligencePlatformCore
 */

@interface _TtCO24IntelligencePlatformCore10ViewUpdate14KeyValueSource : _TtCs12_SwiftObject {
    void configIdentifier;
    void currentBookmark;
    void initialBookmark;
    void initialSourceUpdatedTimestamp;
    void kvs;
    void latestBookmark;
    void response;
    void state;
    void triggered;
    void updateConfig;
    void updateType;
    void viewName;
}

@end
