/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MailSupport.framework/MailSupport
 */

@interface MSInputContextHistory : NSObject <EFPubliclyDescribable> {
    NSDictionary * _ccRecipientNamesByEmailAddress;
    NSArray * _ccRecipients;
    NSSet * _firstPerson;
    bool  _hasCustomSignature;
    NSDictionary * _infoDict;
    NSArray * _originalContentMessages;
    NSString * _originalMessageCategorySubtype;
    NSMutableDictionary * _participantsByEmailAddress;
    NSSet * _primaryRecipients;
    NSDictionary * _recipientNamesByEmailAddress;
    NSSet * _secondaryRecipients;
    ECEmailAddress * _senderEmailAddress;
    bool  _showSmartReplySuggestions;
    NSString * _subject;
    NSString * _threadIdentifier;
    NSDictionary * _toRecipientNamesByEmailAddress;
    NSArray * _toRecipients;
}

@property (nonatomic, retain) NSDictionary *ccRecipientNamesByEmailAddress;
@property (nonatomic, retain) NSArray *ccRecipients;
@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *ef_publicDescription;
@property (nonatomic, retain) NSSet *firstPerson;
@property (nonatomic) bool hasCustomSignature;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSDictionary *infoDict;
@property (nonatomic, retain) NSArray *originalContentMessages;
@property (nonatomic, copy) NSString *originalMessageCategorySubtype;
@property (nonatomic, retain) NSMutableDictionary *participantsByEmailAddress;
@property (nonatomic, retain) NSSet *primaryRecipients;
@property (nonatomic, retain) NSDictionary *recipientNamesByEmailAddress;
@property (nonatomic, retain) NSSet *secondaryRecipients;
@property (nonatomic, retain) ECEmailAddress *senderEmailAddress;
@property (nonatomic) bool showSmartReplySuggestions;
@property (nonatomic, copy) NSString *subject;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *threadIdentifier;
@property (nonatomic, retain) NSDictionary *toRecipientNamesByEmailAddress;
@property (nonatomic, retain) NSArray *toRecipients;

- (void).cxx_destruct;
- (id)_participantNameAndEmailAddressFromEmailAddress:(id)arg1;
- (id)_participantNamesByEmailAddressFromRecipients:(id)arg1;
- (id)ccRecipientNamesByEmailAddress;
- (id)ccRecipients;
- (id)description;
- (id)ef_publicDescription;
- (id)firstPerson;
- (bool)hasCustomSignature;
- (unsigned long long)hash;
- (id)infoDict;
- (id)initWithThreadIdentifier:(id)arg1 senderEmailAddress:(id)arg2 toRecipients:(id)arg3 ccRecipients:(id)arg4 subject:(id)arg5 hasCustomSignature:(bool)arg6 showSmartReplySuggestions:(bool)arg7 originalMessageCategorySubtype:(id)arg8 originalContentMessages:(id)arg9;
- (bool)isEqual:(id)arg1;
- (id)originalContentMessages;
- (id)originalMessageCategorySubtype;
- (id)participantsByEmailAddress;
- (id)primaryRecipients;
- (id)recipientNamesByEmailAddress;
- (id)secondaryRecipients;
- (id)senderEmailAddress;
- (void)setCcRecipientNamesByEmailAddress:(id)arg1;
- (void)setCcRecipients:(id)arg1;
- (void)setFirstPerson:(id)arg1;
- (void)setHasCustomSignature:(bool)arg1;
- (void)setInfoDict:(id)arg1;
- (void)setOriginalContentMessages:(id)arg1;
- (void)setOriginalMessageCategorySubtype:(id)arg1;
- (void)setParticipantsByEmailAddress:(id)arg1;
- (void)setPrimaryRecipients:(id)arg1;
- (void)setRecipientNamesByEmailAddress:(id)arg1;
- (void)setSecondaryRecipients:(id)arg1;
- (void)setSenderEmailAddress:(id)arg1;
- (void)setShowSmartReplySuggestions:(bool)arg1;
- (void)setSubject:(id)arg1;
- (void)setThreadIdentifier:(id)arg1;
- (void)setToRecipientNamesByEmailAddress:(id)arg1;
- (void)setToRecipients:(id)arg1;
- (bool)showSmartReplySuggestions;
- (id)subject;
- (id)threadIdentifier;
- (id)toRecipientNamesByEmailAddress;
- (id)toRecipients;

@end
