/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Hands.framework/Hands
 */

@interface Hands.PinchGenerator : _TtCs12_SwiftObject {
    void _enableCoreAnalytics;
    void _objectInHandAnalytics;
    void _objectInteractionStateCancelAnalytics;
    void _objectInteractionStateExitReasonAnalytics;
    void _objectInteractionStateRejectAnalytics;
    void _pinchFrameFeatureProcessor;
    void _pinchFrameFeatures;
    void _pinchPostProcessingUnits;
    void _serializeInternalData;
}

@end
