/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Hands.framework/Hands
 */

@interface Hands.PinchGesturesForRecovery : _TtCs12_SwiftObject {
    void _absWristRoll;
    void _directionChanged;
    void _jointCoordBuffer;
    void _jointVelocityBuffer;
    void _maxAbsWristPitchVel;
    void _maxPinchSpeed;
    void _maxRelativeSpeedRatio;
    void _noiseFloor;
    void _pinchFrames;
    void _poseCacheSize;
    void _thresholdScrollMaxPinchSpeed;
    void _thresholdScrollMinSwipeFrames;
    void _thresholdScrollRelativeSpeedRatio;
    void _wristPitchBuffer;
    void _wristPitchVelocityBuffer;
}

@end
