/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Hands.framework/Hands
 */

@interface Hands.MiddleDoubleTapRecognition : _TtCs12_SwiftObject {
    void config;
    void enable;
    void eventLogger;
    void hoverDistanceCalculator;
    void middleDoubleTapState;
    void middleTip;
    void suppressors;
}

@end
