/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataDeliveryServices.framework/DataDeliveryServices
 */

@interface DDSMAAutoAssetManagerDataSource : NSObject <DDSMAAutoAssetManagerDataSource>

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (long long)linguisticAssetCompatabilityVersion;
- (bool)shouldDownloadAutoAsset;
- (id)supportedAutoAssetSpecifiers;

@end
