/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.AllHighlightsForExperienceViewController : HealthExperienceUI.CompoundDataSourceCollectionViewController

- (id)initWithCoder:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (void)viewDidLoad;

@end
