/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.PDFCollectionViewLayout : UICollectionViewFlowLayout

@property (nonatomic, readonly) bool flipsHorizontallyInOppositeLayoutDirection;

- (bool)flipsHorizontallyInOppositeLayoutDirection;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end
