/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UNCNotificationSystemServiceListener : NSObject <BSServiceConnectionListenerDelegate, UNCNotificationSystemServiceConnectionDelegate> {
    <UNCNotificationSystemServiceListenerDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _queue;
    NSMutableArray * _queue_connections;
    BSServiceConnectionListener * _queue_listener;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)activate;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (void)systemServiceConnectionDidInvalidate:(id)arg1;

@end
