/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UNCSummary : NSObject <NSSecureCoding> {
    NSString * _bundleIdentifier;
    NSAttributedString * _content;
    bool  _groupSummary;
    NSArray * _requestIdentifiers;
    NSString * _spotlightIdentifier;
    NSString * _threadIdentifier;
}

@property (nonatomic, readonly, copy) NSString *bundleIdentifier;
@property (nonatomic, readonly, copy) NSAttributedString *content;
@property (getter=isGroupSummary, nonatomic, readonly) bool groupSummary;
@property (nonatomic, readonly, copy) NSString *notificationIdentifier;
@property (nonatomic, readonly, copy) NSArray *requestIdentifiers;
@property (nonatomic, readonly, copy) NSString *spotlightIdentifier;
@property (nonatomic, readonly, copy) NSString *threadIdentifier;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)bundleIdentifier;
- (id)content;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1 requestIdentifiers:(id)arg2 spotlightIdentifier:(id)arg3 groupSummary:(bool)arg4 content:(id)arg5 threadIdentifier:(id)arg6;
- (id)initWithCoder:(id)arg1;
- (bool)isGroupSummary;
- (id)notificationIdentifier;
- (id)requestIdentifiers;
- (id)spotlightIdentifier;
- (id)threadIdentifier;

@end
