/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UserNotificationsCore.UserNotificationsVendorServer : _TtCs12_SwiftObject {
    void actionResponder;
    void categoryRepositoryAggregator;
    void listener;
    void lock;
    void notificationRepository;
    void requestProcessingQueue;
    void serviceName;
    void sessions;
    void settingsProvider;
}

@end
