/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UserNotificationsCore.NotificationActionRouter : _TtCs12_SwiftObject {
    void categoryRepository;
    void localDevice;
    void notificationRepository;
}

@end
