/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UserNotificationsCore.DateDefinedReaperClientRepositoryProxy : _TtCs12_SwiftObject {
    void notificationRepository;
}

@end
