/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsCore.framework/UserNotificationsCore
 */

@interface UserNotificationsCore.NotificationSystemServiceClient : NSObject <UNCNotificationCommonServiceServerProtocol, UNCNotificationSystemServiceClientProtocol> {
    void queue;
    void queue_connection;
}

- (void).cxx_destruct;
- (id)allBundleIdentifiersForCategories;
- (id)categoriesForBundleIdentifier:(id)arg1;
- (id)categoryForIdentifier:(id)arg1 bundleIdentifier:(id)arg2;
- (void)categoryRepositoryDidChangeCategoriesForBundleIdentifier:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)removeNotificationRecordsForIdentifiers:(id)arg1 bundleIdentifier:(id)arg2;
- (void)setCategories:(id)arg1 forBundleIdentifier:(id)arg2;

@end
