/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoAnalysis.framework/PhotoAnalysis
 */

@interface PHACurareShadowEvaluationRecipeOptions : PHAPrivateFederatedLearningRecipeOptions {
    NSArray * _modelInfoArray;
    NSString * _trialDeploymentID;
    NSString * _trialExperimentID;
    NSString * _trialTreatmentID;
}

@property (nonatomic, retain) NSArray *modelInfoArray;
@property (nonatomic, retain) NSString *trialDeploymentID;
@property (nonatomic, retain) NSString *trialExperimentID;
@property (nonatomic, retain) NSString *trialTreatmentID;

- (void).cxx_destruct;
- (id)init;
- (id)modelInfoArray;
- (void)setModelInfoArray:(id)arg1;
- (void)setTrialDeploymentID:(id)arg1;
- (void)setTrialExperimentID:(id)arg1;
- (void)setTrialTreatmentID:(id)arg1;
- (id)trialDeploymentID;
- (id)trialExperimentID;
- (id)trialTreatmentID;

@end
