/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GameCenterOverlayService.framework/GameCenterOverlayService
 */

@interface GameCenterOverlayService.MultiplayerClientProxy : GameCenterOverlayService.ClientProxy

@end
