/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/_RealityKit_SwiftUI.framework/_RealityKit_SwiftUI
 */

@interface _RealityKit_SwiftUI.BoundingBoxHelpers : _TtCs12_SwiftObject

@end
