/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/_RealityKit_SwiftUI.framework/_RealityKit_SwiftUI
 */

@interface _TtCV19_RealityKit_SwiftUI24RealityViewCameraContent14ContentStorage : _TtCs12_SwiftObject {
    void spatialTrackingSession;
    void storedSubscriptions;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  unavailableCapabilities;
}

@end
