/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface IFTSchemaIFTActionRequirement : SISchemaInstrumentationMessage {
    IFTSchemaIFTAppRequirement * _appRequirement;
    bool  _exists;
    struct { 
        unsigned int exists : 1; 
    }  _has;
    bool  _hasAppRequirement;
    bool  _hasPermissionRequirement;
    bool  _hasSystemRequirement;
    bool  _hasUnsupported;
    IFTSchemaIFTPermissionRequirement * _permissionRequirement;
    IFTSchemaIFTSystemRequirement * _systemRequirement;
    bool  _unsupported;
    unsigned long long  _whichOneof_Actionrequirement;
}

@property (nonatomic, retain) IFTSchemaIFTAppRequirement *appRequirement;
@property (nonatomic) bool exists;
@property (nonatomic) bool hasAppRequirement;
@property (nonatomic) bool hasExists;
@property (nonatomic) bool hasPermissionRequirement;
@property (nonatomic) bool hasSystemRequirement;
@property (nonatomic) bool hasUnsupported;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) IFTSchemaIFTPermissionRequirement *permissionRequirement;
@property (nonatomic, retain) IFTSchemaIFTSystemRequirement *systemRequirement;
@property (nonatomic) bool unsupported;
@property (nonatomic, readonly) unsigned long long whichOneof_Actionrequirement;

- (void).cxx_destruct;
- (id)appRequirement;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)deleteAppRequirement;
- (void)deleteExists;
- (void)deletePermissionRequirement;
- (void)deleteSystemRequirement;
- (void)deleteUnsupported;
- (id)dictionaryRepresentation;
- (bool)exists;
- (bool)hasAppRequirement;
- (bool)hasExists;
- (bool)hasPermissionRequirement;
- (bool)hasSystemRequirement;
- (bool)hasUnsupported;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)permissionRequirement;
- (bool)readFrom:(id)arg1;
- (void)setAppRequirement:(id)arg1;
- (void)setExists:(bool)arg1;
- (void)setHasAppRequirement:(bool)arg1;
- (void)setHasExists:(bool)arg1;
- (void)setHasPermissionRequirement:(bool)arg1;
- (void)setHasSystemRequirement:(bool)arg1;
- (void)setHasUnsupported:(bool)arg1;
- (void)setPermissionRequirement:(id)arg1;
- (void)setSystemRequirement:(id)arg1;
- (void)setUnsupported:(bool)arg1;
- (id)suppressMessageUnderConditions;
- (id)systemRequirement;
- (bool)unsupported;
- (unsigned long long)whichOneof_Actionrequirement;
- (void)writeTo:(id)arg1;

@end
