/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface ODDSiriSchemaODDSiriAccountInformation : SISchemaInstrumentationMessage {
    NSString * _assistantId;
    bool  _hasAssistantId;
}

@property (nonatomic, copy) NSString *assistantId;
@property (nonatomic) bool hasAssistantId;
@property (nonatomic, readonly) NSData *jsonData;

- (void).cxx_destruct;
- (id)assistantId;
- (void)deleteAssistantId;
- (id)dictionaryRepresentation;
- (bool)hasAssistantId;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setAssistantId:(id)arg1;
- (void)setHasAssistantId:(bool)arg1;
- (id)suppressMessageUnderConditions;
- (void)writeTo:(id)arg1;

@end
