/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface ODDSiriSchemaODDAssistantExperimentDigest : SISchemaInstrumentationMessage {
    ODDSiriSchemaODDAssistantExperimentCounts * _counts;
    ODDSiriSchemaODDAssistantExperimentDimensions * _dimensions;
    bool  _hasCounts;
    bool  _hasDimensions;
    bool  _hasTuples;
    ODDSiriSchemaODDAssistantExperimentTuples * _tuples;
    NSArray * _turnIds;
}

@property (nonatomic, retain) ODDSiriSchemaODDAssistantExperimentCounts *counts;
@property (nonatomic, retain) ODDSiriSchemaODDAssistantExperimentDimensions *dimensions;
@property (nonatomic) bool hasCounts;
@property (nonatomic) bool hasDimensions;
@property (nonatomic) bool hasTuples;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) ODDSiriSchemaODDAssistantExperimentTuples *tuples;
@property (nonatomic, copy) NSArray *turnIds;

- (void).cxx_destruct;
- (void)addTurnIds:(id)arg1;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)clearTurnIds;
- (id)counts;
- (void)deleteCounts;
- (void)deleteDimensions;
- (void)deleteTuples;
- (void)deleteTurnIds;
- (id)dictionaryRepresentation;
- (id)dimensions;
- (bool)hasCounts;
- (bool)hasDimensions;
- (bool)hasTuples;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setCounts:(id)arg1;
- (void)setDimensions:(id)arg1;
- (void)setHasCounts:(bool)arg1;
- (void)setHasDimensions:(bool)arg1;
- (void)setHasTuples:(bool)arg1;
- (void)setTuples:(id)arg1;
- (void)setTurnIds:(id)arg1;
- (id)suppressMessageUnderConditions;
- (id)tuples;
- (id)turnIds;
- (id)turnIdsAtIndex:(unsigned long long)arg1;
- (unsigned long long)turnIdsCount;
- (void)writeTo:(id)arg1;

@end
