/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface STSchemaSTLLMQURequestEnded : SISchemaInstrumentationMessage {
    struct { 
        unsigned int requestLength : 1; 
        unsigned int responseLength : 1; 
    }  _has;
    bool  _hasLlmquPerfMetrics;
    bool  _hasModelNumber;
    bool  _hasQueryArguments;
    STSchemaLLMQUPerfMetrics * _llmquPerfMetrics;
    NSString * _modelNumber;
    STSchemaLLMQUQueryArguments * _queryArguments;
    unsigned int  _requestLength;
    unsigned int  _responseLength;
}

@property (nonatomic) bool hasLlmquPerfMetrics;
@property (nonatomic) bool hasModelNumber;
@property (nonatomic) bool hasQueryArguments;
@property (nonatomic) bool hasRequestLength;
@property (nonatomic) bool hasResponseLength;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) STSchemaLLMQUPerfMetrics *llmquPerfMetrics;
@property (nonatomic, copy) NSString *modelNumber;
@property (nonatomic, retain) STSchemaLLMQUQueryArguments *queryArguments;
@property (nonatomic) unsigned int requestLength;
@property (nonatomic) unsigned int responseLength;

- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)deleteLlmquPerfMetrics;
- (void)deleteModelNumber;
- (void)deleteQueryArguments;
- (void)deleteRequestLength;
- (void)deleteResponseLength;
- (id)dictionaryRepresentation;
- (bool)hasLlmquPerfMetrics;
- (bool)hasModelNumber;
- (bool)hasQueryArguments;
- (bool)hasRequestLength;
- (bool)hasResponseLength;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)llmquPerfMetrics;
- (id)modelNumber;
- (id)queryArguments;
- (bool)readFrom:(id)arg1;
- (unsigned int)requestLength;
- (unsigned int)responseLength;
- (void)setHasLlmquPerfMetrics:(bool)arg1;
- (void)setHasModelNumber:(bool)arg1;
- (void)setHasQueryArguments:(bool)arg1;
- (void)setHasRequestLength:(bool)arg1;
- (void)setHasResponseLength:(bool)arg1;
- (void)setLlmquPerfMetrics:(id)arg1;
- (void)setModelNumber:(id)arg1;
- (void)setQueryArguments:(id)arg1;
- (void)setRequestLength:(unsigned int)arg1;
- (void)setResponseLength:(unsigned int)arg1;
- (id)suppressMessageUnderConditions;
- (void)writeTo:(id)arg1;

@end
