/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RemindersUICore.framework/RemindersUICore
 */

@interface RemindersUICore.TTRQuickEntryReminderCreationInteractorCapability : _TtCs12_SwiftObject

@end
