/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHRemoteRecognizer : NSObject <CHRecognizing> {
    NSXPCConnection * __connection;
    bool  _enableCachingIfAvailable;
    unsigned long long  _maxRecognitionResultCount;
    struct CGSize { 
        double width; 
        double height; 
    }  _minimumDrawingSize;
    long long  _priority;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool enableCachingIfAvailable;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long maxRecognitionResultCount;
@property (nonatomic) struct CGSize { double x1; double x2; } minimumDrawingSize;
@property (nonatomic) long long priority;
@property (readonly) Class superclass;

+ (long long)absoluteMaxStrokeCountPerRequest;

- (void).cxx_destruct;
- (id)connection;
- (void)dealloc;
- (bool)enableCachingIfAvailable;
- (unsigned long long)hash;
- (id)initWithEnableCachingIfAvailable:(bool)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToRemoteRecognizer:(id)arg1;
- (void)logDrawingsAndResultsForRequest:(id)arg1 result:(id)arg2 error:(id)arg3;
- (unsigned long long)maxRecognitionResultCount;
- (struct CGSize { double x1; double x2; })minimumDrawingSize;
- (long long)priority;
- (void)setMaxRecognitionResultCount:(unsigned long long)arg1;
- (void)setMinimumDrawingSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setPriority:(long long)arg1;
- (void)setupXPCConnectionIfNeeded;

@end
