/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleSharingInteractor : _TtCs12_SwiftObject {
    void commandCenter;
    void delegate;
    void headline;
    void tracker;
}

@end
