/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BacklightServicesHost.framework/BacklightServicesHost
 */

@interface BLSHCompletedUpdateOperation : BLSHEnvironmentOperation

+ (id)didCompleteUpdateToBacklightState:(long long)arg1;

@end
