/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MatterPlugin.framework/MatterPlugin
 */

@interface MTRPluginPBMURL : PBCodable <NSCopying> {
    NSString * _value;
}

@property (nonatomic, readonly) bool hasValue;
@property (nonatomic, retain) NSURL *url;
@property (getter=isValid, nonatomic, readonly) bool valid;
@property (nonatomic, retain) NSString *value;

- (void).cxx_destruct;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasValue;
- (unsigned long long)hash;
- (id)initWithURL:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isValid;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setUrl:(id)arg1;
- (void)setValue:(id)arg1;
- (id)url;
- (id)value;
- (void)writeTo:(id)arg1;

@end
