/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFX.VFXSaver : _TtCs12_SwiftObject {
    void isSavingForExport;
    void layout;
    void saveAsPlist;
    void saveBindingsMetadata;
    void targetsToPrecompile;
    void world;
}

@end
