/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFX.EntityClass : _TtCs12_SwiftObject {
    void classComponentstorage;
    void classHash;
    void classIndex;
    void family;
    void hasDirtyPropagation;
    void hasUnstableOrdering;
    void isAnonymous;
    void isGraveyard;
    void isMonoChunk;
    void isTrackingDirty;
    void notifySystemsOnEntityEvent;
    void storageLayout;
}

@end
