/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFX.EntityFamily : _TtCs12_SwiftObject {
    void _componentsIndicesByID;
    void classByClassHash;
    void classComponentTypes;
    void componentTypes;
    void entityComponentTypes;
    void familyHash;
    void familyIndex;
    void packedComponentTypes;
    void storageLayout;
}

@end
