/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFX.GraphTypeInference : _TtCs12_SwiftObject {
    void graph;
    void queue;
    void typeHintByInput;
    void typeHintByOutput;
    void visited;
}

@end
