/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VFX.framework/VFX
 */

@interface VFXCoreEntityHandle : NSObject <NSCopying, NSSecureCoding> {
    NSMutableDictionary * _bindings;
    VFXEntityObject * _entityObject;
    struct __CFXCoreEntityHandle { struct __CFXEntity { struct __CFRuntimeBase { unsigned long long x_1_2_1; _Atomic unsigned long long x_1_2_2; } x_1_1_1; void *x_1_1_2; struct __CFString {} *x_1_1_3; struct __CFString {} *x_1_1_4; struct __CFDictionary {} *x_1_1_5; struct __CFXWorld {} *x_1_1_6; long long x_1_1_7; } x1; struct __CFString {} *x2; struct __CFDictionary {} *x3; struct __CFArray {} *x4; bool x5; void *x6; } * _handle;
    NSString * _tag;
}

@property (nonatomic, readonly) NSArray *bindings;
@property (nonatomic, readonly) VFXEntityObject *entityObject;
@property (nonatomic, readonly) NSString *tag;

+ (id)handleWithEntityObject:(id)arg1;
+ (bool)supportsSecureCoding;

- (void*)__CFObject;
- (void)_syncObjCModel;
- (id)bindingPresentationValueForKey:(id)arg1;
- (id)bindingValueForKey:(id)arg1;
- (id)bindings;
- (id)copy;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (void)didSetEntityObject;
- (void)encodeWithCoder:(id)arg1;
- (id)entityObject;
- (struct __CFXCoreEntityHandle { struct __CFXEntity { struct __CFRuntimeBase { unsigned long long x_1_2_1; _Atomic unsigned long long x_1_2_2; } x_1_1_1; void *x_1_1_2; struct __CFString {} *x_1_1_3; struct __CFString {} *x_1_1_4; struct __CFDictionary {} *x_1_1_5; struct __CFXWorld {} *x_1_1_6; long long x_1_1_7; } x1; struct __CFString {} *x2; struct __CFDictionary {} *x3; struct __CFArray {} *x4; bool x5; void *x6; }*)handle;
- (id)initWithCoder:(id)arg1;
- (id)initWithEntityObject:(id)arg1;
- (id)initWithTag:(id)arg1;
- (void)resolveTag:(id)arg1 remap:(id)arg2;
- (bool)setBindingValue:(id)arg1 forKey:(id)arg2;
- (void)setTag:(id)arg1;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;
- (id)tag;
- (id)valueForKeyPath:(id)arg1;
- (void)wasAddedToWorld:(id)arg1;
- (void)willBeRemovedFromWorld:(id)arg1;
- (id)world;
- (struct __CFXWorld { }*)worldRef;

@end
