/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
 */

@interface _CDInteractionsStatistics : NSObject {
    NSDictionary * _defaultValues;
    NSMutableDictionary * _features;
    NSMutableSet * _hasSharePlayedWith;
    NSMutableDictionary * _personsCountsForRealInteractions;
    NSMutableDictionary * _personsCountsForSyntheticInteractions;
    NSMutableDictionary * _properties;
    NSDictionary * _queryStats;
}

@property (nonatomic, copy) NSDictionary *queryStats;

- (void).cxx_destruct;
- (void)_addConversationId:(id)arg1;
- (id)bundleIdForConversationId:(id)arg1;
- (void)computeFeatureForMethod:(id)arg1 arguments:(id)arg2;
- (void)computeFeaturesForRecipe:(id)arg1;
- (void)computePASSFeatureWithPeopleDetectedInPhoto:(id)arg1;
- (id)conversationIds;
- (void)copyFeature:(id)arg1 toFeatureName:(id)arg2;
- (id)description;
- (id)descriptionRedacted:(bool)arg1;
- (void)divide:(id)arg1 withDivisor:(id)arg2 resultFeatureName:(id)arg3;
- (void)exponential:(id)arg1 withMultiplier:(double)arg2 resultFeatureName:(id)arg3;
- (id)features;
- (bool)hasEverSharePlayed:(id)arg1;
- (void)imputeFeature:(id)arg1 withConstant:(id)arg2;
- (void)includeFeature:(id)arg1 from:(id)arg2;
- (void)incrementValueForFeature:(id)arg1 andConversationId:(id)arg2;
- (void)initFeature:(id)arg1 withValue:(id)arg2;
- (id)initWithDefaultValues:(id)arg1;
- (id)initWithProperties:(id)arg1 features:(id)arg2 defaultValues:(id)arg3;
- (bool)isUsingDefaultValue:(id)arg1 forConversationId:(id)arg2;
- (void)laplaceProbability:(id)arg1 withAlpha:(double)arg2 resultFeatureName:(id)arg3;
- (void)laplaceProbabilityCorrected:(id)arg1 withAlpha:(double)arg2 resultFeatureName:(id)arg3;
- (void)log:(id)arg1 withBase:(double)arg2 resultFeatureName:(id)arg3;
- (void)multiply:(id)arg1 with:(id)arg2 resultFeatureName:(id)arg3;
- (void)multiply:(id)arg1 withMultiplier:(double)arg2 resultFeatureName:(id)arg3;
- (id)nonNilFeaturesForConversationId:(id)arg1;
- (void)power:(id)arg1 withExponent:(double)arg2 resultFeatureName:(id)arg3;
- (id)privatizedConversationId:(id)arg1;
- (id)properties;
- (id)queryStats;
- (void)reciprocal:(id)arg1 withOffset:(double)arg2 resultFeatureName:(id)arg3;
- (void)recordSharePlayInformation:(id)arg1;
- (id)redactedDescription;
- (void)removeConversationIds:(id)arg1;
- (void)renameFeature:(id)arg1 withFeatureName:(id)arg2;
- (void)savePersonId:(id)arg1 forConversationId:(id)arg2 forSyntheticInteraction:(bool)arg3;
- (void)setQueryStats:(id)arg1;
- (void)setValue:(id)arg1 forFeature:(id)arg2 andConversationId:(id)arg3;
- (void)setValue:(id)arg1 forProperty:(id)arg2 andConversationId:(id)arg3;
- (void)sum:(id)arg1 with:(id)arg2 resultFeatureName:(id)arg3;
- (id)valueForFeature:(id)arg1 forConversationId:(id)arg2;
- (id)valueForProperty:(id)arg1 forConversationId:(id)arg2;
- (id)valueOrDefaultValueForFeature:(id)arg1 forConversationId:(id)arg2;

@end
