/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
 */

@interface MBPersona : NSObject {
    bool  _isDataSeparatedPersona;
    NSString * _personaIdentifier;
    NSDictionary * _restoreDepotRootsByVolume;
    _MBUser * _user;
    unsigned long long  _userPersonaType;
    NSString * _volumeMountPoint;
    NSSet * _volumesToBackUp;
}

@property (nonatomic, readonly) long long accountType;
@property (nonatomic, readonly) NSString *appPlaceholderArchiveDirectory;
@property (nonatomic, readonly) NSString *cacheDirectory;
@property (nonatomic, readonly) NSString *demotedAppsPlistPath;
@property (nonatomic, readonly) NSString *dryRestoreContentDirectory;
@property (nonatomic, readonly) NSString *dryRestoreMetadataDirectory;
@property (nonatomic) bool isDataSeparatedPersona;
@property (nonatomic, readonly) bool isEnterprisePersona;
@property (nonatomic, readonly) bool isPersonalPersona;
@property (nonatomic, readonly) NSString *l28BackupTelemetryPlistPath;
@property (nonatomic, retain) NSString *personaIdentifier;
@property (nonatomic, readonly) NSString *placeholderRestoreDirectory;
@property (nonatomic, readonly) NSString *preferencesDirectory;
@property (nonatomic, retain) NSDictionary *restoreDepotRootsByVolume;
@property (nonatomic, readonly) NSString *restoreFailuresPlistPath;
@property (nonatomic, readonly) NSString *restoreKeyBagsPath;
@property (nonatomic, readonly) NSString *restoreOperationLogPath;
@property (nonatomic, readonly) NSString *restoreSnapshotsDatabaseDirectory;
@property (nonatomic, readonly) NSString *safeHarborDirectory;
@property (nonatomic, readonly) NSString *sharedIncompleteRestoreDirectory;
@property (nonatomic, readonly) NSString *sharedRestoreDirectory;
@property (nonatomic, readonly) bool shouldRestoreToSharedVolume;
@property (nonatomic, readonly) NSString *skippedFileRecordsPlistPath;
@property (nonatomic, readonly) NSString *snapshotDatabaseDirectory;
@property (nonatomic, readonly) NSString *sqliteCopyDirectory;
@property (nonatomic, readonly) NSString *systemContainersVolumeMountPoint;
@property (nonatomic, readonly) NSString *systemDataContainerRestoreDirectory;
@property (nonatomic, readonly) NSString *systemSharedDataContainerRestoreDirectory;
@property (nonatomic, readonly) _MBUser *user;
@property (nonatomic, readonly) NSString *userDataVolume;
@property (nonatomic, readonly) NSString *userIncompleteRestoreDirectory;
@property (nonatomic) unsigned long long userPersonaType;
@property (nonatomic, readonly) NSString *userRestoreDirectory;
@property (nonatomic, readonly) NSString *volumeMapPlistPath;
@property (nonatomic, retain) NSString *volumeMountPoint;
@property (nonatomic, retain) NSSet *volumesToBackUp;

+ (void)installPersonaForTesting;
+ (Class)personaClass;
+ (id)personaWithAttributes:(id)arg1 volumeMountPoint:(id)arg2;
+ (id)personaWithIdentifier:(id)arg1 userPersonaType:(unsigned long long)arg2 dataSeparatedPersona:(bool)arg3 volumeMountPoint:(id)arg4;
+ (id)personaWithUMPersona:(id)arg1 error:(id*)arg2;

- (void).cxx_destruct;
- (id)_userRestorePrefetchDirectory;
- (long long)accountType;
- (id)appPlaceholderArchiveDirectory;
- (id)cacheDirectory;
- (id)demotedAppsPlistPath;
- (id)description;
- (id)dryRestoreContentDirectory;
- (id)dryRestoreMetadataDirectory;
- (id)initWithPersonaAttributes:(id)arg1 volumeMountPoint:(id)arg2;
- (id)initWithPersonaIdentifier:(id)arg1 userPersonaType:(unsigned long long)arg2 dataSeparatedPersona:(bool)arg3 volumeMountPoint:(id)arg4;
- (id)initWithUMPersona:(id)arg1 error:(id*)arg2;
- (bool)isDataSeparatedPersona;
- (bool)isEnterprisePersona;
- (bool)isPersonalPersona;
- (id)l28BackupTelemetryPlistPath;
- (id)personaIdentifier;
- (id)placeholderRestoreDirectory;
- (id)preferencesDirectory;
- (void)removeRestoreKeybags;
- (id)restoreDepotRootsByVolume;
- (id)restoreFailuresPlistPath;
- (id)restoreKeyBagsPath;
- (id)restoreOperationLogPath;
- (id)restorePrefetchDirectories;
- (id)restorePrefetchDirectoryForDomain:(id)arg1;
- (id)restoreSnapshotsDatabaseDirectory;
- (id)safeHarborDirectory;
- (void)setIsDataSeparatedPersona:(bool)arg1;
- (void)setPersonaIdentifier:(id)arg1;
- (void)setRestoreDepotRootsByVolume:(id)arg1;
- (void)setUserPersonaType:(unsigned long long)arg1;
- (void)setVolumeMountPoint:(id)arg1;
- (void)setVolumesToBackUp:(id)arg1;
- (id)sharedIncompleteRestoreDirectory;
- (id)sharedRestoreDirectory;
- (bool)shouldRestoreToSharedVolume;
- (id)skippedFileRecordsPlistPath;
- (id)snapshotDatabaseDirectory;
- (id)sqliteCopyDirectory;
- (id)systemContainersVolumeMountPoint;
- (id)systemDataContainerRestoreDirectory;
- (id)systemSharedDataContainerRestoreDirectory;
- (id)user;
- (id)userDataVolume;
- (id)userIncompleteRestoreDirectory;
- (unsigned long long)userPersonaType;
- (id)userRestoreDirectory;
- (id)volumeMapPlistPath;
- (id)volumeMountPoint;
- (id)volumesToBackUp;

@end
