/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSignals.framework/SiriSignals
 */

@interface SiriSignals.MockAppRecordProvider : _TtCs12_SwiftObject {
    void resultPrefix;
}

@end
