/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
 */

@interface ASCredentialRequestEnableICloudKeychainViewController : ASCredentialRequestPaneViewController {
    bool  _canKeychainSyncBeEnabled;
}

- (void)_turnOnICloudKeychain;
- (id)init;
- (void)viewDidLoad;

@end
