/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
 */

@interface _TtCV14AppleAccountUI20CustodianDetailsView11Coordinator : _TtCs12_SwiftObject {
    void contact;
}

@end
