/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaFoundation.framework/TeaFoundation
 */

@interface TFInterprocessDiagnosticDumpNotifier : NSObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  diagnosticTempDir;
    void interprocessDiagnosticDumpNotification;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithNotificationName:(id)arg1 diagnosticTempDir:(id)arg2 log:(id)arg3;
- (void)triggerDiagnosticFileDump;

@end
