/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface _PLSharedStreamsEnablementStateObserver : NSObject

- (void)accountStoreDidChange;
- (void)dealloc;
- (id)init;

@end
