/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLManagedObjectPagingIterator : NSObject {
    NSPredicate * _additionalPredicate;
    unsigned long long  _batchSize;
    NSString * _entityName;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    unsigned long long  _lock_countRemaining;
    bool  _lock_isFinished;
    NSDate * _lock_lastFetchCountTime;
    NSMutableArray * _lock_resultQueue;
    NSManagedObjectID * _lock_resumeObjectID;
    NSArray * _propertiesToFetch;
    NSArray * _relationshipKeyPathsToPrefetch;
    unsigned long long  _resultType;
}

@property (nonatomic, readonly) NSPredicate *additionalPredicate;
@property (nonatomic, readonly) unsigned long long batchSize;
@property (nonatomic, readonly, copy) NSString *entityName;
@property (nonatomic, readonly, copy) NSArray *propertiesToFetch;
@property (nonatomic, readonly, copy) NSArray *relationshipKeyPathsToPrefetch;
@property (nonatomic, readonly) unsigned long long resultType;
@property (nonatomic, readonly) NSManagedObjectID *resumeObjectID;

+ (id)_nextBatchOfResultsWithManagedObjectContext:(id)arg1 entityName:(id)arg2 resultType:(unsigned long long)arg3 resumeObjectID:(id)arg4 additionalPredicate:(id)arg5 batchSize:(unsigned long long)arg6 propertiesToFetch:(id)arg7 relationshipKeyPathsToPrefetch:(id)arg8;

- (void).cxx_destruct;
- (bool)_lock_shouldFetchCountRemaining;
- (id)_neverCallWithLock_refillResultQueueWithManagedObjectContext:(id)arg1;
- (void)_updateResumeObjectIDWithObject:(id)arg1 progressCount:(unsigned long long)arg2;
- (id)additionalPredicate;
- (unsigned long long)batchSize;
- (id)countRemainingWithManagedObjectContext:(id)arg1 logger:(id)arg2;
- (id)entityName;
- (id)initWithEntityName:(id)arg1 resultType:(unsigned long long)arg2 resumeObjectID:(id)arg3 additionalPredicate:(id)arg4;
- (id)initWithEntityName:(id)arg1 resultType:(unsigned long long)arg2 resumeObjectID:(id)arg3 additionalPredicate:(id)arg4 batchSize:(unsigned long long)arg5 propertiesToFetch:(id)arg6 relationshipKeyPathsToPrefetch:(id)arg7;
- (id)nextBatchWithManagedObjectContext:(id)arg1;
- (id)nextObjectWithManagedObjectContext:(id)arg1;
- (id)propertiesToFetch;
- (id)relationshipKeyPathsToPrefetch;
- (void)reset;
- (unsigned long long)resultType;
- (id)resumeObjectID;

@end
