/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLTimedDispatchGroupEnterSession : NSObject {
    NSObject<OS_dispatch_group> * _group;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    bool  _lock_didLeave;
    PLResult * _lock_result;
    NSString * _name;
    NSObject<OS_dispatch_queue> * _queue;
    double  _timeout;
}

- (void).cxx_destruct;
- (void)_handleTimeoutCallback;
- (bool)_lock_leaveIfPossible;
- (void)cancel;
- (id)description;
- (bool)didTimeout;
- (void)enter;
- (id)initWithGroup:(id)arg1 queue:(id)arg2 timeout:(double)arg3 name:(id)arg4;
- (bool)leave;
- (bool)leaveWithResult:(id)arg1;
- (id)result;
- (bool)wasCancelled;

@end
