/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSuggestionsKit.framework/SiriSuggestionsKit
 */

@interface SiriSuggestionsKit.SystemUserDefaultsProvider : _TtCs12_SwiftObject {
    void suggestionsUserDefaults;
}

@end
