/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Settings.framework/Settings
 */

@interface Settings.SettingsUndoManager : _TtCs12_SwiftObject {
    void actions;
    void activeUndoGroup;
    void connection;
    void isUndoing;
    void unitTest;
}

@end
