/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIPrivate.framework/PhotosUIPrivate
 */

@interface PUCleanupToolFaceRectsView : UIView {
    <PUCleanupFaceRectsImageSizeDelegate> * _faceRectsImageSizeDelegate;
    bool  _isHDR;
    NUMediaView * _mediaView;
    bool  _needsClearing;
}

@property (nonatomic) <PUCleanupFaceRectsImageSizeDelegate> *faceRectsImageSizeDelegate;
@property (nonatomic) bool isHDR;
@property (nonatomic) NUMediaView *mediaView;
@property (nonatomic) bool needsClearing;

- (void).cxx_destruct;
- (id)faceRectsImageSizeDelegate;
- (id)initWithMediaView:(id)arg1 isHDR:(bool)arg2 delegate:(id)arg3;
- (bool)isHDR;
- (id)mediaView;
- (bool)needsClearing;
- (void)setFaceRectsImageSizeDelegate:(id)arg1;
- (void)setIsHDR:(bool)arg1;
- (void)setMediaView:(id)arg1;
- (void)setNeedsClearing:(bool)arg1;
- (void)updateDetectedFaces:(id)arg1 imageOrientation:(long long)arg2;

@end
