/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUIPrivate.framework/PhotosUIPrivate
 */

@interface PUPXPhotoKitRemoveStacksActionPerformer : PXPhotoKitAssetActionPerformer <PXActivityActionDelegate>

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)canPerformWithSelectionSnapshot:(id)arg1 person:(id)arg2 socialGroup:(id)arg3;
+ (id)localizedTitleForUseCase:(unsigned long long)arg1 actionManager:(id)arg2;

- (void)performUserInteractionTask;

@end
