/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
 */

@interface MXRoutingContextController : NSObject {
    NSString * _routingContextUUID;
    int  mDiscovererType;
    struct OpaqueFigRoutingContext { } * mRoutingContext;
}

@property (getter=isContextPrewarmed, nonatomic) bool contextPrewarmed;
@property (nonatomic, readonly) NSArray *currentRoutes;
@property (nonatomic, readonly) NSString *routingContextUUID;

- (id)currentRoutes;
- (void)dealloc;
- (id)discoverRouteDescriptorsWithRouteUUIDS:(id)arg1 forDiscoverer:(struct OpaqueFigRouteDiscoverer { }*)arg2;
- (id)initWithRoutingContextUUID:(id)arg1;
- (bool)isContextPrewarmed;
- (void)prewarmRoutesWithUUIDs:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)routeDescriptorsWithRouteIDs:(id)arg1 discoverer:(struct OpaqueFigRouteDiscoverer { }*)arg2;
- (id)routingContextUUID;
- (void)selectRouteDescriptors:(id)arg1;
- (void)setContextPrewarmed:(bool)arg1;

@end
