/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEOGeographicMetadataRequesterDelegateDataBlockAdapter : NSObject <GEOGeographicMetadataRequesterDelegate> {
    id /* block */  _block;
}

@property (readonly, copy) NSString *debugDescription; /* unknown property attribute: ? */
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)geoGeographicMetadataRequester:(id)arg1 failedWithError:(id)arg2 forLocation:(id)arg3;
- (void)geoGeographicMetadataRequester:(id)arg1 resultsDidNotChangeForLocation:(id)arg2;
- (void)geoGeographicMetadataRequester:(id)arg1 returnedNewResults:(id)arg2 forLocation:(id)arg3;
- (void)geoGeographicMetadataRequester:(id)arg1 skippedLocation:(id)arg2;
- (id)initWithBlock:(id /* block */)arg1;

@end
