/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RequestDispatcherBridges.framework/RequestDispatcherBridges
 */

@interface RequestDispatcherBridges.MUXBridgeInstrumentationUtil : _TtCs12_SwiftObject {
    void commonInstrumentationUtil;
    void stream;
}

@end
