/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreML.framework/CoreML
 */

@interface MLModelStructure : NSObject {
    MLModelStructureNeuralNetwork * _neuralNetwork;
    MLModelStructurePipeline * _pipeline;
    MLModelStructureProgram * _program;
}

@property (nonatomic, readonly) MLModelStructureNeuralNetwork *neuralNetwork;
@property (nonatomic, readonly) MLModelStructurePipeline *pipeline;
@property (nonatomic, readonly) MLModelStructureProgram *program;

+ (void)loadContentsOfURL:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)loadModelAsset:(id)arg1 completionHandler:(id /* block */)arg2;
+ (id)loadModelStructureFromCompiledArchive:(void*)arg1 path:(struct Path { struct vector<std::variant<CoreML::ModelStructure::Path::Root, CoreML::ModelStructure::Path::Program, CoreML::ModelStructure::Path::Program::Function, CoreML::ModelStructure::Path::Program::Block, CoreML::ModelStructure::Path::Program::Operation, CoreML::ModelStructure::Path::NeuralNetwork, CoreML::ModelStructure::Path::NeuralNetwork::Layer, CoreML::ModelStructure::Path::Pipeline, CoreML::ModelStructure::Path::Pipeline::SubModel>, std::allocator<std::variant<CoreML::ModelStructure::Path::Root, CoreML::ModelStructure::Path::Program, CoreML::ModelStructure::Path::Program::Function, CoreML::ModelStructure::Path::Program::Block, CoreML::ModelStructure::Path::Program::Operation, CoreML::ModelStructure::Path::NeuralNetwork, CoreML::ModelStructure::Path::NeuralNetwork::Layer, CoreML::ModelStructure::Path::Pipeline, CoreML::ModelStructure::Path::Pipeline::SubModel>>> { void *x_1_1_1; void *x_1_1_2; struct __compressed_pair<std::variant<CoreML::ModelStructure::Path::Root, CoreML::ModelStructure::Path::Program, CoreML::ModelStructure::Path::Program::Function, CoreML::ModelStructure::Path::Program::Block, CoreML::ModelStructure::Path::Program::Operation, CoreML::ModelStructure::Path::NeuralNetwork, CoreML::ModelStructure::Path::NeuralNetwork::Layer, CoreML::ModelStructure::Path::Pipeline, CoreML::ModelStructure::Path::Pipeline::SubModel> *, std::allocator<std::variant<CoreML::ModelStructure::Path::Root, CoreML::ModelStructure::Path::Program, CoreML::ModelStructure::Path::Program::Function, CoreML::ModelStructure::Path::Program::Block, CoreML::ModelStructure::Path::Program::Operation, CoreML::ModelStructure::Path::NeuralNetwork, CoreML::ModelStructure::Path::NeuralNetwork::Layer, CoreML::ModelStructure::Path::Pipeline, CoreML::ModelStructure::Path::Pipeline::SubModel>>> { void *x_3_2_1; } x_1_1_3; } x1; })arg2 error:(id*)arg3;

- (void).cxx_destruct;
- (id)initWithNeuralNetwork:(id)arg1;
- (id)initWithNeuralNetwork:(id)arg1 program:(id)arg2 pipeline:(id)arg3;
- (id)initWithPipeline:(id)arg1;
- (id)initWithProgram:(id)arg1;
- (id)neuralNetwork;
- (id)pipeline;
- (id)program;

@end
