/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SharingUI.framework/SharingUI
 */

@interface SharingUI.SFRemoteAlertPresentationManager : NSObject {
    void remoteAlertPresentationHandlesByID;
}

- (void).cxx_destruct;
- (id)init;

@end
