/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreIDVPAD.framework/CoreIDVPAD
 */

@interface CoreIDVPAD.PADAVAssetReader : _TtCs12_SwiftObject {
    void asset;
    void track;
}

@end
