/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UnifiedMessagingKit.framework/UnifiedMessagingKit
 */

@interface UnifiedMessagingKit.DestinationFactory : _TtCs12_SwiftObject

@end
