/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UnifiedMessagingKit.framework/UnifiedMessagingKit
 */

@interface UnifiedMessagingKit.UMMetricsEventRecorder : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  account;
    void metricsConfiguration;
    void metricsEventRecorder;
}

@end
