/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UnifiedMessagingKit.framework/UnifiedMessagingKit
 */

@interface UnifiedMessagingKit.JavascriptService : _TtCs12_SwiftObject {
    void configuration;
    void engineProvider;
}

@end
