/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/APConfigurationSystem.framework/APConfigurationSystem
 */

@interface APConfigurationMediator : NSObject

+ (id)_configSystemErrorWithDescription:(id)arg1;
+ (id)_loadFromDefaultsForClass:(Class)arg1 error:(id*)arg2;
+ (id)_loadFromJSONForClass:(Class)arg1 error:(id*)arg2;
+ (void)_removeFileAtPath:(id)arg1;
+ (id)_resourcesBundleDirectoryPathError:(id*)arg1;
+ (id)configSystemDirectoryPath;
+ (id)configurationForClass:(Class)arg1;
+ (id)configurationForClass:(Class)arg1 usingCache:(bool)arg2;
+ (id)resourcesBundleDirectoryPath;

@end
