/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextToSpeechVoiceBankingUI.framework/TextToSpeechVoiceBankingUI
 */

@interface TTS_AXLanguageManagerWrapper : NSObject

+ (id)dialectForLanguageId:(id)arg1;

@end
